siglens/siglens

selenium-tests/package-lock.json, selenium-tests/package.json, selenium-tests/tests/cluster-stats-test.js, selenium-tests/tests/dashboard-test.js, selenium-tests/tests/index-test.js, selenium-tests/tests/panelEditScreen-test.js, selenium-tests/tests/saved-queries-test.js, ui-test/package.txt, ui-test/specs/available-fields/available-fields.html, ui-test/specs/available-fields/available-fields.js, ui-test/specs/common.js, ui-test/specs/index/index.html, ui-test/specs/index/index.js, ui-test/specs/search/search.html, ui-test/specs/search/search.js
=> add ui test

cmd/siglens/main.go, cmd/startup/startup.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/derivedConfig.go
PR For the issues : https://github.com/siglens/siglens/issues/31
Updated the GetQueryPort func to get value from env variable
=> #31 Updated GetQueryport func to get value from env 

install_with_git.sh
This script should do the following steps:
1. Check if git is installed (if not prompt the user to install git locally and have them create a GitHub account)
2. Create siglen-contrib and `git clone git@github.com:siglens/siglens.git` into this folder.
3. Go to this repository and run `go  mod tidy`
4. Check if current user is allowed to open. if yes do` go run cmd/siglens/main.go -config server.yaml` on port 80, else do `PORT=8090 go run cmd/siglens/main.go -config server.yaml`
5. Display a msg that SigLens is running on port [http://localhost:80](http://localhost/) or port http://localhost:8090/ depending on above 2 steps
=> Create install_with_git.sh script

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/searchHandler_test.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/tracing/handler/traceHandler.go, pkg/segment/tracing/handler/tracehandler_test.go, pkg/segment/tracing/structs/tracestruct.go, pkg/segment/tracing/traceHandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
Add Search traces Api endpoint.
=> Search traces2

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go
=> Remove redundant code

static/css/tracing.css, static/dependency-graph.html, static/js/dependency-graph.js, static/js/navbar.js, static/js/search-traces.js, static/js/service-health.js, static/search-traces.html, static/service-health.html
- Added initial HTML, JS and CSS files for Tracing UI 
HTML - search-traces.html , dependency-graph.html , service-health.html 
JS - search-traces.js, dependency-graph.js , service-health.js
CSS - tracing.css
- Also added an icon in the side navbar, using the live tail icon temporarily, as the tracing icon has not been designed yet.
- Three subsections have been included at the top of the training screen.
- On the service health screen, I've added an input box to search for any service and a table with columns (service, rate, error, duration). - does not include any backend integration.
=> Added Initial Tracing Files (HTML, JS, CSS)

static/contacts.html, static/js/contacts.js
=> UI : Show Contact Name in Delete Confirmation Popup #101

README.md
added links to docs pages for getting started readme
=> added links to docs pages for getting started readme

pkg/config/version.go
=> version update for release

.github/workflows/publish-prod-images.yml, package_siglens.sh
=> fix for mac build failure

.github/workflows/publish-prod-images.yml, package_siglens.sh
=> fix error for mac/darwin binary

.github/workflows/publish-prod-images.yml, package_siglens.sh, pkg/ast/pipesearch/searchHandler.go, pkg/common/dtypeutils/dtypeutils.go, pkg/server/query/entryHandlers.go, pkg/utils/accessLogUtils.go, pkg/utils/accesslogutils_test.go
=> Fix binary build failure without version update

CODE_OF_CONDUCT.md
=> added readme for code of conduct

.github/CODEOWNERS
This should make it so that when someone updates the cicd files like ingest.csv and restart.csv, Sunita and I are added as reviewers for the PR. Previously, those files were only matched by line 2, so everyone was added as a reviewer
No testing
=> Update CODEOWNERS for the cicd folder

static/index.html, static/js/download-logs.js
=> FIx - Download Logs and CSV Typo

pkg/ast/pipesearch/searchHandler.go, pkg/segment/tracing/handler/tracehandler.go, pkg/segment/tracing/structs/tracestruct.go
In the past, red metrics would only aggregate data from the previous one hundred spans. Now it will process all the spans which should be correct.
=> Fix service health issue

static/css/query-builder.css, static/css/siglens.css, static/css/tracing.css, static/dependency-graph.html, static/js/dependency-graph.js, static/js/service-health.js, static/service-health.html
Fixes #82  (link all the GitHub issues this addresses)
=> Dependency Graph UI

static/css/siglens.css, static/css/tracing.css, static/js/service-health-overview.js, static/js/service-health.js, static/service-health-overview.html
1. One Service Overview 
a. CSS Styling (Dont have figma for that)
b. Dark mode CSS.
2. Service Health Overview 
a. Add units to columns
b. Add a sort(A->Z) icon to each column.
c. Initially sort the rows based on Error Column ( desc - maximum first)
d. Reduce the Rate column to two values after decimal.
=> Service Health of one Service : CSS

static/alert.html, static/css/siglens.css
Fix the issue related to the info icon on the alert screen.
=> Fix : Info Icon Alert UI

pkg/segment/tracing/handler/tracehandler.go, static/js/dependency-graph.js
When request comes in from UI, Get dependency graph by querying traces directly.
Added check to fix runtime error in ProcessRedTracesIngest
=> tracing-change dependancy graph logic

API_README.md, pkg/segment/tracing/structs/tracestruct.go, pkg/segment/tracing/utils/buildspantree.go
Determine whether a span is anomalous for the spans in Gantt Chart Endpoint. If a child span start before its parent, its is anomalous.
=> Determine whether a span is anomalous

.github/workflows/publish-prod-images.yml, package_siglens.sh, pkg/config/version.go
=> yaml changes to fix build failure

package_siglens.sh
=> test changes for prod build

package_siglens.sh
=> add flag to fix  prod build

package_siglens.sh
=> darwin build- use o64-clang

.github/workflows/publish-prod-images.yml, install_with_binary.sh, package_siglens.sh, pkg/config/version.go
=> Fix binary script

install_with_docker.sh
Fix some issues for the docker install script
On mac os, Ubuntu 22.04.01 Lts, CentOS 7
=> Fix some issues for the docker install script

static/css/siglens.css, static/css/tracing.css, static/js/search-traces.js, static/js/trace.js, static/trace.html
=> Gantt Chart Basics

docker-compose.yml, install_with_docker.sh
- Adds docker-compose.yml file to run siglens with new release version
- Modified install_with_docker.sh file to use docker-compose.yml
Fixes #268 (https://github.com/siglens/siglens/issues/268)
- Tested the changes on ubuntu, debian images on digitial ocean droplet and Tested locally in MacOS by executing `install_with_docker.sh` file
=> PR: Refactors installation script to use docker compose

Dockerfile, README.md, pkg/alerts/alertsHandler/alertsHandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, static/application-version.html, static/cluster-stats.html, static/contacts.html, static/js/all-alerts.js, static/js/application-version.js, static/js/cluster-stats.js, static/js/contacts.js, static/js/settings.js, static/org-settings.html, static/test-data.html
- Added an API endpoint to fetch the application version from pkg/config/version.go.
- Created new HTML and JavaScript files to display the application version in the UI as a tab.
- Embedded the application version into the Docker image during the build process for consistent version tracking.
Fixes #249 (link all the GitHub issues this addresses)
Visually inspected the new tab in various browsers (Chrome, Firefox, Safari) to ensure proper rendering.
Checked that the correct version is displayed by comparing it with the version in pkg/config/version.go.
=> feat: Implement Version Display and Embedding in Build Process

pkg/config/version.go
=> Updated verison for release

pkg/config/version.go
=> updated version for release

.github/workflows/publish-prod-images.yml, install_with_docker.sh, pkg/ast/common.go, pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/config/version.go, pkg/dashboards/dashboards.go, pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/timechartagg.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/results/blockresults/runningstats_test.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/segstructs.go, pkg/segment/utils/timeconsts.go, pkg/segment/writer/segstore.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
=> change branch for new release from develop to main

.github/workflows/publish-prod-images.yml, install_with_docker.sh, pkg/config/version.go
=> merge from develop to main for new release

static/assets/search-icon-active.svg, static/assets/search-icon-inactive.svg, static/css/siglens.css
=> Navbar Fix

pkg/segment/aggregations/timechartagg.go, pkg/segment/results/blockresults/blockresult.go
Sort time range buckets based on the timestamp before returning result to front end
=> Sort spl timechart's result based on the timestamp

pkg/segment/aggregations/segaggs.go, pkg/segment/reader/record/rrcreader.go
Fix bug for rex block without group by cols.
=> Fix: Spl rex block

static/component/download/download.css, static/component/single-box/single-box.css, static/css/dashboard.css, static/css/query-builder.css, static/css/siglens.css, static/css/tracing.css, static/dashboard.html, static/index.html, static/js/all-alerts.js, static/js/contacts.js, static/js/dashboard.js, static/js/dashboards-home.js, static/js/event-handlers.js, static/js/log-results-grid.js, static/js/minion-searches.js, static/js/navbar.js, static/js/saved-query.js, static/js/service-health.js, static/live-tail.html, static/org-settings.html, static/service-health-overview.html, static/service-health.html
=> Font size update

Dockerfile
=> make siglens binary to be owned by siglens user

pkg/config/version.go
=> release 0.1.10

Dockerfile, pkg/config/version.go
=> fix docker build and update version

Dockerfile, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/sql/astsql.go, pkg/ast/sql/sqlparser_test.go, pkg/config/version.go, pkg/segment/aggregations/segaggs.go
=> release 0.1.11

pkg/config/version.go
=> release 0.1.12

pkg/config/version.go
=> release 0.1.13

static/alert-details.html, static/alert.html, static/all-alerts.html, static/application-version.html, static/cluster-stats.html, static/component/upper-navbar/upper-navbar.js, static/contacts.html, static/dependency-graph.html, static/js/application-version.js, static/js/cluster-stats.js, static/js/navbar.js, static/org-settings.html, static/search-traces.html, static/service-health.html, static/test-data.html
Created a component for the upper navbar and used it in My Org, Alerting, and Tracing pages. 
Application-Version page was getting some error logs; fixed that.
=> Added Upper Navbar Component

static/js/common.js, static/js/query-builder.js
=> Display Timechart Only for Timechart Queries

pkg/segment/writer/segstore.go
Updates the error message, as requested https://github.com/siglens/siglens/pull/353/files#r1443563100
I've not tested this
=> Update error message when colWips is too large

pkg/ast/pipesearch/searchQueryParser.go
Before, if `result, err := json.MarshalIndent(res, "", "   ")` failed, the query would stop. However, this is a nonessential thing and just used for pretty printing. With this PR, the query continues even if this part fails.
Not tested
=> Don't stop a query when pretty printing fails

install_with_docker.sh
=> fix docker start issue on uid greater than 1000

pkg/config/version.go
=> release 0.1.14

pkg/ast/common.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go
Fixes #103 (link all the GitHub issues this addresses)
I added a new column in sigscalr-client (reader.go) which has random boolean values. I then ingested the generated data to the running server and tested the query like so, <column-name>=true (without quotes)
=> feat: querying for boolean values

tools/nyc-taxi-benchmark/ingester.py, tools/nyc-taxi-benchmark/parquet_to_tsv.py, tools/nyc-taxi-benchmark/requirements.txt
Adds the scripts from https://github.com/siglens/siglens-docs/blob/develop/docs/benchmarks/nyc-taxi-benchmark-runbook.md
=> Add benchmark scripts

install_with_docker.sh, pkg/config/version.go
=> release 0.1.15

Dockerfile, static/dashboard.html
=> Add Default dashboards  dockerchange

pkg/config/version.go
=> release 0.1.16

static/css/dashboard.css, static/js/dashboard.js, static/js/navbar.js
=> Dashboard Panel Fix

docker-compose.yml, install_with_docker.sh, playground.yaml, static/js/settings.js
change docker to accept config file from env var
For playground server, set environment variable CONFIG_FILE=playground.yaml
=> Add playground yaml

pkg/config/version.go
=> release 0.1.17

.circleci/config.yml
=> change circleci_docker version

.circleci/config.yml
=> change circleci_docker version (#402)

pkg/config/version.go
=> release 0.1.18

pkg/config/version.go
=> Release 0.1.19

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/alerts/alertsqlite/alerts_sqlite.go, pkg/alerts/alertutils/alertutils.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
Creates a alert history table to create track specific alerts in a chronological order whenever
- Alert config changed 
- Every time the alert was fired or went normal
**Implementations**
1. Implements `/api/alerts/{alertId}/history` endpoint to fetch all the alert events triggered. Frontend can leverage this endpoint to display specific alert history in a tabular format with columns `Timestamp`,  `Username`,  `EventDescriptiton`.
2. Implements `CreateAlertHistory` method to create an entry whenever config changed by user / system generated alerts.
Fixes #19 (https://github.com/siglens/siglens/pull/247)
- Tested from UI by changing the config and below is the record stored in DB.
- Tested GET `api/alerts/{alertID}/history` endpoint from postman able to successfully fetch all events …
=> PR: Adds logic to track alert history

install_with_docker.sh
Pass csi value to docker-compose as env var
=> Fix: CSI value missing warning

pkg/config/version.go
=> Increment version to 0.1.20

install.sh, install_with_docker.sh, pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/alerts/alertsqlite/alerts_sqlite.go, pkg/alerts/alertutils/alertutils.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/config/version.go, pkg/dashboards/dashboards.go, pkg/segment/aggregations/segaggs.go, pkg/segment/query/querystatus.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/segexecution.go, pkg/segment/segexecutionbench_test.go, pkg/segment/structs/evaluationstructs.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, podman-compose.yml, podman-network_siglens.conflist, static/js/dashboards-home.js
=> Release 0.1.20

.github/workflows/publish-prod-images.yml
=> changes to add latest tag to docker build

pkg/config/version.go
=> Update version to 0.1.21

pkg/segment/tracing/handler/tracehandler_test.go
This PR contains the test cases for ParseAndValidateRequestBody, GetTotalUniqueTraceIds and GetUniqueTraceIds
Executed the tests in the entire file 
=> Test cases for tracehandler

pkg/config/version.go
=> Update version to 0.1.22

.github/workflows/publish-prod-images.yml
=> Revert "Update publish-prod-images.yml"

install.sh
- Pulls the Podman files from the release assets in the `install.sh`
=> Pull podman files from the release assets

static/js/test-data.js
Fix send test data end point, do not route using ingestionURL
=> remove ingestionURL for sending test data

static/js/query-builder.js
=> Remove '_index' and 'timestamp' column from query builder

.github/workflows/publish-prod-images.yml, pkg/config/version.go
Release Notes
1. Added Trace Span 'Tags' in Tooltip
2. SPL- Allow aggregation after Extracting fields
3. Make Ingest and Query Listen IP Addresses configurable
4. Install script change
=> update version to 0.1.23

.github/workflows/publish-prod-images.yml, cmd/startup/startup.go, install.sh, install_with_docker.sh, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/version.go, pkg/segment/aggregations/segaggs.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/reader/segread/segstatsreader.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/results/segresults/segresults.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go, pkg/segment/segexecution.go, pkg/segment/structs/segstructs.go, pkg/ssa/ssa.go, playground.yaml, server.yaml, static/css/query-builder.css, static/css/siglens.css, static/js/available-fields.js, static/js/query-builder.js, static/js/search-traces.js, static/js/test-data.js, static/js/trace.js
Release Notes
1. Added Trace Span 'Tags' in Tooltip
2. SPL- Allow aggregation after Extracting fields
3. Make Ingest and Query Listen IP Addresses configurable
4. Install script change
=> update version 0.1.23

cmd/startup/startup.go, pkg/blob/blobStorage.go, pkg/cfghandler/pqsupdate_test.go, pkg/config/common/common.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/derivedConfig.go, pkg/es/reader/esQueryHandler.go, pkg/es/writer/esBulkHandler.go, pkg/es/writer/esBulkHandler_test.go, pkg/health/clusterStatsHandler.go, pkg/hooks/hooks.go, pkg/retention/retention.go, pkg/retention/retention_test.go, pkg/retention/retutils.go, pkg/segment/query/summary/querysummary.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/server/ingest/entryHandlers.go, pkg/server/ingest/middleware.go, pkg/server/ingest/server.go, pkg/server/query/entryHandlers.go, pkg/server/query/middleware.go, pkg/server/query/server.go, pkg/usageStats/compressedstats.go, pkg/usageStats/stats.go, pkg/utils/httpserverutils.go, pkg/virtualtable/virtualtable.go, pkg/virtualtable/virtualtable_test.go
This adds some hooks for the backend
=> Add backend hooks

cmd/startup/startup.go, pkg/hooks/hooks.go
Adds a hook for `StartSiglensServer()`
=> Add hook for StartSiglensServer

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/searchHandler_test.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/spl/spl.go, pkg/segment/tracing/handler/tracehandler.go
- Added code to check unexpected fields in search endpoint's body
- If unexpected field exists in body, HTTP 400 will be returned to the user
- Added a test case 
- Fixed another minor bug in searchHandler
Fixes #577 
- Added a test case 
- Tested manually 
=> Add validation and error handling to search endpoint

static/css/dashboard.css, static/css/siglens.css, static/js/dashboard-charts.js, static/js/dashboard.js, static/js/edit-panel-screen.js, static/js/search.js
1. Improved copy button style in Dashboard settings JSON section.
2. Resolved issue causing errors when saving or applying changes to black panels, fix functionality to return to the dashboard.
3. Fixed console errors related to the View Panel function for black panels.
4. Chart display when opening the edit panel.
5. Fixed chart resizing functionality on the edit panel screen.
6. Fixed issues with timechart visualization.
=> Dashboard and Timechart Fix

pkg/segment/tracing/handler/tracehandler.go
=> Search-traces Fix

cmd/startup/startup.go, pkg/hooks/hooks.go
=> added hooks for org check

pkg/config/version.go
=> update siglens version

pkg/config/config.go
=> Revert "Fix GetQueryServerBaseUrl (#615)"

.circleci/config.yml
=> disable selenium tests

.github/workflows/publish-prod-images.yml, pkg/config/version.go
=> Release 0.1.27

pkg/config/version.go, static/js/search-traces.js
- Remove localhost for the trace count endpoint.
=> fix: removed locahost for trace count endpoint

pkg/config/version.go, static/js/search-traces.js
=> fix: removed locahost for trace count endpoint (#634)

pkg/config/version.go
=> Bump SigLens version

pkg/ast/pipesearch/resultStructs.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/spl/spl.go, static/js/common.js, static/js/log-results-grid.js, static/js/search.js
Move the flag `SortByTimestampAtDefault` from the struct PipeSearchCompleteResponse to PipeSearchWSUpdateResponse. 
Added a flag to the UI code to render the table accordingly.
=> UI fix for sort query

CONTRIBUTING.md
=> Update golangci-lint link

pkg/config/version.go
- SigLens Release version: 0.1.30
=> SigLens Release Version - 0.1.30

CONTRIBUTING.md, go.mod, go.sum, pkg/ast/pipesearch/resultStructs.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/spl/spl.go, pkg/config/version.go, pkg/health/clusterStatsHandler.go, pkg/hooks/hooks.go, pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/segaggs_test.go, pkg/segment/reader/record/recordreader.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/segexecution.go, pkg/segment/segexecutionbench_test.go, pkg/segment/structs/segstructs.go, pkg/server/query/entryHandlers.go, pkg/systemConfig/systemconfig.go, pkg/utils/stringutils.go, selenium-tests/package-lock.json, static/css/query-builder.css, static/dashboard.html, static/js/common.js, static/js/log-results-grid.js, static/js/search.js, static/js/settings.js
- **Process Uptime in Settings**: Now, you can easily check the uptime of the SigLens application since its installation right from the Settings screen. This allows for better monitoring and management of the app’s performance.
- **Fields Command Improvement**: The fields command functionality has been expanded to support additional use cases, allowing for more flexible data querying and manipulation. Note that using fields command following a groupby clause is planned for future updates.
- **User Interface Enhancements for Sorting Queries**: Improvements have been made to the sorting query interface, ensuring tables are rendered more effectively and user preferences are maintained across sessions.
- **Dropdown Visibility**: Adjustments have been made to the width of dynamically created …
=> Release - 0.1.30

.github/ISSUE_TEMPLATE/documentation.md
=> Add issue template for documentation

static/js/common.js, static/js/test-data.js, static/test-data.html
=> Ingestion tab fix

static/css/siglens.css
=> Issue:#546 - not able to copy column name from the column header

static/css/siglens.css, static/live-tail.html
Added css in siglens.css
Fixes ##556 Fix CSS Style: Available Fields on Live Tail Screen
=> Available Fields fixed

pkg/segment/structs/segstructs_test.go, pkg/segment/structs/segstructs_tests.go
Added Unit Tests for: [STORY] Add unit tests for HasTransactionArguments #530
Issue #530 - https://github.com/siglens/siglens/issues/530
I have run `make test` and `make pr` commands locally. Saw successful results.
=> Added Unit Tests for: [STORY] Add unit tests for HasTransactionArguments #530

static/index.html
Fixed the tool tips for buttons in index.html.
Fixes #550 https://github.com/siglens/siglens/issues/550
=> tool tip fixed

static/css/siglens.css, static/js/log-results-grid.js
Added visual indication for loading records, so that users will have feedback when new records are being retrieved.
=> Add Loading Indicator for Scrolling on Logs Screen

static/js/dependency-graph.js
Temporarily fetch depedency graphs for the last 3h
- Tested this on UI 
=> Fetch Depedency graphs for the last 3h

pkg/config/version.go
=> Release 0.1.32

pkg/config/version.go
=> Update version to 0.1.33d

static/css/query-builder.css, static/css/siglens.css, static/css/tracing.css, static/js/search-traces.js, static/js/service-health-overview.js, static/js/service-health.js, static/js/trace.js, static/service-health-overview.html, static/service-health.html
1. Allow right click on Trace and have the option to open it in a new window.
2. The timepicker on all service health tracing screen should use time value drop down list same as what is in the logs screen time picker
3. Timepicker on service health is not carried on.
4. When a traceID is searched, give 1-year lookback
5. The search result of search traces should persist After clicking on a Trace.
=> Tracing Fix

pkg/segment/aggregations/segaggs_test.go
Fixes #561 
Add new ut test for function `performArithmeticOperation`.
=> test: add ut for performArithmeticOperation

pkg/config/version.go
Update version number in version.go for release 0.1.33.
=> Release 0.1.33

pkg/config/version.go
=> Update version to 0.1.34d

pkg/segment/structs/segstructs_test.go
=> test: add ut for HasQueryAggergatorBlockInChain

pkg/segment/structs/segstructs_test.go
=> test: add ut for HasGroupByOrMeasureAggsInChain

pkg/segment/structs/segstructs_test.go
=> test: add ut for HasGroupByOrMeasureAggsInBlock

pkg/es/reader/resolveIndexHandler.go
=> remove metrics index from index dropdown

pkg/config/version.go
- Added the ability for users to click on spans in the Gantt chart to view related details.
- Improved the appearance and usability of the dependency graph for better user experience.
=> Release 0.1.34

pkg/config/version.go
=> Update version to 0.1.35d

static/alert-details.html, static/alert.html, static/all-alerts.html, static/application-version.html, static/cluster-stats.html, static/contacts.html, static/dashboard.html, static/dashboards-home.html, static/dependency-graph.html, static/feedback.html, static/index.html, static/js/search-traces.js, static/js/service-health-overview.js, static/live-tail.html, static/metrics.html, static/minion-searches.html, static/org-settings.html, static/saved-queries.html, static/search-traces.html, static/service-health-overview.html, static/service-health.html, static/test-data.html, static/trace.html
1. Removed `milliseconds` from the service-health overview graphs.
2. Updated the Lookback time from "Last 3 hrs " to "Last 1 hr " on search-traces screen.
3. Updated the copyright notice on all the HTML page to - 2024
=> Tracing Fix 

static/css/siglens.css
Role Dropdown Related CSS Changes
=> CSS Changes

pkg/ssa/ssa.go
Add install age for fresh install and upgrade
=> Add Install Age for fresh install and upgrade

pkg/config/version.go
=> Update version to 0.1.35

pkg/config/version.go
=> Update version to 0.1.36d

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/notificationHandler.go, pkg/alerts/alertsqlite/alerts_sqlite.go, pkg/alerts/alertutils/alertutils.go, static/js/contacts.js
Alert webhook save and retrieve was throwing error. 
Fixes #677 
=> Webhook fix

pkg/config/version.go
Updated the SigLens version to `0.2.1`.
=> Update version to 0.2.1

pkg/config/version.go
- Update SigLens version to **0.2.2d**
=> Updated version to 0.2.2d

pkg/blob/blobStorage.go
Do the normal flow after calling `hook()`, as the hook is just extra things.
=> Do local setup after running hooks

pkg/config/config.go, pkg/config/config_test.go, pkg/retention/retention.go
=> Miscellaneous changes

pkg/health/clusterStatsHandler.go
cluster stats was showing red-traces and other traces related indexes which are not relevant to cluster stats. Code added to Hide those.
=> hide internal traces index

pkg/segment/utils/segconsts.go
The `regexp.Regexp` type has no public fields, so the default gob encoder can't handle it. This makes a custom gob encoder to handle it. This implements the `GobEncoder` and `GobDecoder` interfaces; see https://pkg.go.dev/encoding/gob#GobDecoder
=> Regex gob encoding

pkg/segment/results/blockresults/blockresult.go
The `key` here is a string, but it's not really meant to be a string. Really it's meant to be a `[]byte`, but we use it as a string so that it can be a key in a map. This causes problems during the encoding and decoding process for values in the `[]byte` that fall outside the normal ASCII range. This change fixes the issue by doing a base64 encoding of the `key` so that all characters are ASCII characters, and then we can use normal JSON encoding for that string. Without this, the reconstructed value differed from the original value that was encoded.
=> Fix json encoding

pkg/segment/query/segquery.go, tools/sigclient/pkg/ingest/ingest.go
1. Fixes an issue counting segments; previously, the UI sometimes showed the search was more than 100% complete when it was still not done
2. Makes the emitted `eventsPerSecond` from sigclient more exact
=> Minor fixups

static/css/tracing.css, static/js/trace.js, static/trace.html
Adding placeholder for logs and metrics table on the traces. 
=> Added logs/metrics container to Traces Screen

pkg/config/version.go
=> Bump siglens version to 0.2.2

cmd/startup/startup.go, go.mod, go.sum, pkg/blob/blobStorage.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/version.go, pkg/health/clusterStatsHandler.go, pkg/hooks/hooks.go, pkg/retention/retention.go, pkg/segment/query/segquery.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/metrics/metricssegment.go, pkg/server/ingest/server.go, pkg/server/query/server.go, pkg/server/utils/utils.go, playground.yaml, server.yaml, static/css/metrics-explorer.css, static/css/tracing.css, static/js/index.js, static/js/log-search.js, static/js/metrics-explorer.js, static/js/trace.js, static/metrics-explorer.html, static/trace.html, tools/sigclient/pkg/ingest/ingest.go
- Gob Encoding: We've added custom gob encoding for regex fields. This new feature improves data handling and boosts overall performance.
- Key Encoding: Fixed an issue with key encoding that was causing problems for non-ASCII characters. We've implemented base64 encoding for keys, ensuring accurate data handling and consistency between original and reconstructed values.
- Minor bug fixes and code changes.
=> Release 0.2.2

pkg/config/version.go
=> Bump version to 0.2.3d

pkg/segment/tracing/handler/tracehandler.go, pkg/segment/tracing/structs/tracestruct.go
Send span status to frontend.
Fixes #789 
- Verified the API response to check for status.
=> Send span status to frontend

pkg/segment/structs/segstructs_test.go
add HasDedupBlockInChain unit test
Fixes #529  
=> #529: add HasDedupBlockInChain unit test

pkg/retention/retention.go, pkg/segment/segexecution_test.go, pkg/segment/writer/segstore.go, pkg/segment/writer/unrotatedquery_test.go, pkg/virtualtable/virtualtable.go
- Delete indices without any segments as part of retention.
- Change retention to first run after 1hr
=> Retention based changes

static/css/metrics-explorer.css, static/js/metrics-explorer.js, static/metrics-explorer.html
=> Metrics Explorer - Timepicker , Theme and Formula Validation

pkg/es/writer/esBulkHandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
Delete `test` index using curl command
curl -X "DELETE" http://localhost:5122/elastic/test
=> added api support for delete index

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, pkg/server/utils/utils.go
API endpoints for metrics explorer. 
Parsing of the request params is done and calling the functionality and response serialization is pending.
TODO: Integrate the functionality to fetch metric names and tags into the API. 
- Tested it using postman. 
=> API endpoints for metrics explorer

pkg/segment/reader/metrics/series/seriesreader.go, pkg/segment/reader/metrics/series/seriesreader_test.go, pkg/segment/writer/metrics/metricssegment.go
- Read Metric Names per Segment.
- Tested by writing an unit test case that Flushes the Metrics Map to a file and then reads from the file.
=> feat: Read Metric Names per segment

.circleci/config.yml
=> remove sigclient repo clone step

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metadata/tsmeta.go, pkg/segment/query/metricsquery.go, pkg/segment/query/metricsquery_test.go, pkg/segment/reader/metrics/series/seriesreader.go, pkg/segment/search/metricssearch.go
- Get All Metric Names Query.
- Tested by writing a unit test that tests the function that the handler calls.
- Tested by call the API endpoint.
=> Feat: Get All Metric Names Query

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler_test.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
=> Metric timeseries API

static/js/index.js
=> Revert "fix: by default 2 option will be selected in search index dropdown"

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metricsquery.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/structs/metricsstructs.go
- Get All Tag Keys and values Set for the given Metric Name over the time range.
- Tested the code by calling the API Endpoint through Postman.
=> feat: Metrics Get All Tags API 

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metricsquery.go, pkg/segment/writer/metrics/metricssegment.go
- Get Metric Names for Unrotated Segments.
- Tested by ingesting the metrics and executing the API endpoint.
=> feat: Get Metric Names for Unrotated Segments

pkg/segment/results/mresults/metricresults.go, static/css/metrics-explorer.css, static/js/metrics-explorer.js
=> Metrics Explorer ( API implementations )

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
Add Metric functions API with dummy response 
API Endpoint -  GET `localhost:5122/metrics-explorer/api/v1/functions`
=> Metric functions API

pkg/config/version.go
=> Bump version to release 0.2.3

pkg/config/version.go
=> Bump version to 0.2.4d

benchmark_test.go, pkg/es/writer/esBulkHandler.go, pkg/hooks/hooks.go, pkg/server/ingest/entryHandlers.go, pkg/server/query/entryHandlers.go
=> Add ingest hooks

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/utils/httpserverutils.go
Modify response structure for metrics time series API
=> Modify response structure for metrics time series API

pkg/es/writer/esBulkHandler.go, pkg/grpc/grpc.go, pkg/hooks/hooks.go, pkg/segment/query/segquery.go
=> Update some hooks

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/metricsresults_test.go
=> Add interval function

pkg/segment/query/metadatafilter_test.go, pkg/segment/query/querystatus.go, pkg/segment/query/segquery.go, pkg/segment/query/segqueryhelpers.go
=> Refactor segquery

pkg/config/version.go
=> release 0.2.4

pkg/config/version.go
=> bump version

cmd/startup/startup.go, static/all-slos.html, static/js/all-slos.js
=> Added message for ent features-slo page

pkg/integrations/prometheus/promql/metricsSearchHandler.go
Set a default true value for mquery.SelectAllSeries
=> Fix: Set a default true value for mquery.SelectAllSeries

static/css/dashboard.css, static/dashboard.html, static/js/dashboard.js, static/js/edit-panel-screen.js
=> Dashboards: CSS Update for Adding and Editing

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler_test.go, pkg/integrations/prometheus/promql/metricsconsts.go, pkg/segment/structs/metricsstructs.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
=> Promql query APIs

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metadata/tsmeta.go, pkg/segment/writer/metrics/metricssegment.go
=> Get all labels functionality

tools/sigclient/pkg/ingest/ingest.go
In case of error, retry ingestion code for 2hrs before exiting.
=> In case of error, retry ingestion code for 2hrs before exiting.

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metricsquery.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/structs/metricsstructs.go
Add functionality to fetch promql label values
- Tested API using postman 
=> Add functionality to fetch promql label values

static/js/common.js, static/js/dashboard.js
use websocket for search on dashboard
screen shot
=> use websocket for search on dashboard

static/js/ag-grid-seg-stats.js, static/js/common.js, static/js/dashboard-logs-results-grid.js, static/js/search.js
=> Use columnsOrder/allColumns field from backend to order columns

pkg/ast/pipesearch/searchHandler.go
=> Fix segstats query

static/js/ag-grid-seg-stats.js, static/js/dashboard-logs-results-grid.js, static/js/search.js
=> Revert "fix issue with colOrder on logs page"

static/js/ag-grid-seg-stats.js, static/js/common.js, static/js/dashboard-logs-results-grid.js, static/js/search.js
=> Revert "Use columnsOrder/allColumns field from backend to order columns"

pkg/config/version.go
=> Bump release version to 0.2.5

pkg/config/version.go
=> Bump version to 0.2.6d

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsconsts.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/utils/segconsts.go
Add sqrt, exp, sgn, deg, rad funcs
Add unit tests and test in the UI
=> Feat: Add promql funcs (sqrt, exp, sgn, deg, rad)

pkg/config/version.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go
Get series by label matchers
- Tested using postman 
=> Get series by label matchers promql

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metricsquery.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/tsid/tsidtracker.go
Store tag keys and values separately for tagsOnlySearch
- Tested both the APIs using the newly stored maps.
=> Store tag keys and values separately for tagsOnlySearch

pkg/integrations/prometheus/promql/metricsSearchHandler.go
Set default start and end epoch for promql APIs
=> Set default start and end epoch for promql

static/js/metrics-explorer.js
Fix: Populate Correct Tag Value for Selected Metrics Name on Metrics Explorer Screen
Fixes #888 
=> Fix: Populate Correct Tag Value for Selected Metrics Name on Metrics Explorer Screen

CONTRIBUTING.md
Update docs with PEG file instructions
=> Update docs with PEG file instructions

.circleci/config.yml, cicd/metrics_test.csv, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/ingest/ingest.go, tools/sigclient/pkg/query/otsdbquery.go, tools/sigclient/pkg/query/query.go, tools/sigclient/pkg/utils/calculation.go, tools/sigclient/pkg/utils/metricsreader.go
Add Metrics E2E test
- Allow using benchmark generator type when ingesting metrics data
- Allow specifing test set file for the e2e test
> Please notice that: The test set data is incomplete. I will complete the remaining test set data, if there is nothing else to modify in the pr
=> Test: Add Metrics E2E test

cicd/ingest.csv, cicd/restart.csv
Resolve the issues that sometimes cause the CI/CD tests to fail when querying for the 404 status.
=> Fix: Replace status 404 with 200 in cicd test sets

pkg/config/version.go
=> Release 0.2.7

pkg/config/version.go
=> Bump version to 0.2.8d

cicd/metrics_test.csv
=> Feat: Complete metrics test sets

.circleci/config.yml, cicd/restart.csv
Reduce ingestion indices count, expedite the ingestion process
=> Fix: Modify ingestion indices count

pkg/influx/query/query.go, pkg/segment/writer/metrics/metricssegment.go
- FIxes the Influx Ingestion Metric Name format.
- Fixed the `show databases` query response.
- Tested by ingesting through TSBS and running queries through TSBS.
=> Fix: Influx Metric Name format.

pkg/segment/reader/record/rrcreader.go
=> Fix: ColumnsOrder Issue

pkg/integrations/prometheus/promql/metricsSearchHandler.go
Return resultType matrix for range queries
- Tested the displaying of graph on grafana UI for range queries
=> Return resultType matrix for range queries

.circleci/config.yml, tools/sigclient/README.md, tools/sigclient/pkg/ingest/ingest.go
Update OTSDB metric ingestion url on sigclient
- tested ingestion URL to make sure the the ingestion works correctly.
=> Update OTSDB metric ingestion url on sigclient

static/js/log-results-grid.js
1. The single line and wrap line views now display correctly. 
2. The results columns now align properly with the columnsOrder. (The columnsOrder remains maintained in all types of table view)
3. Include previous columns when loading more results - when scrolling for additional logs on the UI and the next batch arrived with different columns compared to the previous records, all columns were combined, resulting in blank values for columns that didn't exist for certain records. 
=> Fix: Single line & wrap line view

static/js/log-results-grid.js, static/js/search.js
I'm not very familiar with JS. Please review carefully.
1. Fixed an issue with concurrent `doSearch()` calls using the same timer names
2. Made `doSearch()` return a Promise, since it was already being called as if it returned one
Before, doing a `*` search and scrolling down a few times, the JS logs would look like
Now they look like
=> Fix frontend console errors

pkg/es/writer/esBulkHandler.go, pkg/server/query/server.go, static/cluster-stats.html, static/js/cluster-stats.js, static/js/common.js
=> added delete index functionality on clusterstats page

cicd/metrics_test.csv, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsconsts.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/utils/segconsts.go
Add promql funcs predict_linear(): https://prometheus.io/docs/prometheus/latest/querying/functions/#predict_linear
=> Feat: Add promql funcs predict_linear()

pkg/health/clusterStatsHandler.go, pkg/ssa/ssa.go
=> Add metrics and traces count

cicd/metrics_test.csv
=> Fix metrics test

pkg/alerts/alertsHandler/alertsHandler.go, pkg/integrations/loki/loki.go, pkg/integrations/splunk/splunk.go, pkg/sampledataset/sampledataset.go, pkg/server/utils/utils.go, pkg/utils/httpserverutils.go, pkg/utils/httpserverutils_test.go
Remove some duplicate for error handling when processing an http request
Manually ensured I got to an error state, and checked the log file to make sure the log message looked correct
=> Refactor http errors

pkg/segment/pqmr/pqmatchresults.go, pkg/segment/query/metadata/segmentmicroindex.go, pkg/segment/reader/microreader/microreader.go, pkg/segment/reader/segread/agiletreereader.go, pkg/segment/reader/segread/rollupreader.go, pkg/segment/reader/segread/segreader.go, pkg/segment/reader/segread/timereader.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/agiletreewriter.go, pkg/segment/writer/packer.go, pkg/utils/sliceutils.go, pkg/utils/sliceutils_test.go
Refactor code to make it more concise, easier to understand, and less error prone
Unit tests pass
=> Refactor resizing a slice

static/js/available-fields.js, static/js/event-handlers.js
Selected available fields remain persistent when performing new searchesSummarize the change.
selected available fields remain persistent when performing new searches
=> Fix: Persist selected available fields across new searches

pkg/config/version.go
=> bump release 0.2.8

pkg/segment/reader/record/rrcreader.go
Updates to `nodeResMap` can only be done while holding `mapMutex`
Unit tests pass
=> Fix unsafe map deletion

cmd/startup/startup.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/common/dtypeutils/dtypeutils.go, pkg/common/fileutils/logfileutils.go, pkg/common/fileutils/logfileutils_test.go
Move log files to logs dir and also log query ID
Tested complete flow of query.log and access.log
=> Move log files to logs dir and also log query ID

pkg/segment/writer/metrics/metricssegment.go
Assign metric_name for target_info metrics
- Tested by checking that the target_info metric is processed like other metrics and no error on the log for any metric being processed.
=> Assign metric_name for target_info metrics

pkg/health/clusterStatsHandler.go, pkg/usageStats/stats.go, static/cluster-stats.html, static/js/cluster-stats.js
Update cluster stats page graphs and update usagestats.csv format to store logsBytes and metricsBytes
- Tested graph values by ingesting over time
- No errors or warnings on browser console
=> Update cluster stats page graphs

static/js/dashboard.js
Fix - Double Query Issue on Dashboard Refresh
Fixes #975 
=> Fix - Double Query Issue on Dashboard Refresh

defaultDBs/details/10329b95-47a8-48df-8b1d-0a0a01ec6c42.json, defaultDBs/details/a28f485c-4747-4024-bb6b-d230f101f852.json, defaultDBs/details/bd74f11e-26c8-4827-bf65-c0b464e1f2a4.json, static/css/query-builder.css, static/dashboard.html, static/js/common.js, static/js/dashboard-charts.js, static/js/dashboard.js, static/js/edit-panel-screen.js
1. Updated the dashboard metrics endpoint to the new endpoint.
2. Updated the default dashboards JSON to include the new response format"
=> Dashboard Metrics Panel with New Endpoints

pkg/health/clusterStatsHandler.go, static/cluster-stats.html, static/css/siglens.css, static/js/cluster-stats.js
Cluster stats Bar Graph UI changes API changes for storage saved calculation
- No errors on console.
TODO in next PR: CSS changes for bar graph alignment.
=> Cluster stats Bar Graph changes

pkg/config/version.go
=> Release 0.2.9

pkg/config/version.go
=> Bump version to 0.2.10d

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/metricsbench/metrics_bench.go
=> add query iteration loop for sigclient metricsbench and some debug logs

pkg/config/version.go
=> Bump version to 0.2.10

pkg/config/version.go
=> Bump version to 0.2.11d

tools/sigclient/pkg/ingest/ingest.go
=> SigClient: fix retryCount and some better logging

pkg/config/version.go
=> Bump version to 0.2.11

cicd/promql_test.csv, pkg/config/version.go, pkg/integrations/otsdb/query/expqueryparser.go, pkg/integrations/otsdb/query/queryparser.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/parser.go, pkg/integrations/prometheus/promql/parser_test.go, pkg/segment/query/metadata/tsmeta.go, pkg/segment/reader/metrics/series/seriesreader.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/tests/metricsresults_test.go, pkg/segment/structs/metricsstructs.go, pkg/segment/writer/metrics/metricssegment.go, tools/sigclient/pkg/ingest/ingest.go
=> Release 0.2.11

pkg/config/version.go
=> bump version to 0.2.12d

pkg/memorypool/memorypool.go, pkg/memorypool/memorypool_test.go, pkg/segment/reader/metrics/series/seriesreader.go
Moves the memory pool from https://github.com/siglens/siglens/pull/1008 to its own module and adds unit testing.
Unit tests pass, and the manual testing from https://github.com/siglens/siglens/pull/1008 runs as expected
=> Refactor memory pool

pkg/segment/reader/metrics/series/seriesreader.go
Cleans up some duplicate code
The test from #1008 still works as expected
=> Remove duplicate code in seriesreader

pkg/segment/results/mresults/tests/metricsresults_test.go
Have added unit test for following operations in metricresult_test
- Addition
- Subtraction
- Division
- Multiplication.
Fixes  #1005 (link all the GitHub issues this addresses)
Run
```go test metricsresults_test.go   ```
=> Test: Added unit test for Arithmetic operations in metricresults_test.go

go.mod, pkg/integrations/otsdb/metricsquery_test.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/parser.go, pkg/integrations/prometheus/promql/parser_test.go, pkg/segment/query/metricsquery.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/metricresults_test.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/segexecution.go, pkg/segment/structs/metricsstructs.go, tools/sigclient/pkg/query/otsdbquery.go
- Implemented `ApplyAggregationToResults` function that executes the chained aggregations.
- Updated the parser to use group by fields with respect to the given aggregation.
-  Tested by writing test for `ApplyAggregationToResults` function.
- Tested by updating the current parser tests and also writing new tests.
- Tested by executing some test queries.
=> feat: Metrics Nested Aggregation

pkg/dashboards/dashboard_test.go, pkg/dashboards/dashboards.go
- Parses the update Dashboard request API.
- Tested by writing unit test cases.
=> feat: new parse request function for update dashboard API

pkg/blob/local/localstorage.go, pkg/config/config.go, pkg/virtualtable/virtualtable.go
Check if file is empty before trying to unmarshal and update logs. Walked through methods called during startup and checked cases where json unmarshal could fail due to empty files, either updated the logs for better debugging or skipped unmarshal step for those files.
- Tested startup with pre-existing data dir 
- Tested startup as a fresh install.
=> Check if file is empty before trying to unmarshal and update logs

pkg/health/clusterStatsHandler.go, pkg/usageStats/stats.go, pkg/utils/httpserverutils.go
Refactor Cluster stats code.
- Tested using usage stats from playground
=> Refactor Cluster stats code

pkg/config/version.go
=> Bump version to 0.2.12

cicd/metrics_test.csv, go.mod, pkg/blob/local/localstorage.go, pkg/config/config.go, pkg/config/version.go, pkg/dashboards/dashboard_test.go, pkg/dashboards/dashboards.go, pkg/health/clusterStatsHandler.go, pkg/integrations/otsdb/metricsquery_test.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/parser.go, pkg/integrations/prometheus/promql/parser_test.go, pkg/memorypool/memorypool.go, pkg/memorypool/memorypool_test.go, pkg/segment/query/metricsquery.go, pkg/segment/reader/metrics/series/seriesreader.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/metricresults_test.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/tests/metricsresults_test.go, pkg/segment/segexecution.go, pkg/segment/structs/metricsstructs.go, pkg/usageStats/stats.go, pkg/utils/httpserverutils.go, pkg/virtualtable/virtualtable.go, static/js/event-handlers.js, static/js/log-results-grid.js, tools/sigclient/pkg/query/otsdbquery.go
- Resolved a bug that was causing the SigLens server to fail during startup due to an unexpected JSON error. The server now starts up smoothly without any issues.
- Introduced a new feature that enables the use of boolean modifiers with comparison operators in PromQL queries.
- Corrected an issue with the `SELECT 1` SQL query that was returning inaccurate results. The query now executes correctly and returns accurate results.
- Enhanced performance by refactoring the memory pool code.
=> Release 0.2.12

pkg/config/version.go
=> Bump version to 0.2.13d

pkg/dashboards/dashboards.go
=> dashboards backend code cleanup

static/js/metrics-explorer.js
Fix for error while retrieving functions og metrics explorer page.
=> Fix: Error in Retrieving Metrics All Functions

pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/metrics/tagsholder.go, pkg/segment/writer/metrics/tagstree.go
More informative error logging
=> Cleanup error handling

pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/segsearchstructs.go, pkg/segment/structs/segstructs.go
pkg/segment/structs/evaluationstructs.go
pkg/segment/structs/segsearchstructs.go
pkg/segment/structs/segstructs.go
=> cleanup part 2

pkg/integrations/prometheus/utils/operatorutils.go, pkg/utils/bitutils.go, pkg/utils/dateutils.go, pkg/utils/httpserverutils.go, pkg/utils/stringutils.go, pkg/utils/timeutils.go
=> Clean up log lines for files under pkg/utils package

pkg/config/config.go, pkg/config/derivedConfig.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/structs/metricsstructs.go, pkg/segment/structs/querystructs.go, tools/sigclient/cmd/utils/converter.go
pkg/config/config.go
pkg/config/derivedConfig.go
pkg/segment/structs/metricsstructs.go
pkg/segment/structs/querystructs.go 
pkg/segment/structs/querystructs.go 
tools/sigclient/cmd/utils/converter.go
=> log cleanup part 3

pkg/config/version.go
=> Bump version to 0.2.13

pkg/config/version.go
=> Bump version to 0.2.14d

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go
=> default to splunk QL when query lanugage is not passed

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/reader/segread/timereader.go
pkg/ast/pipesearch/searchHandler.go
pkg/ast/pipesearch/searchQueryParser.go
pkg/ast/pipesearch/wsSearchHandler.go
pkg/segment/reader/segread/timereader.go
=> log cleanup part 5

pkg/config/version.go
=> Bump version to 0.2.14

pkg/alerts/alertsqlite/alerts_sqlite.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/sql/astsql.go, pkg/common/fileutils/fileutils.go, pkg/common/fileutils/logfileutils.go, pkg/config/version.go, pkg/segment/reader/segread/dechecker.go, pkg/segment/reader/segread/timereader.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/sortblockresult.go, tools/sigclient/pkg/metricsbench/metrics_bench.go
- Updated the default query language type to `Splunk QL` if no query language is passed to the query APIs.
=> Release 0.2.14

pkg/config/version.go
Bump version to release 0.2.15d
=> Bump version to release 0.2.15d

static/css/query-builder.css, static/js/common.js, static/js/event-handlers.js, static/js/log-search.js, static/js/query-builder.js, static/js/search.js
=> Fix: Small Issues on Logs Screen

CONTRIBUTING.md
=> Add a basic glossary

static/css/siglens.css
=> Enable Text Selection in Logs Table

cmd/startup/startup.go, static/alert-details.html, static/alert.html, static/all-alerts.html, static/all-slos.html, static/application-version.html, static/cluster-stats.html, static/contacts.html, static/dashboard.html, static/dashboards-home.html, static/dependency-graph.html, static/feedback.html, static/index.html, static/metrics-explorer.html, static/minion-searches.html, static/org-settings.html, static/saved-queries.html, static/search-traces.html, static/service-health-overview.html, static/service-health.html, static/test-data.html, static/trace.html
Added `CSSVersion` to startup.go so that we can update the version in one place, and it will be reflected in all the HTML files.
=> Added Cache Busting for CSS

pkg/config/version.go
=> Bump version to 0.2.15

pkg/config/version.go
Bump version to release 0.2.16d
=> Bump version to release 0.2.16d

.github/workflows/publish-prod-images.yml, tools/sigclient/Dockerfile
Build sigclient and push to docker hub. 
Tested the same workflow and docker file on my fork and workflow was executed successfully - https://github.com/venkateshamatam/siglens/actions/runs/9483822491
=> Build sigclient and push to docker hub

static/assets/function-icon-dark.svg, static/css/dashboard.css, static/css/metrics-explorer.css, static/css/query-builder.css, static/css/siglens.css, static/js/metrics-explorer.js
=> Dark Mode Metrics Explorer

static/css/dashboard.css, static/css/metrics-explorer.css, static/css/siglens.css, static/js/metrics-explorer.js, static/metrics-explorer.html
Added a refresh icon to the Metrics Explorer, allowing users to easily refresh the metrics data/grpah displayed.
=> Refresh Icon On Metrics Explorer

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/aggregations/segaggs.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/evaluationstructs_test.go, pkg/segment/structs/segstructs.go
https://docs.splunk.com/Documentation/SCS/current/SearchReference/ConditionalFunctions
https://docs.splunk.com/Documentation/SCS/current/SearchReference/ConversionFunctions
```
Comparison and Conditional functions: case, coalesce, searchmatch, validate, nullif
* | stats count BY http_status | eval description=case(http_status = 200, "OK") 
* | stats count BY http_status | eval description=case(http_status = 200, "OK", http_status = 500, "Internal Server Error", http_status = 404, "Not found") 
* | stats count BY http_status | eval description=validate(http_status = 200, "OK") 
* | stats count BY http_status | eval description=validate(http_status = 200, "OK", http_status = 500, "Internal Server Error", http_status = 404, "Not found") 
* | stats count BY city, state | eval …
```
=> Feat: Add Spl eval subcmd parsing logic for Comparison and Conditional/Conversion functions 

pkg/config/version.go
Bump version to release 0.2.17
=> Bump version to release 0.2.17

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/config/version.go, pkg/segment/aggregations/segaggs.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/evaluationstructs_test.go, pkg/segment/structs/segstructs.go
=> Release 0.2.17

pkg/config/version.go
Bump version to release 0.2.18d
=> Bump version to release 0.2.18d

static/css/query-builder.css, static/css/siglens.css, static/index.html, static/js/event-handlers.js, static/js/log-search.js, static/js/query-builder.js, static/js/search.js
On log search page- 
- UI changes to show queryMode under settings
- Allow user to set default mode using settings icon
- Preserve queryMode across multiple query searches
=> Make builder vs code as a setting

static/js/log-results-grid.js, static/js/search.js
=> Fix: Logs JSON Pop-up Not Closing on Outside Click

pkg/config/version.go
Bump version to release 0.2.18
Changes:
Feat: Add regex support for metrics
Add prompt messages for metrics-explorer page
Feat: Add support for SPL commands (random, pi, makemv)
Fix: Issues for queries with formulae having single char name
Add UI changes for queryMode in Logs
Fix: Prevent editing of default dashboards
Feat: Add UI changes to support Metrics Formula
Fix: Show "Select Panel Type" and "Add Panel" popup based on the presence of dashboard in Dashboards
Fix: JSON popups not closing upon outside clicks in Logs
=> Bump version to release 0.2.18

pkg/config/version.go
=> Bump version to 0.2.19d

static/css/siglens.css, static/index.html, static/js/common.js, static/js/dashboard-from-logs.js, static/js/event-handlers.js, static/js/log-results-grid.js, static/js/log-search.js
=> Fix : Query Inconsistency on Scrolling Logs

pkg/hooks/hooks.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/segwriter_test.go
1. Add a rotation hook
2. Add some convenience methods for `SegStore`
=> Add a hook on segment rotation

pkg/alerts/alertsHandler/alertsHandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
Add Test contact point API
- Tested the below cases: 
Correct slack token and channel ID
Correct slack token and wrong channel ID
Wrong slack token and correct channel ID
Missing slack token and missing channel ID when type is `slack`
Missing slack token when type is `slack`
Missing channel ID when type is `slack`
Correct webhook URL and verified the request details come through on webhook endpoint.
Missing webhook URL when type is `webhook`
Incorrect webhook URL when type is `webhook`
Missing type
Invalid/unsupported type.
=> Add Test contact point API

pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/segstructs.go
https://docs.splunk.com/Documentation/SplunkCloud/9.1.2308/SearchReference/Eventcount
- Added testcases for parser.
=> Add Parsing for eventcount index command

pkg/es/writer/esBulkHandler.go
=> Update ES bulk API response

static/alert.html, static/css/metrics-explorer.css, static/css/siglens.css, static/js/alert.js, static/js/metrics-explorer.js
=> UI Support for Creating Metrics Alerts

static/alert.html, static/css/siglens.css, static/js/alert.js, static/js/all-alerts.js, static/js/common.js, static/js/contacts.js, static/js/dashboard.js, static/js/metrics-explorer.js
1. Fix extra queryElement issues. 
2. Change error popups to include X and OK buttons. 
3. Remove default labels.
4. Add alert types to all alert windows.
=> Alerting UI fixes

pkg/hooks/hooks.go, pkg/segment/query/distributedquery.go, pkg/segment/query/segquery.go
Add another hook and clean up some code
=> Add hook during query

pkg/config/version.go
Bump version to release 0.2.19
=> Bump version to release 0.2.19

pkg/config/version.go
=> Bump version to 0.2.20d

pkg/config/version.go
=> Bump version to 0.2.21d

.gitignore, tools/sigclient/README.md, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/alerts/alerts_loadtest.go, tools/sigclient/pkg/alerts/alerts_loadtest_vector.yaml
- The server will try to start the vector to tunnel the logs into SigLens.
- The server also handles the case of errors from vector and closing of the vector server at the end.
- Tested by executing the scale test command with 10 Alerts.
=> feat: Added vector setup and config to tunnel logs to SigLens.

pkg/segment/query/metadatafilter_test.go
Use a temporary directory for testing, that gets automatically cleaned up.
Unit tests pass
=> Fix flaky test

pkg/common/fileutils/fileutils.go, pkg/segment/writer/segwriter.go
1. Adds a function to get segmetas if they're in the segmeta file
2. Adds a util function to process a file line by line
=> Get segmetas from the segmeta file

pkg/hooks/hooks.go, pkg/segment/writer/segstore.go
=> Add a hook after rotation

pkg/config/version.go
=> Bump version to 0.2.21

pkg/config/version.go
=> Bump version to 0.2.22d

static/contacts.html, static/js/alert.js, static/js/contacts.js
fixed delete button logic for contact points , removed redundant code for contact page , revamped the logic for creating new contact points
=> Fixed errors with Contact Point Creating/Updation/Deletion and Ui-fixes for Contact Table

static/css/dashboard.css, static/dashboard.html, static/js/common.js, static/js/dashboard-logs-results-grid.js, static/js/edit-panel-screen.js, static/js/event-handlers.js
Users can select fields, run queries, and save panels for Data Table View.
Available fields selections are saved on a per-panel basis
Fixes #1209 
=> Added Available fields dropdown to Dashboards Panels

pkg/config/version.go
=> Bump Version to 0.2.22

pkg/config/version.go
=> Bump Version to 0.2.23d

static/js/alert.js, static/js/common.js, static/js/log-search.js
=> Fix: Adjust Alert Logs Code Input Box for Long Queries

pkg/utils/maputils_test.go
=> Add util for converting a map to a set

static/js/metrics-explorer.js
- added custom timepicker handlert for metrics explorer
- dynamic x-axis shows the custom time range
=> custom timepicker handlert for metrics explorer

pkg/retention/retention.go, pkg/segment/writer/segwriter.go
This PR's purpose is to add `AddOrReplaceRotatedSegment()`. There's also some refactoring to make adding this function easier
Not yet tested
=> Add function to replace a segmeta entry

defaultDBs/details/10329b95-47a8-48df-8b1d-0a0a01ec6c42.json, defaultDBs/details/a28f485c-4747-4024-bb6b-d230f101f852.json, defaultDBs/details/bd74f11e-26c8-4827-bf65-c0b464e1f2a4.json, static/css/dashboard.css, static/css/metrics-explorer.css, static/dashboard.html, static/js/alert.js, static/js/common.js, static/js/dashboard.js, static/js/edit-panel-screen.js, static/js/event-handlers.js, static/js/metrics-explorer.js, static/metrics-explorer.html
Added metrics query builder to dashboards.
Default dashboards are working; previously created metrics dashboards will not work.
Raw query edit and retrieving is not working.
=> Integrate Metrics Explorer to Dashboard

static/js/alert.js, static/js/metrics-explorer.js
=> Retrieve Query from Metrics Explorer URL for Adding Query Element, Formula and Visualization

static/css/metrics-explorer.css, static/css/siglens.css, static/dashboard.html, static/js/dashboard.js, static/js/edit-panel-screen.js, static/js/index.js, static/js/metrics-explorer.js, static/metrics-explorer.html
Fixes #1238  (link all the GitHub issues this addresses)
=> Fix : Editing a Dashboard query and saving doesn't save the query unless "Run query" button is clicked

pkg/segment/writer/segwriter_test.go
Adds unit tests
New unit tests pass
=> Add unit tests for replacing a segmeta entry

static/css/siglens.css, static/js/navbar.js, static/metrics-ingestion.html, static/traces-ingestion.html
added 2 html files for metrics-ingestions tab and traces-ingestions tab.
=> added 2 html files for metrics-ingestions tab and traces-ingestions tab

static/js/metrics-explorer.js
=> Revert "Added Dynamic -X axis for empty response, Visualization for Constant Values , Fixed Step Size Error When Switching Between Time-Frames"

static/css/dashboard.css, static/dashboard.html, static/js/dashboard.js
Add ability to edit the json on the dashboard settings page
Fixes #1094
=> Added edit-option for dashboard json

static/alert.html, static/css/siglens.css
Made the tooltip design better
=> changed tooltip

pkg/config/version.go
=> Bump Version to 0.2.24

pkg/config/version.go
=> Bump Version to 0.2.25d

static/js/common.js, static/js/metrics-explorer.js
=> [Metrics Explorer] - Merge graph should have different color for each line 

pkg/segment/aggregations/streamstats.go, pkg/segment/structs/segstructs.go, pkg/utils/gobutils.go, pkg/utils/gobutils_test.go
This is similar to https://github.com/siglens/siglens/pull/1289 but for list.List
New unit tests pass
=> Use GobbableList instead of list.List

pkg/segment/structs/segstructs.go, pkg/segment/structs/segstructs_test.go
Defined a function HasInChain that implements checking current QA (with function passed as a parameter) and moves to the next one. 
Reused this function many times. 
Fixes #1321
Add some tests covering corner cases.
- [☑] I have self-reviewed this PR.
- [☑] I have removed all print-debugging and commented-out code that should not be merged.
- [☑] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [☑] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.
=> Deduplicate inchain funcs

pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/structs/segstructs.go
https://docs.splunk.com/Documentation/Splunk/9.2.2/SearchReference/Mvexpand
- Added unit tests for parser
=> Add parser for mvexpand

cicd/ingest.csv, cicd/restart.csv, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/aggregations/generateevents.go, pkg/segment/aggregations/segaggs.go, pkg/segment/query/segquery.go, pkg/segment/reader/record/recordreader.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/segexecution.go, pkg/segment/structs/segstructs.go, pkg/segment/utils/timeconsts.go, pkg/utils/timeutils.go
Gentimes command splunk
Tests in ingest.csv
=> SPL command GenTimes

pkg/hooks/hooks.go, pkg/segment/writer/segstore.go
=> Update rotation hook

pkg/config/version.go
=> Bump version to 0.2.25

static/js/metrics-explorer.js
Setting Constant value for formula was not working as expected for alerts/metrics query builder
=> fix constant value for formula

pkg/config/version.go
=> Bump version to 0.2.26d

pkg/querytracker/querytracker.go, pkg/querytracker/querytracker_test.go
Add tests. Add error messages. Decomposed one function.
Fixes #376 
Tests are in querytracker_test.go
=> Querytracker tests

pkg/querytracker/querytracker_test.go
Tests checking handlers in querytracker.go
Fixes #376 
=> Tests on querytracker handlers

pkg/hooks/hooks.go, pkg/segment/query/segquery.go
Add a bool param to `FilterQsrsHook()` for whether the segment have been rotated.
=> Update hook for filtering QSRs

static/js/event-handlers.js
=> Cancel button on Logs Screen is working now

static/cluster-stats.html, static/css/siglens.css, static/js/cluster-stats.js
1. Added Trace Section to Cluster Stats Page. 
2. Added Separator between the different sections.
3. Formatted the cluster-stats.js file as Prettier.
=> Added Trace Section to Cluster Stats Screen

cicd/ingest.csv, cicd/restart.csv, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/evaluationstructs_test.go
Modulo support for numeric expressions
Added tests in ingest csv as well as evaluationstructs_tests.go
=> Support for Modulo operator in SPL

static/css/siglens.css, static/js/navbar.js, static/metrics-ingestion.html, static/test-data.html, static/traces-ingestion.html
=> Navbar Submenu Fix

pkg/health/clusterStatsHandler.go
=> change query stats table lables

tools/sigclient/README.md, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/ingest/ingest.go
Added eventsPerDay option for controlling the rate of ingestion.
Tested over an interval of 6s for log and metrics data with single and multiple processes. Verified the amount of data ingested and the sleep times.
=> eventsPerDay option for Ingestion

pkg/health/clusterStatsHandler.go, static/css/siglens.css
Fix Typo - "Queries Count.." to "Query Count.."
Adjust the width of the table so that the text comes in a single line.
=> Fix Query Stats Table

pkg/hooks/hooks.go, static/js/settings.js, static/org-settings.html
=> show deployment type under settings tab

static/js/common.js, static/js/dashboard-charts.js
Added support for multiple group by columns and timechart query for bar chart on dashboards
=> Support Multiple Group By Columns for Bar Chart on Dashboards

pkg/hooks/hooks.go, static/css/siglens.css, static/org-settings.html
=> Adding hook to get distributed nodes config

static/css/siglens.css, static/js/common.js, static/js/search.js
Timeout Error (For testing, it shows 10s, but actually it's 300s). 
When the user clicks on the OK button, hide the progress bar and show the error.
Fixes #1381 
=> Fix: Display Query Timeout Error

eslint.config.mjs, static/js/common.js, static/js/event-handlers.js
=> Fix : Logs Screen 

tools/sigclient/pkg/ingest/ingest.go
=> minor log change

static/css/siglens.css, static/js/common.js, static/js/navbar.js, static/js/pqs-settings.js, static/js/settings.js, static/org-settings.html, static/pqs-settings.html
Added a new sub-tab `PQS` to My-Org Screen.
1. Move the PQS Enabled dropdown to the new screen 
2. Added the Clear PQS Info Button - A confirmation popup opens before clearing the info.
3. Added the Delete All PQS Data - API integration is not done yet.
4. Get PQS Queries Table - Get all the PQS Queries Details and display them in table format. 
5. In the above table if the user clicks on any PQS Query ID - a popup opens up with the JSON details.
=> Added PQS Settings Section

static/js/dashboard-charts.js
=> Null column names chart

pkg/hooks/hooks.go
=> added hook for MultinodeSystemInfo

pkg/usageStats/stats.go
Only report error if the file exists and there is an issue opening the file.
=> Fix: Only report usage stats error for existing files

pkg/segment/writer/segstream.go
```
applySearchSingleQuery: failed to apply wildcard expression search! error: qValDte had nil regexp compilation
ESC[31mERROESC[0m[2024-08-09 06:35:52] applySearchSingleQuery: failed to apply wildcard expression search! error: qValDte had nil regexp compilation
ESC[31mERROESC[0m[2024-08-09 06:35:52] applySearchSingleQuery: failed to apply wildcard expression search! error: qValDte had nil regexp compilation
```
=> Remove log flood

pkg/config/version.go
=> Bump version to 0.2.26

pkg/config/version.go
=> Bump version to 0.2.27d

static/css/metrics-explorer.css, static/js/dashboard-from-logs-metrics.js, static/js/metrics-explorer.js, static/metrics-ingestion.html, static/test-data.html, static/traces-ingestion.html
=> fixed panel formatiing for dashboard.js

pkg/segment/reader/segread/agiletreereader.go, pkg/segment/search/searchaggs.go
=> remove noisy logs

pkg/es/query/queryparser.go, pkg/integrations/loki/loki.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/querystatus.go, pkg/segment/results/segresults/segresults.go, pkg/segment/search/conditioncheck.go, pkg/segment/search/segsearch.go, pkg/segment/segexecution.go
=> log refactor for query ID

static/css/query-builder.css, static/css/siglens.css, static/js/alert.js, static/js/common.js, static/pqs-settings.html
1. Entering a pipe character will not automatically create a line break.
2. Add ellipsis(...) indicator for content exceeding 5 lines when collapsed
3. Do not collapse the textarea less than 5 lines are present.
4. Adding heading to PQS Tables.
Fixes #1319 
=> UI Fix: Search Textarea 

pkg/config/version.go
=> Bump version to 0.2.27

pkg/config/version.go
=> Bump Release to 0.2.28d

.github/workflows/uts.yml, pkg/retention/retention.go
=> misc fixes

pkg/config/version.go
=> bump version to 0.2.28 for release

.github/workflows/uts.yml, pkg/config/version.go, pkg/retention/retention.go, pkg/segment/reader/segread/dechecker.go, pkg/segment/reader/segread/segreader.go, pkg/segment/search/conditioncheck.go, pkg/segment/search/filtersearch.go, pkg/segment/writer/rawchecker.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segstream.go
=> release  0.2.28

.github/workflows/uts.yml, pkg/config/version.go, pkg/retention/retention.go, pkg/segment/reader/segread/dechecker.go, pkg/segment/reader/segread/segreader.go, pkg/segment/search/conditioncheck.go, pkg/segment/search/filtersearch.go, pkg/segment/writer/rawchecker.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segstream.go
=> Revert "release  0.2.28"

pkg/config/version.go
=> Release 0.2.28.1

.github/workflows/uts.yml, pkg/config/version.go, pkg/retention/retention.go, pkg/segment/reader/segread/dechecker.go, pkg/segment/reader/segread/segreader.go, pkg/segment/search/conditioncheck.go, pkg/segment/search/filtersearch.go, pkg/segment/writer/rawchecker.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segstream.go
=> release version 0.2.28.1

pkg/config/version.go
=> bump release version number

pkg/config/version.go
=> release version 0.2.29

pkg/config/version.go
=> set version number for next release

static/alert.html, static/js/metrics-explorer.js
=> added code for sending functions along with formula for metrics alert

pkg/cfghandler/pqsupdate.go
Remove this unneccesary log. We are already logging [here](https://github.com/vasukalariya/siglens/blob/ffda38538f8acb2f04454be75153e83ae3d9305f/pkg/config/config.go#L516).
=> Remove unneccesary log line

static/css/query-builder.css, static/js/search.js
=> Added Total-Possible-Events on the Progress Bar

static/js/common.js
=> fixed dashboard function while editing metrics explorer

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/packer.go, pkg/utils/testutils.go
Refactored a lot of duplicate code in the parser.
Corrected parser for functions that are yet to be implemented
Refactored parser tests. Added stats + eval tests for yet to be implemented functions
https://github.com/siglens/siglens/issues/1103
=> SPL: Refactored aggregate functions

static/css/metrics-explorer.css, static/css/siglens.css, static/js/metrics-explorer.js, static/js/saved-query.js, static/metrics-explorer.html
Functions do not apply to expressions that contain numeric values, so we do not allow users to add any functions.  
If a function is already applied and the user changes the expression to numeric, then we get an error. After the error handling PR is merged, we will show the error on the UI.
=> Disable Formula Functions For Numeric Value (Metrics Explorer)

static/js/common.js
=> fixed issue with panel creation from metrics explorer

static/js/alert.js, static/js/common.js, static/js/metrics-explorer.js
=> time picker and referesh fixed for alert and metrics explorer

pkg/segment/writer/segwriter.go
=> Update log line in segwriter

static/js/metrics-explorer.js
=> Fix Metrics Graph and Legends

static/css/dashboard.css, static/js/index.js
=> Handle Null Index to Prevent Errors on Dashboards and Alerts

pkg/segment/aggregations/timechartagg.go, pkg/segment/reader/segread/segstatsreader.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/segstructs.go, pkg/segment/writer/segstore.go, pkg/utils/gobutils.go
- Use GobbableHll for custom encoding
- Renewed method for InitSegStore
=> Fix inconsistencies for GobEncoding for HLL

pkg/segment/writer/segstore.go
Update InitSegStore to call initWipBlock. It is need if we directly use WritePackedRecord.
=> Minor Fix for CICD failure 

static/js/metrics-explorer.js
=> created fix

pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/querystatus.go
=> Cancel query execution when query is cancelled from UI

static/js/pqs-settings.js
=> Fix: PQS Clear Meta Data API call

pkg/config/version.go
=> Bump version to 0.2.30

pkg/config/version.go
Bump version to release 0.2.31d
=> Bump version to release 0.2.31d

.github/workflows/playwright-test.yml, playwright-tests/tests/index.test.js
Created a new directory, `playwright-tests/tests/`, for organizing Playwright test files. Individual test scripts can be added within this directory as test.js files. Added a test file for the index.html page. Also, created a playwright-test.yml GitHub workflow that will run on every PR/push.
- **Improved CI/CD Reliability:** Playwright ensures that failed tests are accurately reported, unlike Selenium, which sometimes allowed CircleCI to show success even when tests failed.
- **Stability and Consistency**: Playwright eliminates issues caused by frequent ChromeDriver updates in Selenium by providing a more stable environment with built-in browser versions.
- **Ease of Use**: Playwright is easier to write and understand, making tests more maintainable and readable.
Will remove the …
=>  Playwright for UI testing

pkg/segment/reader/segread/agiletreereader.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/agiletreewriter.go
- Updates the version of AgileTree.
- All unit test cases passed
=> Update the version of AgileTree

cmd/startup/startup.go, pkg/config/version.go
=> Bump version to 0.2.32

.github/workflows/playwright-test.yml, cicd/ingest.csv, cicd/restart.csv, cmd/startup/startup.go, pkg/config/version.go, pkg/segment/reader/segread/agiletreereader.go, pkg/segment/reader/segread/segstatsreader.go, pkg/segment/reader/segread/segstatsreader_test.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/results/segresults/segresults.go, pkg/segment/search/searchaggs.go, pkg/segment/search/searchaggs_test.go, pkg/segment/tracing/handler/tracehandler.go, pkg/segment/utils/segconsts.go, pkg/segment/utils/segutils.go, pkg/segment/writer/agiletreewriter.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, playwright-tests/tests/index.test.js, static/js/metrics-explorer.js
=> Release 0.2.32

pkg/config/version.go
=> Bump version to 0.2.33d

static/assets/mute-active-icon.svg, static/assets/mute-icon.svg, static/assets/mute-regular-icon.svg, static/css/siglens.css, static/js/all-alerts.js
Added a mute icon to the all-alerts table. Users can select a time range or a custom time.
Outstanding issue: Add an API to unmute the alert.
=> UI : Alert Silencing

cmd/startup/startup.go, docker-compose.yml, install.sh, pkg/alerts/alertsqlite/alerts_sqlite.go
Migrate the siglens DB from working directory to data folder.
After this change start the siglens server noticed the migration of DB from working directory to the data directory.
Checked that there are no error logs specifying Failed to connect to siglens database.
=> Check and Migrate Siglens DB

cmd/startup/startup.go, pkg/config/version.go
=> Release 0.2.33

pkg/config/version.go
=> Release 0.2.34d

static/js/edit-panel-screen.js
=> fixed timepicker for dashboard

tools/sigclient/pkg/ingest/ingest.go
Update log line to show better params.
=> Update Ingest Log Line

tools/sigclient/pkg/ingest/ingest.go
=> Ingest Log Cleanup

cicd/ingest.csv, cicd/restart.csv, pkg/alerts/alertsHandler/alertsHandler.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/pipesearch/searchQuery_test.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/ast/structs.go, pkg/integrations/loki/loki.go
Added a index support for SPL, to override the index for searching.
- Ingest multi index data
- Change the index on the UI and run a index specific query
- Verify the results
Added parser tests and tests in ingest.csv and restart.csv
=> Index support for SPL

cmd/startup/startup.go, pkg/config/version.go
=> Bump Version to 0.2.34

static/js/cluster-stats.js
=> UI: Added Column Count

pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
=> avoid rotating seg on shorter interval during bootup

static/js/log-results-grid.js
=> Ag-grid optimization

static/js/common.js, static/js/metrics-explorer.js, static/js/saved-query.js
=> Fix: Unable to Save Logs Query

pkg/health/clusterStatsHandler.go, pkg/hooks/hooks.go, pkg/usageStats/stats.go
- Adds hook to get cluster Ingest stats from all nodes
=> feat: Add hook for ingest stats

pkg/dashboards/dashboards.go, pkg/hooks/hooks.go, playwright-tests/tests/dashboard.test.js, playwright-tests/tests/dashboards-home.test.js, static/js/dashboard.js
=> Playwright testing : Dashboards 

cmd/startup/startup.go, pkg/config/version.go
=> Initial Bump release to 0.2.36

static/js/cluster-stats.js
=> Fix QueryStats Table

pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/multicolreader.go
Improves the logs from #1640 
Not tested
=> Use more descriptive error logs

cmd/startup/startup.go, pkg/config/version.go
=> Bump initial version to 0.2.37

cmd/startup/startup.go, pkg/config/version.go
=> Bump version to 0.2.38d

cmd/startup/startup.go, pkg/config/version.go
=> Bump initial version to 0.2.38

cmd/startup/startup.go, pkg/config/version.go
=> Bump initial version to 0.2.39d

.github/workflows/uts.yml
=> GH Actions: Set skip-cache to false for faster build times

cmd/startup/startup.go, pkg/config/version.go
Bump initial version to 0.2.39
=> Bump initial version to 0.2.39

cmd/startup/startup.go, pkg/config/version.go
Bump initial version to 0.2.40d
=> Bump version to 0.2.40d

pkg/blob/local/localstorage.go, pkg/segment/reader/segread/segstatsreader.go
Fix a few issues reading files.
=> Fix bugs reading and checking for certain files

pkg/ast/pipesearch/listIndicesHandler.go, pkg/hooks/hooks.go
=> Cleanup Indexes

playwright-tests/tests/settings.test.js, static/cluster-stats.html, static/css/siglens.css, static/js/settings.js, static/org-settings.html, static/pqs-settings.html
=> UI: Settings Page Improvements

cmd/startup/startup.go, pkg/config/version.go
=> bump release version to 0.2.40

pkg/config/config.go, pkg/config/config_test.go
This reverts commit d6c2f9a66262648d2550800537729154679223f8.
=> Revert "Disallow unknown fields in server.yaml (#1682)"

playwright-tests/tests/all-slos.test.js, playwright-tests/tests/dashboard.test.js, playwright-tests/tests/minion-searches.test.js, playwright-tests/tests/saved-queries.test.js
=> Playwright Test : SLOs, Minion Searches & Saved Queries Screen

static/css/dashboard.css, static/css/siglens.css, static/js/common.js, static/js/dashboard-logs-results-grid.js, static/js/dashboard.js, static/js/edit-panel-screen.js
- **Text Selection and Column Resizing Fix:** Resolved the issue on the Dashboard screen where users were unable to select text in the Data Table panel or resize the column width. The panel is now draggable from the header only, preventing unwanted movement when user tries to resize the column width.
- **Table Update on New Searches:** Fixed the problem where the table was not updating with new searches; it was previously appending new data to the existing table. The table now refreshes correctly with new search results.
- **Persistent Column Widths:** Implemented functionality that allows users to change the width of columns, which is saved in the panel JSON. The column ID/name and updated width are saved, ensuring that user-defined column widths remain intact when the dashboard is …
=> Fix: Dashboard Table Functionality and Column Resizing

pkg/config/config.go
=> minor fix-change GetUIDomain to return hostname  or localhost

cmd/startup/startup.go, pkg/config/version.go
=> Bump release version to 0.2.41

cmd/startup/startup.go, pkg/config/version.go
=> Bump version to 0.2.42d

cmd/startup/startup.go, pkg/config/version.go
=> Bump version to 0.2.43d

pkg/es/writer/esBulkHandler.go
Minor fix - send correct argument to ProcessIndexRequest
=> Minor fix 

cmd/startup/startup.go, pkg/config/version.go
=> version 0.2.43  release

cmd/startup/startup.go, pkg/config/version.go
=> bump version to 0.2.44d

pkg/config/config.go, static/js/test-data.js
1. Fix splunk ingest documentation on log Ingestion page
2.  fix GetUIDomain function to return host name when port is not specified in the host url
=> misc fixes 

pkg/segment/query/segquery.go, pkg/segment/query/segquery_test.go
1. Remove a redundant parameter
2. Extract a helper function so we can reuse it for the new query pipeline in a different PR
No functionality should change, except some error log messages
CICD
=> Refactor search functions

pkg/segment/query/segquery.go
This shouldn't change any functionality.
This makes a helper function to remove duplicate code, and cleans up the adjacent code a little. The helper function will also be useful for the new query pipeline.
CICD
=> Move duplicate code into a helper function

playwright-tests/tests/index-2.test.js, static/js/download-logs.js
Resolved an issue where the download functionality for `segstats-query` was not working correctly.
=> Fix: Logs Download Functionality for segstats query

static/js/event-handlers.js
=> Fix Available Fields Select Issue for Data Table Panel in Dashboard

pkg/segment/query/segquery.go
Fixes Known Issue 2 from https://github.com/siglens/siglens/pull/1758
1. Enable the new query pipeline
2. Ingest some data
3. Query the data
I ran this query
```
"searchText": "city=Boston",
"startEpoch": "now-24h",
}' http://localhost:5122/api/search | python3 -m json.tool | less
```
=> Search unrotated data in new query pipeline

pkg/utils/option.go, pkg/utils/option_test.go
=> Add Gob encoding/decoding to Option[T]

pkg/config/config.go, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/processor/fieldscommand.go, pkg/segment/query/processor/fieldscommand_test.go, pkg/segment/reader/record/recordreader.go
- Added support for fields command.
- When multiple columns match a wildcard criteria, we return those cols in sorted order to provide consistent results.
Tested using the following queries
```
app_name=Bracecould | fields first_name, city | fields city, first_name
app_name=Bracecould | fields -a* | fields first_name, city
app_name=Bracecould | fields first_name, city
app_name=Bracecould | fields first_name, city, b*
app_name=Bracecould | fields first_name, a*
app_name=Bracecould | fields first_name, city, batch | fields city, first_name, batch
```
=> Fields command for the new pipeline

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/query/processor/regexcommand.go, pkg/segment/query/processor/regexcommand_test.go, pkg/segment/structs/evaluationstructs.go
- Modified the regex to use Gobbable regex
- Tested by running the regex queries
- unit test cases pass
=> Regex cmd: change to Gobbable regex

pkg/es/writer/esBulkHandler.go, pkg/hooks/hooks.go
=> added extra hook for delete index

cmd/startup/startup.go, pkg/config/version.go
=> Bump release version to 0.2.44

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/queryprocessor_test.go
We need to merge this PR after this [one](https://github.com/siglens/siglens/pull/1810).
=> Remove sortByTimestampDefault option in the response for new pipeline.

tools/sigclient/functionalQueries/stats_group_by_eval.json
Added fields command to remove the non-relevant fields (nowResult and timeResult should not be checked since they are dependent on the current time).
=> Fix test having relative time

tools/sigclient/pkg/query/query.go
Rex was implemented for the new pipeline in #1823 
CICD
=> Enable rex CICD

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, tools/sigclient/functionalQueries/functionalQueries.yml, tools/sigclient/functionalQueries/head.json
- Enabled a functional query and added a parser unit test.
=> Fix parser for fields in eval/boolean expression to include numbers and underscores

pkg/ast/spl/tests/splParser_test.go
Temporarily disabling this test, while we fix it properly. 
=> Disable test failing day after time change

tools/sigclient/README.md, tools/sigclient/pkg/query/query.go
=> Add longer functional test readme

tools/read-pqmr.py
Our .pqmr files are binary. This adds a tool to read them. This is meant just for debugging purposes
Some example output:
```
Total chunks found: 1
No duplicate block numbers found
Chunk Analysis:
Chunk 1:
Block number: 0
Records matched: 3 of 15000
```
=> Add tool to read pqmr file

pkg/segment/query/processor/wherecommand.go
- If a column does not exist and its present in the where clause we will just return empty result.
TODO: When we correct the evaluation to use different data types we can return the backfilled value and evaluate the conditions properly.
Earlier a query like this was crashing, now it should not
`* | where invalidCol="abc"`
=> Fix where crash for a non existent column

pkg/ast/pipesearch/searchHandler.go, pkg/segment/query/metadatafilter_test.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/queryprocessor_test.go, pkg/segment/query/segquery.go, pkg/segment/query/segquery_test.go, pkg/segment/query/segqueryhelpers.go, pkg/segment/segexecution.go
- Added Log Query Summary for new query pipeline.
- All unit tests passed.
- I ran some queries and verified that the response time being updated in `usage_querystats.csv` and also verified that is reflecting in the UI on the my org.
=> Log Query Summary for new query pipeline

pkg/config/version.go
=> Bump Version to 0.2.46d

cicd/ingest.csv, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/processor/tailcommand.go, pkg/segment/query/processor/tailcommand_test.go, pkg/utils/sliceutils.go, pkg/utils/sliceutils_test.go, tools/sigclient/functionalQueries/functionalQueries.yml, tools/sigclient/functionalQueries/sort_tail_eval_newField.json, tools/sigclient/functionalQueries/tail.json, tools/sigclient/functionalQueries/tail_stats.json, tools/sigclient/longerFunctionalQueries/longerFunctionalQueries.yml, tools/sigclient/longerFunctionalQueries/sort_tail_eval_newField.json, tools/sigclient/longerFunctionalQueries/tail.json, tools/sigclient/longerFunctionalQueries/tail_stats.json, tools/sigclient/pkg/query/query.go
- Added tail command for the new query pipeline.
- Added functional and longer functional tests.
- Enabled the ingest.csv tests having tail command.
=> Add tail command in the new query pipeline

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/searcher.go, pkg/segment/query/querystatus.go
- API Search: Fixed error handling for cases with no results by updating the code to return an empty response instead of an error.
- WebSocket/API GroupBy Query: Addressed issue where groupby queries returned error on no results. Updated logic to send an empty response, 
=> Handle No Result Responses for API and GroupBy Queries

pkg/segment/tracing/handler/tracehandler.go
- With the migration to new pipeline we are not creating Aggs struct member of the response. Due to this 0 results were being shown for traces even though traces were present.
- Added code to use default fields of the response.
- We should ensure in future that other parts of the codebase should only use default fields, extra fields present in the response is only meant for the client and not internal code.
- Ingest the data using the [GoApp](https://www.siglens.com/siglens-docs/instrument-traces/go-app)
- Ingested different traces GET, POST.
- Queried the traces and verified that the traces returned are correct.
Before …
=> Trace fix for the new pipeline

pkg/config/version.go
=> Bump Version to 0.2.46

pkg/config/version.go
Bump SigLens Version to 0.2.47d
=> Bump Version to 0.2.47d

pkg/health/clusterStatsHandler.go, pkg/segment/query/querystatus.go, pkg/usageStats/stats.go
=> Add Active Query Count to QueryStats

pkg/segment/query/querystatus.go
=> Update GetActiveQueryCount to Use Read Lock

pkg/segment/query/querystatus.go
=> Update max running queries to 32

pkg/config/version.go
=> Bump Version to 1.0.1

.circleci/config.yml, .github/workflows/check-changed-files.yml, .github/workflows/jsformat.yml, .github/workflows/playwright-test.yml, .github/workflows/uts.yml, pkg/config/version.go, pkg/health/clusterStatsHandler.go, pkg/segment/query/processor/statscommand.go, pkg/segment/query/processor/statscommand_test.go, pkg/segment/query/querystatus.go, pkg/segment/utils/segconsts.go, pkg/usageStats/stats.go
=> Release 1.0.1

pkg/config/version.go
=> Bump Version to 1.0.2d

pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/queryprocessor.go
- Added a method to set streams for a Data Processor
=> set streams for a data processor

pkg/segment/writer/logpacker.go, pkg/segment/writer/segwriter_test.go
- Do not use parsing buffer if there is an escape character.
=> Fix ingestion (col values gets overwritten due to parsing buffer)

pkg/segment/query/segquery.go
- Refactor `PrepareToRunQuery` function.
- All unit tests passed
- Cicd ingest.csv queries passed
=> refactor prepare to run query

pkg/config/version.go
=> bump for 1.0.2

pkg/config/version.go
=> bump to 1.0.3d

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/record.go, pkg/segment/query/processor/statscommand.go, pkg/segment/query/processor/wherecommand.go
Fix log flood if we are continuing even after errors.
Ran a where query that will cause evaluation error and verified that log flood is not present.
=> Fix log flood

pkg/config/version.go
=> bump to release 1.0.3

pkg/config/version.go
=> bump to 1.0.4d

pkg/segment/query/querystatus.go, pkg/segment/query/segquery.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, playwright-tests/tests/cluster-stats.test.js, static/cluster-stats.html, static/css/siglens.css, static/js/cluster-stats.js, static/js/navbar.js, static/js/query-stats.js, static/query-stats.html
- Implemented API functionality to fetch and display active queries and waiting queries.
- Added UI to show two types of queries:
- Active Queries: Currently running queries with their execution duration.
- Waiting Queries: Queries that are pending execution, with the time they have been waiting.
=> Display Active and Waiting Queries with Execution Time

pkg/config/version.go
=> bump version to 1.0.4

pkg/segment/writer/segmetarw.go
Fixed an issue in the readSfm function where column names were incorrectly merged between different indices when traces were ingested.
=> Fix readSfm Function

pkg/segment/writer/suffix/suffix.go, pkg/segment/writer/suffix/suffix_test.go
Refactor code, to make it easier to change in my next PR
Note: it might be easier to review commit-by-commit
Added a unit test. The unit test passes both on the old and new versions of the function.
=> Refactor getting the next suffix

pkg/config/config.go, pkg/config/config_test.go, pkg/hooks/hooks.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/segwriter_test.go, pkg/segment/writer/suffix/suffix.go, pkg/segment/writer/suffix/suffix_test.go
This PR needs to be merged first: https://github.com/siglens/siglens/pull/1944
=> Add hook for getting suffix

pkg/config/version.go
=> Bump Version 1.0.5

.github/workflows/nightly-tests.yml, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/validation.go, tools/sigclient/pkg/utils/calculation.go
- Add support for just ingest/query for functional test.
- Update the workflow to perform rotated test and disable the PQS.
=> Add options for just ingest/query for functional Test

.github/workflows/nightly-tests.yml, tools/sigclient/functionalQueries/simple_sort.json
=> Add step in workflow to print the logs

.github/workflows/nightly-tests.yml
=> Change longer functional back to nightly

.github/workflows/nightly-longer-functional.yml, pkg/ast/spl/tests/splParser_test.go
=> Rename workflow for longer functional

pkg/common/fileutils/fileutils.go, pkg/common/fileutils/fileutils_test.go, pkg/segment/writer/segmetarw.go
=> Misc utils

pkg/health/clusterStatsHandler.go, pkg/hooks/hooks.go, pkg/segment/query/querystatus.go
- Block Processing of query and node stats on Changes
=> Add hook for Blocking the processing of query and node stats on changes

pkg/querytracker/querytracker.go
Determine which columns to make sort indexes for using PQS
=> Determine which columns to make sort indexes for using PQS

pkg/segment/query/processor/searcher.go, pkg/segment/query/querystatus.go, pkg/segment/query/segquery.go
=> Progress Tracking with Sort Index Enabled

pkg/config/version.go
=> Bump version to 1.0.6

pkg/config/version.go
=> Bump version to 1.0.7d

pkg/config/version.go
- Update SigLens version to `1.0.7`
=> Bump Version to 1.0.7

cmd/startup/startup.go, pkg/config/config.go, pkg/config/version.go
- SigLens Release Version: `1.0.7`
=> Release 1.0.7

pkg/config/version.go
=> Bump version to 1.0.8

pkg/config/version.go
=> Bump version to 1.0.9d

pkg/config/version.go
=> Bump version to 1.0.9

pkg/config/version.go
=> Bump version to 1.0.10d

pkg/config/config.go, pkg/segment/memory/limit/memorylimit.go, playground.yaml, server.yaml
- Refactor Info and error log lines
- Updated `server.yaml` and `playground.yaml` with new memory usage percent example value.
=> refac: Info and error log lines

pkg/ingest/ingestionStats.go, pkg/instrumentation/ssgauges.go
Added few additional metrics 
- event count per minute
- event volume per minute
- number of indexes
- total segment count
- total column count
- total CMI size
- total CSG size
- Number of files (per index; key=indexName, value=(e.g., ind-0))
- Number of blocks (per index)
=> Metrics for logs

pkg/hooks/hooks.go, pkg/segment/query/querystatus.go
=> Add waiting queries hook

pkg/hooks/hooks.go, static/index.html
Added functionality to index.html to have another dropdown choice
=> Added Dropdown2 functionality to index.html

pkg/segment/query/distributedquery.go, pkg/segment/query/segquery.go
=> Fix bug causing hanging queries

pkg/alerts/alertsHandler/alertsHandler.go, pkg/hooks/hooks.go, pkg/server/query/entryHandlers.go, pkg/systemConfig/systemconfig.go, static/css/siglens.css
Moved the `ProcessVersionInfo` function to retrieve the SigLens version from the `alertHandler` file to the `systemConfig` file and added a version hook.
=> Add Version Hook

tools/sigclient/README.md
1. Remove leading `$` so it's easier to copy-paste commands
2. Fix a few commands
=> Cleanup sigclient README commands

pkg/otlp/otlp.go, pkg/server/ingest/entryHandlers.go
- Extracts myid from the ingest request and uses it.
- Tested by running trace ingestion with oltp endpoint.
=> call trace ingest with myid extraction

static/css/tracing.css, static/js/trace.js, static/trace.html
=> Fix: Tracing UI 

pkg/ast/pipesearch/searchQueryParser.go, pkg/hooks/hooks.go
=> Add parse hook

.prettierignore, pkg/server/ingest/entryHandlers.go, pkg/server/query/entryHandlers.go, pkg/server/utils/utils.go, pkg/usersavedqueries/usqueries.go
Extract orgid and use it to save queries.
=> Fix: Saved Queries

eslint.config.mjs, pkg/hooks/hooks.go, static/js/navbar.js, static/js/query-stats.js
=> Added few UI hooks

pkg/config/version.go
=> release 1.0.10

.github/workflows/publish-prod-images.yml
=> test gh token

pkg/config/version.go
=> bump version to 1.0.11

.github/workflows/publish-prod-images.yml, pkg/config/version.go
=> release 1.0.11

.github/workflows/publish-prod-images.yml
=> update gh permissions

pkg/config/version.go
=> bump to 1.0.12

pkg/config/version.go
=> bump to 1.0.12 (#2084)

pkg/config/version.go
=> bump to 1.0.13d

cmd/startup/startup.go, pkg/dashboards/dashboards.go, pkg/dashboards/dashboards_test.go, pkg/dashboards/folders.go, pkg/server/query/entryHandlers.go
=> Fix Dashboards

pkg/ast/spl/tests/splParser_test.go, pkg/segment/tracing/handler/tracehandler.go
- Generate Service health and Dependency graph per id
- Tested by running trace ingestion through hot-rod app across multiple ids.
=> generate service health and dependency graph per id

pkg/config/version.go
- Bump SigLens version to `1.0.13`
=> Bump version to 1.0.13

cmd/startup/startup.go, pkg/ast/spl/tests/splParser_test.go, pkg/config/version.go, pkg/dashboards/dashboards.go, pkg/dashboards/dashboards_test.go, pkg/dashboards/folders.go, pkg/segment/tracing/handler/tracehandler.go, pkg/server/query/entryHandlers.go
=> Release 1.0.13

pkg/config/version.go
=> Bump version to 1.0.14d

pkg/alerts/alertsHandler/cronJobHandler.go, pkg/ast/pipesearch/searchHandler.go
We were always using 0 as the ID. Now we use the ID from the alert.
=> Send correct ID when evaluating alerts

pkg/config/version.go
=> bump version to 1.0.14

pkg/config/version.go
=> bump version to 1.0.15d

.github/workflows/publish-prod-images.yml
=> temp disable arm64 docker images

static/component/time-picker/time-picker.js, static/css/tracing.css, static/js/navbar.js, static/js/search-traces.js, static/js/trace.js, static/search-traces.html, static/trace.html
1. Show a loading cursor while searching for traces.
2. Fix the scrollbar on the search traces page.
3. Add expand and collapse functionality for trace spans, including connecting lines between parent and child spans.
4. Resize the chart dynamically based on the available width.
5. Add an adjustable resizer between labels and the chart.
6. Highlight the span and label on hover, and display span details on click.
=> Tracing UI Enhancements

pkg/config/version.go
=> udpdate version to 1.0.15

pkg/config/version.go
=> bump version to 1.0.16d

static/js/query-builder.js, static/js/search-traces.js
=> use backticks for chosen column name to avoid sql parser failure

pkg/config/version.go
=> Updated Version to 1.0.16

pkg/config/version.go, static/js/query-builder.js, static/js/search-traces.js
=> Release 1.0.16

pkg/config/version.go
=> Bump Version to 1.0.17d

.circleci/continue-config.yml, .github/workflows/uts.yml
=> skip gh action for UTs and lint on main

pkg/config/version.go
=> Update version.go to 1.0.17

.github/workflows/jsformat.yml, .github/workflows/playwright-test.yml, .github/workflows/uts.yml
=> try other option for gh skips

pkg/config/version.go
=> Update version.go to 1.0.18

.circleci/continue-config.yml, .github/workflows/jsformat.yml, .github/workflows/playwright-test.yml, .github/workflows/uts.yml, pkg/config/version.go
=> release 1.0.18

.github/workflows/uts.yml
=> skip cache action building of tar for faster build times

pkg/config/version.go
=> Update version.go 1.0.19d

tools/cb_post/benchmark.sh
=> No need to keep the input file once it is split. Free up the space

pkg/server/ingest/entryHandlers.go
- Make the Current Disk Usage function public
=> chore: Make current disk usage function public

pkg/config/version.go
=> Bump version to 1.0.19

static/css/siglens.css
=> Increase font-size for ag-grid

pkg/integrations/prometheus/ingest/putmetrics.go, pkg/integrations/prometheus/ingest/putmetrics_test.go
=> Ignore NaN and +-Inf metric values

pkg/alerts/alertsqlite/alerts_sqlite.go
Metric alert messages that used templating for the query language or text weren't resolving correctly because those values are stored in a different place for log vs metric alerts. This PR fixes that.
Manually made a metric alert like this
with the message
```
{{alert_rule_name}}: "{{query_string}}" ({{queryLanguage}}) {{condition}}
```
And got a message like this when it fired:
```
some metric: "{"queries":[{"name":"a","qlType":"promql","query":"((app_ads_ad_requests_total))","state":"builder"}],"formulas":[{"formula":"a"}]}" (promql) is above 0
```
=> Fix metric alert message templating

pkg/alerts/alertsHandler/notificationHandler.go
Whenever we sent an alert notification to a webhook, we'd send it as `firing`. Now we send `normal` when appropriate.
Manually tested using webhook.site, since I'm not sure what a good way to automatically test this is
=> Send correct alert status for webhook

static/css/query-builder.css, static/css/siglens.css, static/js/event-handlers.js
Screen shots for changes  in light mode:
wrap line view:
single line view:
table view:
Screen shots for changes  in dark  mode:
wrap line view:
single line view:
table view:
=> Changed the font type and color for logs text

pkg/config/version.go, static/css/query-builder.css, static/css/siglens.css, static/index.html
=> Moved the custom query builder elements at top

static/css/siglens.css
Added hover for log line with purple border
=> Added hover for log lines

static/component/dashboard/add-new.js, static/js/saved-query.js
UX enhancements have been implemented to improve the user experience. Now, when users open the modal for creating a dashboard or folder, the first input field— which is mandatory— automatically receives focus, streamlining the workflow. Additionally, pressing the "Esc" key now closes the modal, enhancing keyboard accessibility and ensuring a more seamless interaction.
=> UX Improvement

pkg/segment/reader/microreader/microreader.go, static/js/event-handlers.js, static/js/log-results-grid.js
Added check for if the mbsu file has less than 1 byte so an OOB error wont cause panic. Will return an error, instead. 
=> Out of bounds panic fix

static/css/query-builder.css, static/css/siglens.css, static/index.html, static/js/log-results-grid.js
=> UI : Displaying Logs JSON Data in Split View

static/css/query-builder.css, static/css/siglens.css, static/index.html
https://github.com/user-attachments/assets/a6d4ff6f-1f1a-4a95-ac5b-2a3b11dec112
=> Fix: Logs JSON Popup Scrolling

static/js/common.js, static/js/search-traces.js, static/js/trace.js
- Have both trace_id and start_time from URL.
- Create a 30-minute window centered on the trace start time (±15min)
=> Fix time window for trace view

static/css/tracing.css
=> UI: Improve resizing on panels on gantt chart

pkg/config/version.go, pkg/otlp/logs.go, pkg/otlp/logs_test.go, pkg/otlp/utils.go, pkg/segment/query/metadata/metamocks.go, pkg/segment/query/metadatafilter_test.go, pkg/segment/query/segquery.go, pkg/segment/query/segquery_test.go, pkg/segment/reader/record/rrcreader_test.go, pkg/segment/segexecution_test.go, pkg/segment/segexecutionsort_test.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, static/component/infrastructure/big-number-card-component.js, static/component/infrastructure/container-image-card-component.js, static/css/query-builder.css, static/css/siglens.css, static/css/tracing.css, static/index.html, static/js/common.js, static/js/log-results-grid.js, static/js/search-traces.js, static/js/trace.js
- Various UI improvements
- Handle nested maps in OTEL log ingestion
=> Release 1.0.21

pkg/segment/writer/suffix/suffix.go, pkg/segment/writer/suffix/suffix_test.go
See title. Previously, a panic could happen during the file write which would cause an empty file.
Existing unit tests pass
=> Atomically update suffix files

pkg/segment/reader/microreader/microreader.go
=> Verify BSU content to avoid panic

pkg/config/version.go, pkg/segment/reader/microreader/microreader.go, pkg/segment/writer/suffix/suffix.go, pkg/segment/writer/suffix/suffix_test.go
=> Release 1.0.22

pkg/config/version.go
=> Bump to 1.0.23d

pkg/otlp/logs.go, static/css/siglens.css, static/js/log-results-grid.js
-Added tab buttons to switch between table and json view
-Added copy to clipboard functionality in json overlay
-Added functionality to show the json content in table form
=> Added tab buttons to switch between table and json view

static/js/kubernetes-view.js
=> Updated K8 Events Index Name

pkg/config/config.go, pkg/config/config_test.go, pkg/server/ingest/server.go, pkg/server/query/server.go, playground.yaml, server.yaml
=> listen on both ipv4 and ipv6 addresses

pkg/config/version.go
=> Bump version to 1.0.23

pkg/config/version.go
=> Bump to 1.0.24d

eslint.config.mjs, static/css/dashboard.css, static/dashboard.html, static/js/dashboard-logs-results-grid.js
=> Fix: Dashboard Data Table

pkg/config/version.go
=> Bump to 1.0.25d

pkg/segment/writer/segmetarw.go
When there's thousands of SFM files, this speeds up the startup code significantly (starts in a few seconds instead of a few minutes)
=> Read SFM files in parallel on startup

pkg/config/version.go, pkg/segment/writer/segmetarw.go
=> Release 1.0.25

static/js/event-handlers.js
Fix the issue where switching to wrap/multi-line view displayed all the rows in one page irrespective of the page size.
=> Pagination Fix

eslint.config.mjs, playwright-tests/tests/index-2.test.js, static/css/siglens.css, static/dashboard.html, static/index.html, static/js/available-fields-dashboard.js, static/js/available-fields.js, static/js/common.js, static/js/event-handlers.js, static/js/log-results-grid.js, static/js/query-builder.js, static/js/search.js
- **Revamped Available Fields UI:**
- Moved available fields to the left side.
- Users can now add/remove fields using an add (+) and remove (x) icon.
- Initially, when no field is selected, all columns are displayed.
- On a new search, selected fields persist if the index name is the same, otherwise, they reset.
- **Dashboard Fields Update:**
- Dashboards still use the previous dropdown UI for available fields.
- Moved that code to a separate file: `available-fields-dashboard.js`.
- **Table View Enhancements:**
- Empty columns now display `-` instead of being blank.
- In Single/Wrap Line View, empty columns are completely hidden.
Before marking …
=> Revamped Available Fields UI

static/component/infrastructure/big-number-card-component.js, static/component/infrastructure/container-image-card-component.js, static/component/infrastructure/usage-line-chart-component.js, static/css/siglens.css, static/js/kubernetes-overview.js
=> K8 Overview Panel Explore Button

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go, pkg/utils/dateutils.go
- The PromQL results are not being sent in a sorted order. This PR fixes that.
- Made a temp Fixes for panics that occurred while executing queries through compliance tool.
- Ran the test through compliance tool
=> Promql range query fixes

pkg/segment/results/mresults/metricresults.go
- Sanitize float values, so that `-Inf`, `Inf`, and `NaN` are removed.
=> Sanitize float values

eslint.config.mjs, playwright-tests/tests/metrics-explorer.test.js, playwright-tests/tests/navbar.test.js, static/alert.html, static/css/dashboard.css, static/css/metrics-explorer.css, static/css/siglens.css, static/dashboard.html, static/index.html, static/js/alert.js, static/js/common.js, static/js/dashboard.js, static/js/kubernetes-overview.js, static/js/metrics-explorer.js, static/metrics-explorer.html
1. Fix : adding multiple metric queries to dashboard.
2. Fix : The queries changed when they were added to the dashboard.
3. Fix : Fix bug causing duplicate queries on dashboard.
4. Make the cursor spin when a metrics query is taking a while.
5. Fix: Switching to code (clicking the </> button) only works for the first metric.
6. The delete button is greyed out for queries that are used in a formula. On the Alerts screen, we can only have one formula element, so it gets greyed out, preventing users from adding more formulas. I've improved the UI by adding tooltips for better clarity.
Before marking your pull request as ready for review, complete …
=> UI: Metrics Explorer Fixes

static/css/dashboard.css, static/css/siglens.css, static/js/common.js, static/js/dashboard-logs-results-grid.js, static/js/edit-panel-screen.js
- Fix “Data Table” View - The timestamp column does not show formatted or at the beginning.
- Fix “Log Lines” View - No columns shows up other than timestamp
=> Fix: Dashboard Data Table and Log Lines View

pkg/integrations/prometheus/ingest/putmetrics.go
=> fix prom metrics writing

static/js/metrics-cardinality.js
Turned  Metrics -> total unique series count to a human readable form using commas
=> Added a human readable format for total unique series count

static/css/siglens.css, static/js/common.js
https://github.com/user-attachments/assets/f806192b-ccc3-46b3-b8de-a9d3abd5264c
=> Fix: Updated the Copy Icon In JSON Popup

pkg/usageStats/stats.go
=> fix panic when there are no activeseriescounts

pkg/config/version.go
=> Bump version to 1.0.27

pkg/config/version.go
=> Bump version to 1.0.28d

pkg/usageStats/stats.go
Refactor : - Refactor resultMap handling to use reference instead of reassignment
Updated function to use a reference for the return param `resultMap`
- Removed the pattern of extracting the entry and re-assigning it (`resultMap[bucketInterval] = entry`)
=> Refactor : - Refactor resultMap handling to use reference instead of reassignment

pkg/integrations/loki/loki.go, pkg/otlp/metrics.go
=> fix loki ingestion stats, and fix metric ingestion stats

tools/sigclient/cmd/sigclient.go
This should be reverted after the bug is fixed.
=> Remove count queries from longevity test

pkg/segment/tracing/handler/tracehandler.go, pkg/segment/tracing/handler/tracehandler_test.go
Fix - prevent panic by safely handling dynamic time value types in tracehandler
=> Fix - prevent panic by safely handling dynamic time value types in tracehandler

pkg/segment/query/metricsquery.go, pkg/segment/reader/metrics/tagstree/tagstree_test.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/metrics/tagstree.go
=> add tagtree reading for unrotated

pkg/segment/utils/segconsts.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
=> remove segment rotation on time

pkg/config/version.go
=> Bump to 1.0.28

pkg/config/version.go
=> Bump to 1.0.29d

pkg/retention/retention.go, pkg/segment/metadata/metadata.go
=> switch the order of deletion of things during retention based deletion

pkg/config/version.go, pkg/retention/retention.go, pkg/segment/metadata/metadata.go
=> release 1.0.29

pkg/config/version.go
=> bump to 1.0.30d

pkg/segment/query/queryrefresh.go, pkg/virtualtable/virtualtable.go
- remove uploading of all ingestnode dirs when vtable file changes
- some debug logs changes
=> some debug logs remove ingest dir upload in some cases

pkg/segment/query/querystatus.go
Manually tested by changing the interval to 1 second, and running some queries
=> Log number of active and waiting queries

.github/workflows/jsformat.yml, .github/workflows/playwright-test.yml, .github/workflows/uts.yml, pkg/otlp/logs.go, pkg/otlp/utils.go, pkg/segment/query/queryrefresh.go, pkg/segment/writer/segmetarw.go
=> dont run workflow on main, some debug log lines change

pkg/segment/query/metadatafilter_test.go, pkg/segment/query/summary/querysummary.go
- keep track of querysummary instances
- log with lesser granularity after 5 mins
=> Track query summary threads and log less frequently

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/querystatus.go, pkg/segment/query/segquery.go
=> reduce logging

static/css/siglens.css
=> Changed scrollbar's design for dark theme

pkg/ast/pipesearch/searchHandler.go, pkg/segment/query/segquery.go, pkg/segment/query/segqueryhelpers.go
- dont delete timechart query if it was not started
- reduce some redundant error logs
=> don't delete timechart query if it is not started

pkg/common/fileutils/fileutils.go, pkg/common/fileutils/fileutils_test.go, pkg/segment/query/metadata/metamocks.go, pkg/segment/structs/segmeta.go, pkg/segment/writer/segmetarw.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
1. Cleanup writing an SFM
2. Add a field to SFM
3. Fix a util for reading a directory
=> Restruture writing a SegFullMeta

pkg/segment/writer/segmetarw.go, pkg/segment/writer/segstore.go
=> Add option to skip upload

pkg/segment/query/summary/querysummary.go
=> safety check for parallel close of query summary

pkg/segment/reader/segread/segreader/segreader.go, pkg/segment/reader/segread/timereader.go, pkg/segment/search/filtersearch.go
=> reduce error logging

tools/sigclient/cmd/sigclient.go, tools/sigclient/go.mod, tools/sigclient/go.sum, tools/sigclient/pkg/ingest/ingest.go, tools/sigclient/pkg/query/querymanager.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go, tools/sigclient/pkg/utils/metricsreader.go, tools/sigclient/pkg/utils/reader.go
With the clientperf change about casting, it increased client perf on my local setup from `98K/min` to `142K/min` ingestion with the longevity test
=> Increase sigclient perf and add debug profiler to client

pkg/segment/query/summary/querysummary.go
=> Fix - Closed of closed panic

pkg/config/version.go
=> Bump to 1.0.31

pkg/config/version.go
=> Bump to 1.0.32d

static/js/search-traces.js
=> Fix: Search Traces Duration Filter Fix

static/component/infrastructure/big-number-card-component.js, static/js/kubernetes-overview.js
=> Now the 6 panels use instant queries

static/component/infrastructure/header-component.js
=> UI: Fix Kubernetes Dropdown

static/css/query-builder.css, static/css/siglens.css, static/js/common.js
=> UI: Highlight the row when its JSON popup is open

cmd/startup/startup.go, pkg/hooks/hooks.go
=> Handle SIGUSR1 as a special shutdown signal

static/css/query-builder.css, static/css/siglens.css, static/index.html
=> UI: Pagination placement

pkg/segment/writer/unrotatedquery.go
=> Fix off-by-1 safety check

pkg/segment/reader/microreader/microreader.go
=> Check for bad data when reading block summaries

pkg/config/version.go
=> Bump to 1.0.32

cmd/startup/startup.go, pkg/config/version.go, pkg/hooks/hooks.go, pkg/segment/query/querystatus.go, pkg/segment/reader/microreader/microreader.go, pkg/segment/structs/metricsstructs.go, pkg/segment/structs/segstructs.go, pkg/segment/writer/unrotatedquery.go, static/component/infrastructure/big-number-card-component.js, static/component/infrastructure/header-component.js, static/css/query-builder.css, static/css/siglens.css, static/index.html, static/js/common.js, static/js/event-handlers.js, static/js/kubernetes-overview.js, static/js/search-traces.js, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/querymanager.go
=> Release 1.0.32

pkg/config/version.go
=> Bump to 1.0.33d

static/js/trace.js
=> UI: Loading Indicator for Gantt Chart

static/css/siglens.css, static/js/metrics-cardinality.js, static/metric-cardinality.html
=> UI: Added Loading Indicator for Metrics Cardinality Tables

cmd/startup/startup.go, pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/metrics/wal/wal.go, pkg/segment/writer/metrics/wal/wal_test.go
=> Implemented WAL support for metric names

static/js/saved-query.js, static/js/search.js
=> Fix: Saved Query Retrieval

pkg/segment/reader/segread/timereader.go
=> Fix potential panic from bad data

static/js/usage-stats.js
On hovering over chart points, enlarge the point size for better user interaction.
=> UI: Fix chart point hover effects

pkg/segment/reader/segread/segreader/segreader.go
Add safety checks and clean up the code
=> Prevent nil dereference

pkg/health/clusterStatsHandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, static/js/usage-stats.js
=> Changed name of the clusterIngestStats api to usageStats

pkg/config/version.go
=> Bump to 1.0.34

.github/workflows/playwright-test.yml, .github/workflows/uts.yml, pkg/config/version.go, pkg/health/clusterStatsHandler.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/segmetarw.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, pkg/utils/checksumfile.go, pkg/utils/checksumfile_test.go, static/css/dashboard.css, static/css/siglens.css, static/js/common.js, static/js/dashboard.js, static/js/date-picker.js, static/js/dependency-graph.js, static/js/event-handlers.js, static/js/kubernetes-overview.js, static/js/kubernetes-view.js, static/js/metric-summary.js, static/js/metrics-cardinality.js, static/js/metrics-explorer.js, static/js/service-health-overview.js, static/js/service-health.js, static/js/usage-stats.js, static/metric-cardinality.html, static/usage-stats.html
=> Release 1.0.34

pkg/config/version.go
=> Bump to 1.0.35d

static/alerting.html, static/all-alerts.html, static/apm.html, static/css/siglens.css, static/infrastructure.html, static/metrics.html
Added only the HTML in this PR, will do the redirect from the navbar in another PR.
=> UI: Show cards for Submenus

static/ingestion.html
=> Added ingestion page

pkg/hooks/hooks.go, static/cluster-stats.html, static/index.html, static/js/navbar.js, static/js/settings.js, static/org-settings.html, static/pqs-settings.html, static/query-stats.html
=> UI Changes

pkg/dashboards/dashboards.go, pkg/dashboards/folders.go, pkg/querytracker/querytracker.go, pkg/usersavedqueries/usqueries.go
=> Remove query node dir uploads

benchmark_test.go, pkg/health/clusterStatsHandler.go, pkg/ingest/ingestionStats.go, pkg/segment/metadata/metadata.go, pkg/segment/metadata/segmentmicroindex.go, pkg/segment/query/metadata/metareader_test.go, pkg/segment/query/metadatafilter_test.go, pkg/segment/reader/microreader/microreader.go, pkg/segment/reader/segread/segreader/segreader.go, pkg/segment/reader/segread/segreader/tests/segreader_test.go, pkg/segment/reader/segread/timereader.go, pkg/segment/reader/segread/timereader_test.go, pkg/segment/search/segsearch.go, pkg/segment/search/segsearch_test.go, pkg/segment/segexecution_test.go, pkg/segment/structs/segsearchstructs.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go, pkg/segment/writer/segstore.go
- Remove unused byte param
- Use string interning to reduce repeated creation of cname string
=> code simplification, mem improvements

pkg/segment/writer/metrics/metricssegment.go
=> Fix nil pointer panic

tools/promtest/README.md, tools/promtest/docker-compose.yaml, tools/promtest/prometheus.yaml, tools/promtest/server.py
=> Add tool to easily check Prometheus query response

static/css/metrics-explorer.css
=> Fix : Metrics Explorer Legends/Series Height

pkg/usageStats/stats.go
=> Fix usage stats timestamp issue

.github/CODEOWNERS, .github/pull_request_template.md
Update codeowners and remove PR template bloat
=> Clean up PR workflow

static/js/common.js
=> UI Fix: Unflatten JSON

pkg/hooks/hooks.go, pkg/server/query/entryHandlers.go
=> naming and usage stats fix

pkg/config/version.go
=> Bump version to 1.0.38

pkg/config/version.go, pkg/health/clusterStatsHandler.go, pkg/hooks/hooks.go, pkg/server/query/entryHandlers.go, static/component/infrastructure/header-component.js, static/component/time-picker/time-picker.js, static/css/query-builder.css, static/css/siglens.css, static/js/event-handlers.js, static/js/kubernetes-overview.js, static/js/kubernetes-view.js, static/js/metric-summary.js, static/js/metrics-cardinality.js, static/js/metrics-explorer.js, static/js/navbar.js, static/js/service-health-overview.js, static/js/service-health.js, static/js/usage-stats.js, static/org-settings.html, static/usage-stats.html
=> Release 1.0.38

pkg/config/version.go
Preparing branch for 1.0.39 development
=> Bump the version to 1.0.39d

tools/promtest/Makefile, tools/promtest/README.md, tools/promtest/docker-compose.yaml
=> Make the promtest tool easier to use

pkg/hooks/hooks.go
=> Fix: Update Hooks

playwright-tests/tests/ingestion.test.js
=> Fix Ingestion Screen Playwright Test

pkg/segment/query/processor/dedupcommand.go, pkg/segment/reader/segread/segreader/segreader.go, pkg/segment/utils/segconsts.go
=> some debugging changes

static/js/common.js, static/js/usage-stats.js, static/usage-stats.html
- Added the ability to export Usage Stats data a CSV format. 
- Table format: 
=> Add the ability to export Usage Stats data

pkg/config/version.go
=> Update version.go 1.0.40

pkg/segment/metadata/metadata.go, pkg/segment/metadata/segmentmicroindex.go, pkg/segment/reader/record/recordreader.go, pkg/segment/writer/unrotatedquery.go
=> avoid repeated map creations and reuse maps

static/js/search.js
=> UI: WebSocket Fix

static/css/siglens.css, static/js/settings.js, static/org-settings.html
=> UI: Org Settings Page Styling

pkg/segment/aggregations/timechartagg.go
Fixes a panic on certain timechart queries.
Ingest some data, then run a query like
```
* | timechart avg(latency_c1) by http_method_c1 span=1h
```
Previously, if the column in the `by` part didn't exist, we'd get a panic. Now if that happens we get the same result as when the `by` clause is excluded. When the column does exist, we still do the group by logic.
=> Fix timechart panic when groupby col doesn't exist

pkg/config/version.go
=> Update version.go 1.0.42

pkg/segment/query/processor/dataprocessor.go
=> Add helper function

static/css/siglens.css
=> Adjusting visibility of feild names

static/alert.html, static/dashboard.html, static/js/query-builder.js
=> UI: Dashboard Fix

eslint.config.mjs, static/css/dashboard.css, static/css/siglens.css, static/js/common.js, static/js/dashboard-charts.js, static/js/dashboard.js, static/js/edit-panel-screen.js, static/js/event-handlers.js, static/js/logs-visualization.js, static/js/search.js
=> Dashboards UI: Line Chart Support for Logs Visualization

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/notificationHandler.go, pkg/alerts/alertutils/alertutils.go
=> Added support for custom headers in webhook configuration

cmd/startup/startup.go
=> Add nil check to avoid panic on shutdown

pkg/segment/reader/segread/segreader/segreader.go, pkg/segment/search/filtersearch.go
Fixup to avoid saying a block is valid when it was invalid.
Only existing CICD
=> Ignore errors when a block lacks a certain column

pkg/config/version.go
=> Bump Version to 1.0.44d

pkg/ast/spl/tests/splParser_test.go
The test fails sometimes, but it's not clear why since it relies on a randomly generated string.
=> Give more detail when SPL unit test fails

pkg/config/version.go
=> Bump Version to 1.0.44

static/js/search-traces.js
Update Queries to Retrieve Service and Operation Names Using SPL Instead of SQL
=> Search Traces: Service and Operation Queries

.github/workflows/nightly-longer-functional.yml
Run nightly longer functional just once per day
=> run nightly longer once

static/css/siglens.css, static/index.html, static/js/common.js, static/js/dashboard-logs-results-grid.js, static/js/download-logs.js
1. Fix: Download Aggregation Query Results
2. Fix: Enable Text Selection in Aggregation Table
=> Fix: Download Aggregation Query Results 

pkg/config/version.go
=> Update version.go 1.0.45

pkg/config/version.go
=> Update version.go to 1.0.46d

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/queryprocessor_test.go, pkg/segment/segexecution.go
=> Fix: Use requested size for search result limit instead of hardcoded 100

pkg/config/version.go
=> Bump to 1.0.46

pkg/ast/pipesearch/multiplexer/queryStateMultiplexer.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/config/version.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/queryprocessor_test.go, pkg/segment/segexecution.go, static/css/siglens.css, static/index.html, static/js/download-logs.js, static/js/pagination.js, static/js/usage-stats.js, static/usage-stats.html
=> Release 1.0.46

pkg/config/version.go
=> Bump to 1.0.47d

static/css/query-builder.css, static/js/pagination.js, static/js/search.js
Fix: For query `(URL=http* OR URL=https*) | stats count as cnt by BadColName | sort -cnt | head 15` we are getting an empty result, but in the console frontend was gettingan  error, which is why the search was showing loading.
=> Fix: Pagination Error

static/assets/lookups-icon-active.svg, static/assets/lookups-icon-inactive.svg, static/css/siglens.css
Added a new icon for `Lookups` in the side navbar, previously we were using the same icon as `Logs`.
The icon clearly communicates that users can input/upload files.
=> Added New InputLookup Icon in Side Navbar

pkg/config/version.go
=> Bump to 1.0.47

pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/segreader/segreader.go
=> avoid formulating debug lines in fast path

pkg/config/version.go
=> Update version.go 1.0.48

pkg/config/version.go, pkg/segment/query/distributedquery.go, pkg/segment/query/segquery.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/segreader/segreader.go
=> release 1.0.48

pkg/config/version.go
=> Update version.go 1.0.49d

pkg/segment/query/processor/dataprocessor.go
This speeds up query execution when there's multiple streams to fetch from
=> Fetch from multiple streams in parallel

pkg/segment/query/processor/searcher.go
When there's multiple streams to fetch from, this fixes a bug where the number of records to search was specified as artificially low. It's similar to https://github.com/siglens/siglens/pull/2694, but that PR missed a case, which caused the incorrect number to be shown for the query `* | sort 100 latency_c1`
The logic for finding/summing the counts for each stream is a bit convoluted and should be cleaned up at some point.
Tested on
```
* | stats count
* | sort 100 latency_c1
*
```
and manually checked what the UI showed for the total number of records
=> Fixup for getting total records to search

pkg/config/version.go
=> Update version.go 1.0.49

pkg/ast/pipesearch/searchHandler.go, pkg/blob/blobStorage.go, pkg/config/version.go, pkg/hooks/hooks.go, pkg/retention/retention.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/searcher.go
=> release 1.0.49

pkg/config/version.go
=> Update version.go 1.0.50d

static/js/logs-histogram.js, static/js/search.js
=> Clear message for histogram when running  stats queries

pkg/config/version.go
=> Update version.go 1.0.50

eslint.config.mjs, pkg/config/version.go, pkg/segment/aggregations/timechartagg.go, pkg/segment/aggregations/timechartagg_test.go, pkg/segment/query/processor/timechartcommand.go, pkg/segment/query/processor/timechartcommand_test.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go, pkg/segment/utils/number.go, pkg/segment/utils/segconsts.go, static/alert.html, static/css/query-builder.css, static/index.html, static/js/ag-grid-seg-stats.js, static/js/alert.js, static/js/dashboard-charts.js, static/js/event-handlers.js, static/js/log-search.js, static/js/logs-histogram.js, static/js/pagination.js, static/js/search.js
=> release 1.0.50

pkg/config/version.go
=> Update version.go 1.0.51d

pkg/segment/query/iqr/intermediateQueryResult.go
=> Optimize reading timestamps from IQR

pkg/config/version.go
=> Bump to 1.0.51

pkg/config/version.go, pkg/segment/query/iqr/intermediateQueryResult.go, static/js/search.js
=> Release 1.0.51

pkg/config/version.go
=> Bump to 1.0.52d

FIRST_TIME_GIT_USERS_GUIDE.md, README.md
Monospace fonts are usually used for showing code. Inkeeping with this idea:
1. In README.md, several numbers mostly relevant to performance (e.g. 8 TB / day) were highlighted using monospace font. This has been changed to use bold HTML tags
2. In FIRST_TIME_GIT_USERS_GUIDE.md, all terminal snippets have been rewritten to use monospace fonts.
=> Monospace font use made exclusive to code in README.md and FIRST_TIME_GIT_USERS_GUIDE.md

pkg/dashboards/dashboards.go, static/component/dashboard/breadcrum.js, static/js/dashboard.js, static/js/folder.js
- Fixed an issue where breadcrumbs for dashboards and folders were not appearing correctly in the UI.
- Updated the backend to return breadcrumb information when dashboards are updated.
=> Fix: Breadcrumb Display Dashboards and Folders

pkg/segment/query/processor/searcher.go
This removes some unnecessary work during queries, to improve performance. It shouldn't change any query results.
Previously when the Searcher had multiple streams we'd merge the streams and sort them again. But the streams were already sorted in the order we re-sorted them. This PR removes that extra, unnecessary sorting. This yields significant improvement when many records match the initial search.
Tested with `SearchPhrase != "" | sort 10 str(EventTime) | fields SearchPhrase, EventTime` on 100 million records. In version 1.0.41 of siglens, this took ~6 seconds; and with this PR it also takes ~6 seconds. But with https://github.com/siglens/siglens/pull/2623 and without this PR, it was taking >200 seconds
=> Remove unnecessary sorting work

static/pqs-settings.html
- Resolved alignment and CSS issues for buttons in the PQS Settings popup.
=> UI Fix: PQS Setting Buttons

pkg/server/ingest/server.go, pkg/server/query/server.go
Health check API (used by deployment script) should not require any middleware checks.
=> Health check API should not be behind auth checks

static/js/common.js, static/js/search.js
=> UI: Remove progress bar when an error occurs during query execution

pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/searcher.go, pkg/segment/query/processor/streamer.go, pkg/segment/query/processor/tests/queryprocessor_test.go, pkg/utils/maputils.go
Reapply https://github.com/siglens/siglens/pull/2748 and fix the issues with it that caused some tests to fail
CICD. Also ran the query in the Testing section of #2748
=> Reapply #2748 with fixes

pkg/utils/sliceutils.go
For some queries, `BatchProcess()` was using significant memory just from moving slices. This PR does some extra work up front to determine the require size, but then just allocates the slice once.
This might make some other queries slightly slower; maybe later we'd want to add elements to the slices up to a certain point and if they grow too large then stop adding them directly and instead just count the elements in each batch like this PR does.
Tested with 100 million records on 
```
* | eval height=ResolutionHeight / 10 | stats avg(height) as avg, count(height) as count, sum(height) as sum by ResolutionWidth | sort -ResolutionWidth
```
This PR reduced the total allocated memory from 68 GB to 46 GB and reduced the query time from 12.2 seconds to 11.1
=> Allocate slices in BatchProcess with correct size

static/css/siglens.css, static/dashboard.html, static/index.html, static/js/dashboard.js, static/js/edit-panel-screen.js
Improved CSS and UI design for the query settings on the logs screen for better usability. 
**Before**
**After**
=> UI: Improve CSS for Logs Query Settings

static/css/dashboard.css, static/js/dashboard-logs-results-grid.js, static/js/edit-panel-screen.js
Fixes a bug where dashboard panels with different queries would show the same data on the main dashboard screen.
=> UI Fix: Dashboard Panels Displaying Same Query Results

pkg/segment/search/searchaggs.go
Speed up query time for stats queries.
Got 10% faster query response on 
```
* | stats dc(UserID) as u BY RegionID | sort 10 -u
```
=> Optimize map iteration

pkg/hooks/hooks.go, static/css/siglens.css, static/js/cluster-stats.js, static/js/navbar.js
=> Added Hooks

benchmark_test.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/ast/common.go, pkg/ast/pipesearch/listIndicesHandler.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/es/reader/esGetSingleDocHandler.go, pkg/es/reader/esQueryHandler.go, pkg/es/writer/esBulkHandler.go, pkg/hooks/hooks.go, pkg/querytracker/querytracker.go, pkg/segment/query/metadatafilter_test.go, pkg/segment/query/segquery_test.go, pkg/segment/segexecution_test.go, pkg/segment/segexecutionbench_test.go, pkg/segment/segexecutionsort_test.go, pkg/segment/structs/querystructs.go, pkg/virtualtable/virtualtable.go, pkg/virtualtable/virtualtable_test.go
Reverts siglens/siglens#2810
Incomplete changes.
=> Revert "Check if access to an index is allowed"

benchmark_test.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/ast/common.go, pkg/ast/pipesearch/listIndicesHandler.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/config/version.go, pkg/es/reader/esGetSingleDocHandler.go, pkg/es/reader/esQueryHandler.go, pkg/es/writer/esBulkHandler.go, pkg/hooks/hooks.go, pkg/querytracker/querytracker.go, pkg/segment/query/metadatafilter_test.go, pkg/segment/query/segquery_test.go, pkg/segment/segexecution_test.go, pkg/segment/segexecutionbench_test.go, pkg/segment/segexecutionsort_test.go, pkg/segment/structs/querystructs.go, pkg/virtualtable/virtualtable.go, pkg/virtualtable/virtualtable_test.go
=> Release version 1.0.54

static/css/siglens.css, static/js/dashboard-logs-results-grid.js, static/js/event-handlers.js, static/js/log-results-grid.js, static/js/search.js
Fixes issue where XML and HTML content was being rendered as HTML instead of displaying as plain text in Logs grid for both Logs and Dashboards Screen.
Before: 
After:
=> Fix XML content displaying in Logs Grid

pkg/config/config_test.go, pkg/es/writer/esBulkHandler.go, pkg/utils/withdefault.go
=> Cleanup helpers

pkg/segment/query/processor/streamstatscommand.go, pkg/segment/structs/segstructs.go
Percentile and median now work with streamstats
=> Fix: Perc not working with streamstats

pkg/segment/structs/evaluationstructs.go, tools/sigclient/functionalQueries/functionalQueries.yml, tools/sigclient/functionalQueries/mvfilter.json
Implemented mvfilter function to filter multivalue fields based on a condition. [Docs](https://docs.splunk.com/Documentation/Splunk/9.1.1/SearchReference/MultivalueEvalFunctions)
Added individual functional test to include mvfilter
=> Add SPL multivalue eval functions - mvfilter

benchmark_test.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/ast/common.go, pkg/ast/pipesearch/listIndicesHandler.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/config/version.go, pkg/es/reader/esGetSingleDocHandler.go, pkg/es/reader/esQueryHandler.go, pkg/es/writer/esBulkHandler.go, pkg/hooks/hooks.go, pkg/querytracker/querytracker.go, pkg/segment/query/metadatafilter_test.go, pkg/segment/query/segquery_test.go, pkg/segment/segexecution_test.go, pkg/segment/segexecutionbench_test.go, pkg/segment/segexecutionsort_test.go, pkg/segment/structs/querystructs.go, pkg/virtualtable/virtualtable.go, pkg/virtualtable/virtualtable_test.go
=> Revert "Release version 1.0.54"
