siglens/siglens

pkg/es/writer/esBulkHandler_test.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
This fixes an issue where siglens would crash when a single block had a column where both string and numeric values were being ingested. In particular, this caused siglens to crash when ingesting example traces when following the instructions in #38 but now you can follow those instructions to ingest example traces and siglens handles it properly.
Now when records are being added to a block, different records can have a string or numeric value for the same column. When the block is flushed, we try to convert all those values to numbers but if any of those conversions fail we abort and instead convert all the values to strings.
=> Fix ingestion issue

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/new_feature_request.md, .github/ISSUE_TEMPLATE/story.md, .github/pull_request_template.md
This adds templates for PRs and issues. For issues, you can either create a blank issue or use a template for a
* bug report
* feature request
* story describing how to implement a task
=> Add PR and issues templates

CONTRIBUTING.md
In [CONTRIBUTING.md](https://github.com/siglens/siglens/blob/main/CONTRIBUTING.md?plain=1#L99):
The link to README.md of sigscalr-client is broken
Fixes #109 
Checked link re-direction.
=> Fixed README.me link for sigscalr-client

pkg/segment/tracing/handler/tracehandler.go, pkg/segment/tracing/structs/tracestruct.go
Add ServiceName and OperationName for the search traces' response
```
request: api/traces/search
response: 
{
traces: [
{
"trace_id": string,
"start_time": int,
"end_time": int,
"span_count": int,
"span_errors_count": int,
"service_name": string,
"operation_name": string,
},
```
=> Update Search Traces API Response

pkg/segment/reader/segread/agiletreereader.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/agiletreewriter.go
Previously, the AgileAggsTree didn't work properly when the query had multiple GroupBy columns. This fixes that issue. Each node in the tree is supposed to store its own key as well as its ancestors' keys all the way up to the root node. However, only the current node's key was being stored. These keys are used to determine the value of each GroupBy column that the tree accounts for.
I've only done manual testing. We should add unit tests to ensure we never get this issue again.
For manual testing, I followed these steps:
1. Append `agileAggsEnabled: true` to server.yaml
2. Start siglens
3. Setup PQS with this API call:
```bash
"tableName": "benchmark",
"groupByColumns": ["cab_type", "passenger_count", "pickup_date", "trip_distance"],
"measureColumns": ["total_amount"] …
```
=> Fix issue serving queries with multiple GroupBys from AgileAggs

static/js/dashboard.js
Fixed an issue where the dashboard name wasn't being refreshed on update.
Fixes #203 
I utilized the existing method to display the dashboard name upon saving the DB settings and tested it by updating a dashboard name to verify that it's being updated without a refresh.
=> Fix: Dashboard Name Update Issue on Refresh

pkg/segment/utils/segconsts.go, pkg/segment/writer/segwriter.go
This clarifies the units of time for a few constants.
This should have no effect except for line 225 in segwriter.go. Previously that line had just been using the variable as if it was in nanoseconds, but the variable was specified in milliseconds. See https://pkg.go.dev/time#Duration
I have not tested this other than making sure siglens compiles and runs.
=> Clarify units of time

pkg/segment/reader/segread/agiletreereader.go, pkg/segment/results/blockresults/blockresult.go, pkg/utils/bitutils.go
This makes a few different changes, each of which improve the speed that we can use an AgileAggs tree to answer a query. 
1. Estimate how much space we need for a string builder so that we can allocate the slice upfront instead of doing multiple smaller allocations.
2. Avoid copying data to create a string from a []byte. We do this by using an unsafe conversion, but we don't change that data once we set it, so it should be safe.
3. Rearrange some logic for getting the raw value for an encoded value. With this change we only have to lookup `allDictEncodings[colName]` once instead of doing it for each bucket; this saves some time when there's a lot of buckets.
It might be easier for reviewers to review each commit one-by-one instead of looking at the whole PR.
To make sure my queries used …
=> Aggs tree performance

pkg/config/config.go, pkg/config/config_test.go
Now when `agileAggsEnabled` is not set in server.yaml, it defaults to true instead of false.
I haven't done much testing, I just printed the value of `config.IsAggregationsEnabled()`. When `server.yaml` has no changes or when it has `agileAggsEnabled: true`, this correctly prints `true`. When the config files has `agileAggsEnabled: false` this correctly prints `false`
=> Enable AgileAggs by default

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg
This allows the `AS` and `BY` keywords to be matched case insensitively. It also allows multiple spaces where we have at least one space.
With these changes, the following command gives a result, rather than a syntax error:
```
*      |     stats     count    by       VendorID
```
Without these changes, that query gave a syntax error. Also without those changes both of the following queries gave syntax errors
```
* | stats count by VendorID
* |     stats count BY VendorID
```
=> Fix case sensitivity and multiple spaces

pkg/segment/query/metadata/metadata.go
Previously when we did `rebalanceCmi()`, we only loaded the PQS columns. Then in `RunCmiCheck()` we don't load any CMIs if the `loadedMicroIndices` flag is true (line 120). This makes a temporary quick fix, so that during `rebalanceCmi()` we load the indices for all columns, not just the PQS columns.
Later, we should revert this PR and make fix this properly. That would mean `rebalanceCmi()` only loads the PQS columns, but `loadedMicroIndices` should be converted from a boolean value to a set of strings indicating for which columns we have the micro indices loaded.
1. Start siglens
2. Ingest some data
3. Stop siglens
1. In server.yaml, append `pqsEnabled: false`
2. Restart siglens
3. Run a query. I tested with just the SPL query `HEAD` (using dummy data from the sigscalr-client). For this …
=> Load CMIs for all columns when rebalancing

pkg/ast/common.go, pkg/segment/search/filtersearch.go, pkg/segment/structs/querystructs.go, pkg/segment/structs/searchhelpers.go
This fixes an issue with SPL queries where `NOT` was used for a search on all columns. For example, `NOT HEAD`
I ingested data from sigscalr-client:
```
go run main.go ingest esbulk -n 10 -g benchmark -d http://localhost:8081/elastic -t 100_000
```
I tested the following queries. These all return correct results with the changes from this PR, but give incorrect results without this PR.
```
NOT HEAD
weekday=Tuesday NOT HEAD
NOT Arttalk
(GET OR POST) NOT Tuesday
NOT (HEAD OR POST OR DELETE)
```
(Arttalk was one of the `app_name` values in my dataset)
=> Fix SPL queries with NOT on all columns

cicd/ingest.csv, cicd/restart.csv, pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go
Allow using multiple spaces for:
1. Those commands or operators which need at least 1 space on one side or both sides. 
```
E.g.
CMD_SEARCH <- "search" SPACE
OR <- SPACE "OR" SPACE
keyword: limit, like, in... (It should have at least one space at left side)
```
- Central idea: Use regex to replace multiple spaces with one (except for the spaces inside string literals)
<br>
2. For those commands or operators which can allow 0 space or multiple spaces around them.
```
E.g.
1. ',' 2. '(' 3. '=' 4. '-' ... 
```
- Central idea: Central idea: Create a rule EMPTY_OR_SPACE <- " "?, and put this rule around these operators
```
OpPlus <- EMPTY_OR_SPACE "+" EMPTY_OR_SPACE {
return "+", nil
}
COMMA <- EMPTY_OR_SPACE "," EMPTY_OR_SPACE
L_PAREN <- "(" EMPTY_OR_SPACE
R_PAREN <- EMPTY_OR_SPACE ")"
``` …
=> Allow Spl query using multiple spaces

pkg/ast/common.go, pkg/ast/pipesearch/resultStructs.go, pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/timechartagg.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/search/searchaggs.go, pkg/segment/segexecution_test.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/segstructs.go, pkg/segment/utils/timeconsts.go
Add limit option for spl timechart.
To do in next pr:
- Finish all the merge val logic for non-numeric agg func (Values, Cardinality)
- Add some more options for timechart
```
The results are the same as the `stats block` for the following queries:
1. 
* | timechart span=1h sum(latitude)
* | stats sum(latitude)
2.
city=Boston | timechart span=1hrs sum(latitude) range(longitude) BY weekday 
city=Boston | stats sum(latitude) range(latitude) BY weekday
3.
Maryland NOT Boston | timechart span=1hrs sum(latitude) range(longitude) BY http_method limit=3
Maryland NOT Boston | stats sum(latitude) range(longitude) by http_method
Maryland NOT Boston | stats count by http_method (The score is based on the frequency of each value of <field>)
4.
Boston NOT male latency > 1000000 | timechart span=10m …
```
=> Spl timechart (Limit option)

cicd/ingest.csv, cicd/restart.csv, pkg/segment/query/metadata/blockmeta.go
This bypasses the CMI checks when there's a NOT expression. This is because the CMI checks are performed using the bloom indexes, which either say the string is probably in the block or is definitely not in the block; but when negate this we get that the string is probably not in the block or definitely is in the block, so we have to search all the records in all the blocks anyways, making the bloom check useless.
1. Start siglens with an empty `data/` directory
2. From sigscalr-client, ingest some data with:
```
go run main.go ingest esbulk -n 1 -g benchmark -d http://localhost:8081/elastic -t 1_000_000
```
3. Run the following queries:
```
app_name="Albumis" (Wednesday OR Tuesday)
app_name="Albumis" (Wednesday OR Tuesday) NOT asdfjkliuer
```
Both queries should return the same results …
=> Don't do CMI check when there's a NOT expression

cicd/ingest.csv, cicd/restart.csv, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go
In the past, only the first search block can execute without using keywrod `search`
E.g.:
`"Santa Ana" | search latency > 500000`
After this change, allow this type of query:
E.g.:
`"Santa Ana" | latency > 500000`
=> Fix: Allow the search block without using keyword "search"

pkg/common/fileutils/fileutils.go
Previously we always used 8192 as the max number of open files. Now we use the result of a system call to get the current max, and use that.
I ran siglens on my machine and through docker. On my machine, the limit was 122880 (but we use 70% of the max, so 86016). On docker I got 1048576 (so 70% is 734,003). 
=> Use existing FD limit

pkg/segment/writer/segstore.go
When new columns are added, they're included in `colWips`. However, old columns aren't removed, so the size could grow. If it gets larger than it should, we'll reset it.
I've not tested this
=> Clear colWips if it's too large

static/js/event-handlers.js
Fixed issue with the query builder not allowing the stats query without specifying a groupBy column
=> Allow Running Stats Query Without GroupBy

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/server/query/entryHandlers.go, pkg/utils/accessLogUtils.go, pkg/utils/accesslogutils_test.go
This makes it so access.log logs both UI and API queries, even when the queries are invalid so they exit due to error handling.
I tested some valid and invalid queries via the API:
```
"searchText": "* | stats max(latency)",
"index": "*",
"startEpoch": "now-240h",
}' http://localhost:5122/api/search | python3 -m json.tool
"searchText": "* | stats max(latenc",
"index": "*",
"startEpoch": "now-240h",
}' http://localhost:5122/api/search | python3 -m json.tool
```
I also tested valid and invalid queries on the UI
```
city=helloworld
city=helloworld | stats lskdjf
```
I got this in my access.log
```
2024-01-08 17:40:45 No-user http://localhost:5122/api/search { …
```
=> Make access logs more robust

pkg/segment/aggregations/segaggs.go
- SPL Transaction command was not showing results when only the StartsWith command was given.
- So the issue was that the code was not appending the results until it found another StartsWith condition.
- I changed the code to append the code when EndsWith is not given and append any leftover grouped records.
- Tested the command with commands on UI.
- Tested with the automated tests written in `segaggs_test.go`
=> fix: SPL Transaction Startswith bug fixed

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/aggregations/segaggs.go, pkg/segment/structs/evaluationstructs.go
This adds support for `dedup` blocks after a `stats` block.
I manually tested this by running queries like 
```
* | stats count as count by weekday, http_status | dedup weekday
```
which gives 
=> Support dedup after a groupby 

static/js/search-traces.js
On tracing page when the user clicks on the graph and select a trace by clicking it, showing details about the trace like duration, no. of spans, no. of error spans and  the trace id.
Fixes #418 
- [ x ] I have self-reviewed this PR.
- [ x ] I have removed all print-debugging and commented-out code that should not be merged.
- [ x ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
=> Showing info about traces

.github/workflows/publish-prod-images.yml, install.sh
- Added the `install.sh` script as a release asset.
- Added `podman-compose.yaml` && `podman-network_siglens.conflist` as release assets.
- Changed the Curl URLs of the above two files to GitHub release versions.
=> PR: Add Podman Install scripts as release assets

pkg/segment/tracing/handler/tracehandler.go
The percentile numbers on the service-health page was initially shown in nano seconds instead of milliseconds. This change converts the durations to ms.
Fixes #419
- Tested it by sending a small number of traces and verifying the accuracy of the percentile values manually.
=> Fix: P50, P90 and P99 numbers on service health page

static/css/siglens.css, static/dashboard.html, static/js/edit-panel-screen.js
exiting edit panel screen with unsaved changes shows alert
Fixes #444  (link all the GitHub issues this addresses)
1. Make a dashboard and add a panel
2. Make some changes to the panel (select a Data Source, enter a query, etc.) but don't click the Save or Apply buttons.
3. In the top left, click the back arrow next to <MyDashboard> / <MyPanel> (not the browser's back button)
If you made changes in panel name, panel description, chart type, query type, query message, and so on (essentially deep compare of currentPanel object with original panel), shows popup. If there is no change, popup doesn't show up. If you clicked save button and exited without further change, popup doesn't show up.
Before marking your …
=> feat: exiting edit panel screen with unsaved changes shows alert

.circleci/config.yml, install.sh, install_with_docker.sh, pkg/config/version.go, playground.yaml, server.yaml
Add timeout for docker script to check exit if docker does not start in 3 minutes and use playground.yaml instead of server.yaml on playground machine. Playground should be added to   
Tested timeout by stopping docker and reducing the wait time to start docker and  test the case where docker wont start in time on local machine.
Tested playground.yaml by setting the environment in my machine and execute the script to use playground.yaml
=> Add timeout for install script and use playground.yaml on playground

cmd/startup/startup.go, pkg/config/config.go, pkg/config/config_test.go, playground.yaml, server.yaml
This PR makes Ingest and Query Listen IP addresses configurable in server.yaml. This is the list of changes:
-     Add ingestListenIP and queryListenIP to server.yaml
-     Add IngestListenIP and QueryListenIP to Configuration
-     Implement GetIngestListenIP and GetQueryListenIP functions and call them in place of hard coded strings in startup.go.
-     Set the defaults in ExtractConfigData, InitializeDefaultConfig and server.yaml, update playground, tests and examples.
Fixes #507 
- Define 0.0.0.0 for ingestListenIP and queryListenIP 
- Define 127.0.0.1 for ingestListenIP and queryListenIP 
- Define different IPs ingestListenIP and queryListenIP 
in server.yaml and run siglens. Both services should start listening on the corresponding specified IP Addresses. 
- [x ] I have removed all …
=> Make Ingest and Query Listen IP Addresses configurable

install.sh
- A slight fix for the install script regarding the creation of the `env` file. Creating `.env` file with sudo access.
- The `.env` will only be created for docker installation.
- I have tested the script by running it on the Ubuntu Instance.
=> fix: podman install sudo script

static/dashboard.html
Added descriptive `alt` texts for all the images in the file `dashboard.html`.
Made sure if the images are not visible, the alt text provides concise description about the element while not cluttering the view.
Fixes #553 
Since the changes were made in HTML files, built the project and tested it locally.
- Tested dashboard in the happy path
- Tested the dashboard on desktop view after removing source images (.svg files)
- Tested the dashboard on Mobile view similarly. _(*optional)_
_screenshots were taken after the assets were unloaded, simulating scenarios for resource not found_
=> Fix: #553 Add alt text for images in dashboard.html

CONTRIBUTING.md
- Updated the SigLens Contributing guide regarding the Linux dependencies.
- Linux systems, require `build-essential` package to run the SigLens Server.
Fixes #582
=> chore: Contributing guide Linux dependecy update

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/writer/rawchecker.go
- The Timechart Argument `span` will work regardless of the order.
- Tested against the SigLens UI.
- Updated existing and have written additional tests to test the queries.
=> fix: Timechart span Argument

pkg/ast/common_test.go
Adding unit test for GetDefaultTimechartSpanOptions
Fixes #563  
=> Add unit test for GetDefaultTimechartSpanOptions. Issue 563

pkg/config/config.go
The behavior of `GetQueryServerBaseUrl()` was inconsistent. If the provided hostname was empty, it would return the url with the port, but if the hostname was not empty, it would exclude the port.
=> Fix GetQueryServerBaseUrl

CONTRIBUTING.md
- This PR contains an addition on how to open an issue in the Siglens repo and an explanation of all four types of issues.
- Added a section explaining the current Linux and macOS support for local development on Siglens and steps to setup on local machine.
Fixes #628 
- As a follow-up to this PR, I think there should be one more Issue Type named Doc to target documentation changes.
- The golinter link in the CONTRIBUTING.md is not working:
https://github.com/siglens/siglens/blob/a73152da87724525e9d23b92b924756a45d08b72/CONTRIBUTING.md?plain=1#L81
=> docs: add macOS setup and open an issue instructions in CONTRIBUTING.md

pkg/ast/common.go, pkg/segment/utils/segutils.go
Fix an issue where running a query with an invalid regex expression caused the server to crash.
Fixes #641 
Ran this invalid regex query (it's invalid because of the `\` before `795`):
```
* | regex address="\795 North Plains view, Pittsburgh, Ohio 94834" | fields address
```
And I got this:
=> Return error on bad regex, instead of crashing

cmd/startup/startup.go, pkg/config/common/common.go, pkg/config/config.go, pkg/server/ingest/server.go, pkg/server/query/server.go, server.yaml
- SSL/TLS for the query and ingest service can be enabled.
- Added two more variables under TLS config to take the Certificate and PrivateKey.
- Tested by setting up a domain, generating a Certificate and private key, and Enabling the TLS.
- Ingested data from my local to hosted URL ingestion `https` endpoint.
- Ran queries against the UI and sent sample test data from UI against the `https` query endpoint.
=> Enable SSL/TLS for Query and Ingest Service. 

tools/sigclient/README.md
- The cmd on the SigClient readme sets to use `10_000` indices instead of events.
- I changed it to use events.
=> Fixed the SigClient cmd to use events instead of indices

pkg/segment/aggregations/timechartagg.go
Fixes the time chart panic error: index out of range. The time chart index is returning the index to be the same length as the time chart time points, which is causing the panic. I have made a condition to check to assign it to the last time bucket.
- I have tested the query against the Localhost UI.
- Need to run this on Playground.
=> fix: timechart bucket index out of range

pkg/config/version.go
- Incremented the Siglens version to 0.1.30
- Added the suffix `d`
=> Bump SigLens version to 0.1.30 and add the suffix d

static/css/query-builder.css
Added css property,"width" for the dynamically created dropdown.
Fixes #569  (link all the GitHub issues this addresses)
Populated the logs data for address info and then filtered to check if the width property added works.
=>  Address dropdown should be large enough#569

go.mod, go.sum, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/segaggs_test.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/segexecution.go, pkg/segment/segexecutionbench_test.go, pkg/segment/structs/segstructs.go
- The Transaction command now groups events from the entire set of records based on the given time.
- The command can be very slow and resource-intensive if not queried properly.
- Queries like just raw transaction requests will take too much time and resources. Example: `* | transaction ip session ...`
- Filter out the search and columns or use limit and many more to get the exact events that you want the grouping of events in the form of transaction. Example: `search productId=pro98766 | fields productId, ip, session, action, email, etc | transaction ip session startswith=view endswith=purchase`
=> Transaction Command fix for Multiple Segments

pkg/config/version.go
- Incremented the SigLens version to 0.1.31 and added the suffix `d`.
=> bump develop version to 0.1.31d

pkg/server/ingest/server.go, pkg/server/query/server.go, pkg/server/utils/utils.go
Now instead of having splunk endpoints under `/splunk/` in the URL, it's just under `/`
I ingested data with vector using the splunk ingestion methods. This was my vector config:
```
data_dir: deleteme-vector
sources:
read_from_file:
type: file
include:
- 2kevents.json # Path to the log file
generate_syslog:
type: 'demo_logs'
format: 'syslog'
count: 2
transforms:
remap_file_log:
inputs:
- 'read_from_file'
type: 'remap'
source: |
structured = parse_json!(.message)
., err = merge(., structured)
sinks:
siglens:
type: splunk_hec_logs
inputs:
- generate_syslog
- remap_file_log
endpoint: http://localhost:8081
host_key: hostname
index: 'ind-0'
indexed_fields:
- index
timestamp_key: time
compression: none
encoding:
codec: json
default_token: 'A94A8FE5CCB19BA61C4C08'
batch:
max_events: 1
``` …
=> Remove the url splunk prefix

pkg/integrations/splunk/splunk.go
This allows ingesting multiple records into siglens using the splunk integration. Previously you could only ingest one record at a time.
I was able to ingest some logs with the below:
```
curl -XPOST -d '[{
"index": "example",
"field1": "apples",
"field2": "oranges"
},
{
"field1": "thing1",
"field2": "thing2"
}]' http://localhost:8081/services/collector/event
```
=> Allow ingesting multiple records with splunk

pkg/segment/query/segquery.go
There was an issue that caused the `MeasureFunctions` to not be populated for groupby queries where the max number of buckets were created. In this case the buckets that were created weren't properly being flushed and so the `MeasureFunctions` were not being set. So then for queries like that that also rename or create some `MeasureFunctions`, those weren't being properly handled.
Now this query correctly has `avg_lat` and `r_avg_lat` columns. Previously it had `avg(latency)` (so it wasn't renamed to `avg_lat`) and the `r_avg_lat` column never got created.
```
* | stats avg(latency) as avg_lat by app_name | eval r_avg_lat=round(avg_lat)
```
=> Flush the histogram after finishing all segments

pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/segaggs_test.go, pkg/utils/sliceutils.go, pkg/utils/stringutils.go
Now you can run queries like `... | stats ... | fields ...`
Added some unit tests, and also manually tested with these queries:
```
* | stats count as Count by http_status, http_method | eval mine=http_method . " -> " . http_status | fields mine, Count
* | stats count as Count by http_status, http_method | eval mine=http_method . " -> " . http_status | fields *m*
* | stats count as Count by http_status, http_method | eval mine=http_method . " -> " . http_status | fields -*m*
* | stats count as Count by http_status, http_method | eval mine=http_method . " -> " . http_status | fields http*, mine | fields -*status
* | stats count as Count by http_status, http_method | eval mine=http_method . " -> " . http_status | fields -http*
* | stats count as Count by http_status, http_method, weekday | …
```
=> Allow SPL fields command after groupby

static/js/saved-queries.js
Saved Queries Page dynamically loads content after the initial page load, the event handler is not attached to the button because it wasn't present in the DOM at the time the script ran. Using event delegation from a static parent element or the document itself to solve
Fixes #<541> (https://github.com/siglens/siglens/issues/541#top)
test pass.
=> bug fix (issue#541) for Dark/Light Mode toggle on saved queries page

pkg/integrations/splunk/splunk.go, pkg/utils/httpserverutils.go, pkg/utils/httpserverutils_test.go
This allows the splunk ingestion endpoint to handle data that is gzipped. It also makes it handle multiple records that are sent as a series of JSON objects (not inside a JSON list)
https://github.com/siglens/siglens/pull/673 had allowed multiple records to be ingested but it required them to be in a JSON list, which doesn't follow the Splunk documentation; see https://docs.splunk.com/Documentation/Splunk/latest/Data/FormateventsforHTTPEventCollector#Event_data
Manually tested with
```
curl -XPOST -d '{
"index": "example",
"field1": "apples",
"field2": "oranges"
}{"field1": "thing1", "field2": "thing2"}' http://localhost:8081/services/collector/event
```
I also tested sending gzipped records
=> Allow gzipped splunk ingestion of multiple records

pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/aggregations/segaggs.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/structs/segstructs.go
Now the following queries will work:
```SPL
1. * | head limit=10
2. * | head 10
3. * | search app_name="Waspsing"  | head 10
4. * | search app_name=Stadium* | stats count(*) by app_name | head 15
5. * | search app_name=* | stats count(*) by app_name, http_method | head 5
6. * | rex field=app_version "(?<major>\d+)\.(?<minor>\d).*" | stats count(*) by minor | head 2
7. * | head 132000
8. * | head 100000 | stats count(*)
9. * | search app_name="W*"  | fields app_name, batch | head 2
10. search app_name=Hyena* | fields gender, http_method, http_status | transaction gender http_method startswith=http_status=301  endswith=(http_status=404 OR http_status=500) | head 2
```
- Also resolved a bug regarding the `for loop` at processing of aggs at `rrcreader.go`.
- Tested against the UI With the …
=> fix: SPL Head Command Fix

pkg/segment/search/searchaggs.go
- Fixed the issue with search with Stats.
Now the below queries will work:
```SPL
1. * | app_name=Stadiumshake | stats count(http_status)
2. * | app_name=Stadium* | stats sum(http_status), count(http_status)
3. * | app_name=Stadium* | stats avg(http_status)
```
Tested against the UI.
=> Search stats fix

pkg/segment/tracing/handler/tracehandler.go
Pick timestamp from the latest dep graph while aggregating multiple dependency graphs.
- Tested this using the API endpoint.
=> Pick timestamp from the latest dep graph while aggregating multiple graphs

pkg/segment/aggregations/segaggs.go, pkg/segment/structs/segstructs.go
- Now `where` cmd will work without stats.
- So Now below commands will work:
```SPL
1. * | search app_name=Was* | fields address, app_name, hobby, http_status | where like(http_status, "%2%")
2. * | search app_name=Wasp* | fields address, app_name, hobby, http_status | where where match(hobby, "ing*")
3. * | search app_name=Was* | where http_status >= 400
4. * | search app_name=Was* | where like(app_name, "%could%")
5. * | search app_name="Wasp*"  | fields address, app_name, hobby, http_status  | where (http_status >= 200 AND http_status < 400) AND like(hobby, "%ing%")
``` 
- Tested against the UI by writing the SPL queries similar to the above queries.
=> Fix: Where cmd on Recs

pkg/segment/search/searchaggs.go, pkg/segment/search/searchaggs_test.go, pkg/segment/structs/segstructs.go
- The SPL Head command followed by stats was not working when we query or are given a limit less than the total segments.
- For example, the below queries will not work:
```SPL
* | head 250000 | stats count(*)
* | head 20000 | stats sum(latency)
* | head 30000 | stats sum(latency) by http_method
```
- The above queries won't work assuming that there are more segments than required because of the limit.
- Before, this function only returned the aggregations that were only part of the final segment.
- Now, this is fixed. It now stores the previous aggregations in `NodeResult` in struct and appends data to it for each segment.
- Tested the code against the UI.
- Written Tests for Stats and Stats With Group By with Size Limit in `searchaggs_test.go`
=> Fix: SPL Head command followed by Stats When querying less than total Segments

.github/workflows/develop-e2e-install.yml, pkg/config/version.go, pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/segaggs_test.go, pkg/segment/search/searchaggs.go, pkg/segment/search/searchaggs_test.go, pkg/segment/structs/segstructs.go, pkg/segment/structs/segstructs_test.go, static/css/query-builder.css, static/css/siglens.css, static/css/tracing.css, static/dependency-graph.html, static/js/date-picker.js, static/js/dependency-graph.js, static/js/log-results-grid.js, static/js/search-traces.js, static/js/service-health-overview.js, static/js/service-health.js, static/js/trace.js, static/service-health-overview.html, static/service-health.html
- Introduced a time picker on the dependency graph screen, enabling users to view aggregated dependency graphs for periods up to 30 days in the past.
- Expanded trace search capabilities to include traces up to one year old.
- Resolved an issue with the SPL `where` command, which now functions correctly with queries that do not include group by operations.
- Addressed a problem with the SPL `head` command, ensuring it works as expected with queries when followed by the stats command, even when querying fewer than total segments.
- Implemented minor UI enhancements on the tracing screen for improved user experience.
=> Release 0.1.33 

pkg/utils/httpserverutils.go
This adds some convenience functions for more succinctly blocks of error handling like
```
if err != nil {
log.Errorf("ProcessCreateLogMinionSearchRequest: could not unmarshal json body, err=%v", err)
ctx.SetStatusCode(fasthttp.StatusBadRequest)
responseBody["error"] = err.Error()
utils.WriteJsonResponse(ctx, responseBody)
return
}
```
No you can do simply
```
if err != nil {
utils.SendError(ctx, "could not unmarshal json body", "", err)
return
}
```
These functions also automatically get the name of the function (in this case `ProcessCreateLogMinionSearchRequest`) that called `SendError()` and prepend that to the emitted log message. The second string (empty in this example) is to provide more information in our internal log message that we don't want to show to the user.
Called the …
=> Add error utils

pkg/segment/writer/metrics/metricssegment.go
Fixed following error while ingesting siglens metrics with NaN value:
```ExtractOTSDBPayload payload {\\\"metric\\\":\\\"ss_segment_latency_avg_ms\\\",\\\"tags\\\":{\\\"__name__\\\":\\\"ss_segment_latency_avg_ms\\\",\\\"instance\\\":\\\"siglens:2222\\\",\\\"job\\\":\\\"siglens-metrics\\\",\\\"otel_scope_name\\\":\\\"siglens\\\",\\\"pqid\\\":\\\"18251664056736810150\\\",\\\"metric\\\":\\\"ss_segment_latency_avg_ms\\\"},\\\"timestamp\\\":1712909069675,\\\"value\\\":NaN} failed to extract payload! Unknown value type ",```
=> fix NaN error while ingesting siglens metrics

static/js/index.js, static/js/log-search.js
1. Storing indexes in cookies so that if a user reloads the page, the selected indexes are not refreshed.
2. If cookies contain indexes - use them, otherwise, select the first sorted index.
3. Removed some code related to the '*' index.
=> Save Indexes in Cookies

tools/sigclient/pkg/ingest/ingest.go
- Updated the metric ingestion URL.
- The error handling of the ingestion response will now also check the status code. 
- Tested it by ingesting it into SigLens through SigClient.
- And running the example metric queries.
=> Fix: Update the Metric Ingestion URL in SigClient

static/js/index.js
The default value in the dropdown will be the second option of the list (if available).
It can be checked by opening the `Logs` tab in incognito mode, you will see the second option is selected by default (if available)
=> fix: by default 2 option will be selected in search index dropdown

pkg/influx/writer/putmetrics_test.go, pkg/integrations/prometheus/ingest/putmetrics_test.go, pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/metrics/tagsholder.go, pkg/segment/writer/segwriter.go
- Fixed Metrics Ingestion to reject the old/duplicate timestamps per `TimeSeries`.
- Fixed overriding the first value in a `TimeSeries` block while ingesting metrics.
- Fixed flushing of Metrics Blocks that was not incrementing the `BlockNum`.
- Fixed the tests of Metrics Ingestion that is being rejected because of duplicate Timestamps.
- Extracting the timestamp from the Influx Db case while ingesting metrics in csv format.
- Fixed the tests related to Influx DB Put Metrics: Ingestion through csv.
- Tested by running the ingestion through SigClient and queries through UI.
=> Fix: Metrics Ingestion And Flushing of Metrics Blocks

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/seriesresult.go
- Set the default to `Avg` for Metrics aggregation.
- Fixed the `Avg` Aggregation for Metrics.
- Tested by ingesting a set metrics and making queries from the UI.
=> fix: Avg Aggregation case for Metrics and Set the default Metrics Aggregation as Avg

pkg/segment/results/mresults/seriesresult.go
- Fixed the count aggregation for Metrics.
- Tested by running the queries against the UI.
=> fix: count aggregation for metrics

pkg/segment/writer/metrics/meta/metricsmeta.go, pkg/segment/writer/metrics/metricssegment.go
- The Metric Names will be stored in a file when the Segment is being rotated.
- The Metric Names Bloom will be flushed when the Segment is being rotated.
- Refactored the field `mNames` to `mNamesBloom` in the `MetricsSegment` struct.
- Refactored the  field `Metrics` to `MetricSegments` in the `MetricsAndTagsHolder` struct.
- Tested by ingesting multiple metrics across segments.
=> feat: Write Metric Names into a file

pkg/segment/query/metadata/metricsmetadata.go, pkg/segment/query/metadata/metricsmetadata_test.go, pkg/segment/writer/metrics/metricssegment.go
- Added `ReadMetricsBloom` method that will read the Metrics Name Bloom File.
- Tested by adding a test case that calls the Flush metric names func and then calls the `ReadMetricsBloom` Method.
=> feat: ReadMetricsBloom

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler_test.go, pkg/segment/structs/metricsstructs.go
- Integrates the TimeSeries API with the existing Metrics Query Flow.
- Tested by calling the TimeSeries API endpoint through Postman.
=> Integrated the Metrics Query flow with new TimeSeries handler

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/reader/metrics/tagstree/tagstree_test.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/metricsresults_test.go, pkg/segment/results/mresults/tsid/tsidtracker.go, pkg/segment/segexecution.go, pkg/segment/structs/metricsstructs.go, pkg/segment/writer/metrics/tagstree.go
- Fix for working with variable tag Keys per metric.
- Also included basic formula execution.
- Added the storage and retrieval of `int64` in the tag values for metrics.
- Modified get all tag keys and values per metric api to return only a unique key value pair set.
- Tested by executing the existing test cases.
- Ingested data and ran queries by calling the api endpoints.
=> Variable Tag Keys Per Metric + Formulas.

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metricsquery.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/structs/metricsstructs.go, tools/sigclient/pkg/utils/metricsreader.go
```
api: http://localhost:5122/metrics-explorer/api/v1/timeseries
{
"start": "now-30m",
"end": "now",
"queries": [
{
"name": "a",
"query": "abs(testmetric3)",
"qlType": "promql"
}
],
"formulas": [
{
"formula": "a"
}
]
}
```
=> Feat: Add abs func support for Promql query

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/utils/segconsts.go, tools/sigclient/pkg/utils/metricsreader.go
Add log2, log10, ln funcs for promql [Promql docs](https://prometheus.io/docs/prometheus/latest/querying/functions)
Test with queries like:
- "log2(testmetric3)",
- "log10(testmetric3)"
- "ln(testmetric3)"
=> Feat: Add log2, log10, ln funcs for promql 

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/tsid/tsidtracker.go
- Now the Metrics Query will aggregate the metrics per series if group by is given.
- Else, the query will be aggregated on the Metric name and any other given tag filters.
- Tested by updating the existing test cases.
- Tested by executing the queries in the UI.
=> feat: Refactored the group processing of metrics

pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/querystatus.go, pkg/segment/query/segquery.go, pkg/segment/query/segquery_test.go
1. Lets you correctly specify whether unrotated segments should be queried, and whether rotated segments should be queried.
2. Updates the `scrollFrom` in the wsHandler each `UPDATE`, so previous logs already sent to the UI are not resent
=> Fix selecting segments

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler_test.go, pkg/integrations/prometheus/promql/metricsconsts.go, pkg/segment/query/metricsquery.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/structs/metricsstructs.go, pkg/segment/utils/segconsts.go
- Consolidate range funcs with math funcs.
- Fix Metrics Range funcs
- Verify [Rate](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate)/[Deriv](https://prometheus.io/docs/prometheus/latest/querying/functions/#deriv) processing logic
- Add irate()
- "deriv(testmetric0[10m])"
- "rate(testmetric0[5m])"
- "irate(testmetric0[5m])"
=> Fix: Rate/Deriv processing logic

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsconsts.go
&nbsp;
Fixes Unsupported node type issue, when using metrics queries with aggregate func such as: max(metric1), sum(metric1)
As I was debugging this, I checked this [document](https://pkg.go.dev/github.com/influxdata/promql/v2#Inspect) and the PromQL source code. I found that it will walk into a nil point at the end. I think the reason PromQL adds this step is because it allows us to do some post-processing after we finish traversing all the nodes. Currently, we do not need to do that, so I just return nil when it finishes traversing and walks into a nil point. But please correct me if I am wrong.
Try the queries again:
- max(metric1)
- sum(metric1)
=> Fix: promql node traversal issue

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/structs/metricsstructs.go
- Fix for get All Tag Keys and Values API.
- Also fixes the Metric Query Flow.
- Tested by executing the Queries and the API Endpoints.
=> fix: Get All tag key and values pairs for a metric name

static/component/download/download.js, static/js/download-logs.js
Earlier, filename of logs and traces export were limited between 3 to 16 characters but now the limit has been extended to 254 characters.
Fixes #851 
I have tested by exporting logs and traces with filename of 100 characters and also for 280 characters. Logs and traces exported in the former case while it produced error for the latter one.
=> fix: filename of log and traces export will be 3-254 chars

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsconsts.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/structs/metricsstructs.go, pkg/segment/utils/segconsts.go
Add promql clamp functions as mentioned in [doc](https://prometheus.io/docs/prometheus/latest/querying/functions/#clamp): clamp, clamp_max, clamp_min
- clamp(testmetric0, 1, 50)
- clamp_max(testmetric0, 10)
- clamp_min(testmetric0, 1)
=> Feat: Add Promql Clamp funcs

pkg/segment/results/mresults/metricresults.go
panic in accessing keyValue while framing promql response while querying only for metricName without label filters
=> fix: panic while framing promql response

pkg/ast/pipesearch/resultStructs.go, pkg/ast/pipesearch/wsSearchHandler.go
Add ColumnsOrder attr in query_update msg for async query
So right now, 
- The resp for all types of queries in dashboard api will contain `ColumnsOrder` attr.
- For `websocket search`, except for agg query without groupby cols. Other queries should contain `ColumnsOrder` attr.
Please notice that:
For `websocket search`, there are 2 types of query.
1. Async query (Non aggregation query):
query_update resp: will contian data we need to append to the UI, including `ColumnsOrder` attr.
query_complete resp: will only contain some statistic data, without `ColumnsOrder` attr.
2. Sync query (Aggregation query):
query_update resp: without `ColumnsOrder` attr.
query_complete resp: will contain all the data, including `ColumnsOrder` attr.
1. Non agg query:
city=Boston | fields weekday, state, …
=> Fix: Add ColumnsOrder attr in query_update msg for async query

pkg/integrations/loki/loki.go
- Fixes the Loki instant Query Time range.
- Tested by executing the queries against.
=> fix: Loki/LogQL Instant Query time range

static/js/ag-grid-seg-stats.js, static/js/dashboard-logs-results-grid.js, static/js/search.js
websocket results do not have groupByCols , instead it returns results with colNames. I removed the check for colName index in groupByCols
=> fix issue with colOrder on logs page

pkg/ast/pipesearch/searchHandler.go, pkg/segment/aggregations/segaggs.go, pkg/segment/query/querystatus.go, pkg/segment/results/segresults/segresults.go, pkg/segment/structs/evaluationstructs.go
- Fix the bug where the dashboard API's(http://localhost:5122/api/search/-1) groupByCols were not updated after using the `rename cmd`
- Remove some redundant code
Test with the queries below:
1. Rename to a str:
city=Boston | rename gg AS city
city=Boston | fields city, country | rename city AS "test"
city=Boston | stats count AS Count BY http_status, http_method | rename http_method AS "test"
city=Boston | stats count AS Count BY http_status, http_method | rename Count AS "test"
2. Regex
city=Boston | rename c*y AS sig*scalr
city=Boston | fields app_name, app_version | rename app* AS start*end
city=Boston | stats count AS Count BY http_status, http_method | rename ht* AS A*
city=Boston | stats count AS Count BY http_status, http_method | rename C* AS A*
//Multiple wildcards
city=Boston …
=> Fix: Dashboard API's groupByCols were not updated after using the rename cmd

pkg/integrations/prometheus/ingest/putmetrics.go, pkg/segment/query/metricsquery.go, pkg/segment/writer/metrics/metricssegment.go
Fixes #887 
Fixes #886 
- Tested by executing the API endpoints.
- And ingesting with empty metric name.
=> fix: metric name in tags and empty metric names

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsconsts.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/utils/segconsts.go
Add a part of <aggregation>_over_time() functions: https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time
avg_over_time(range-vector): the average value of all points in the specified interval.
min_over_time(range-vector): the minimum value of all points in the specified interval.
max_over_time(range-vector): the maximum value of all points in the specified interval.
sum_over_time(range-vector): the sum of all values in the specified interval.
count_over_time(range-vector): the count of all values in the specified interval.
=> Feat: Add promql funcs <aggregation>_over_time()

pkg/segment/writer/metrics/tagsholder.go, pkg/segment/writer/metrics/tagsholder_test.go, pkg/segment/writer/segwriter.go
- Fixes the issue of TagsHolder concurrent access.
- Removed the use of pools.
- Tested by running the script that simultaneous try to ingest 1000 metrics.
=> fix: tagsholder panic

.circleci/config.yml, cicd/promql_test.csv, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/promqlquery.go, tools/sigclient/pkg/utils/calculation.go
This PR adds code to run queries against the promQL API and lets you verify the result against the expected result if a particular query should fail or succeed.
To test using queries from a file using sigclient run the below command:
`go run main.go query promql -d http://localhost:5122/promql/api/v1/query_range -f ../../cicd/promql_test.csv`
To test a single query run the below command:
`go run main.go query promql -d http://localhost:5122/promql/api/v1/query_range -q "testmetric0 start:1716239444 end:1716239544"`
the `-q` flag accepts the query along with the start and end epoch in seconds in this format - `"<query> start:<startEpoch> end:<endEpoch>"`
- Tested the above commands with different queries
=> Promql query support for sigclient

pkg/segment/results/mresults/metricresults.go, pkg/segment/structs/metricsstructs.go
There was a bug in the code while framing the promql response that was returning only the last timestamp in case of range queries. This fix will return all the timestamps with its values within that range. Also updated the json response to have `values` instead of `value` as `values` is working fine for both instant and range queries.
- Tested against both instant and range queries on grafana
=> Fix: Return all values with timestamps for promql query APIs

static/css/query-builder.css, static/css/siglens.css, static/index.html, static/js/common.js, static/js/dashboard.js, static/js/edit-panel-screen.js, static/js/event-handlers.js, static/js/index.js, static/js/log-search.js, static/js/search.js
=> logsearch page -Wildcard and autocomplete support for index Search

cicd/metrics_test.csv, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsconsts.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/utils/segconsts.go
Add promql funcs as below:
- quantile_over_time(scalar, range-vector): the φ-quantile (0 ≤ φ ≤ 1) of the values in the specified interval.
- stddev_over_time(range-vector): the population standard deviation of the values in the specified interval.
- stdvar_over_time(range-vector): the population standard variance of the values in the specified interval.
- last_over_time(range-vector): the most recent point value in the specified interval.
- present_over_time(range-vector): the value 1 for any series in the specified interval.
=> Feat: Promql <aggregation>_over_time funcs Completion

static/js/log-results-grid.js
After Andrew's [PR](https://github.com/siglens/siglens/pull/938) the error is fixed , but we sometimes see the warning.
Added `isFetching` flag to prevent multiple concurrent requests so that only one request is being processed at a time.
=> Added flag to prevent multiple simultaneous fetches

pkg/segment/query/querystatus.go, pkg/segment/segexecution.go, pkg/segment/writer/unrotatedquery.go
Fix the issue where running a range query like `search 200` sometimes does not return results correctly. I believe this can also solve some CI/CD test issues at the same time.
=> Fix: Unrotated segment range checking logic

cicd/metrics_test.csv, pkg/common/dtypeutils/dtypeutils.go
Floating-point operations can sometimes lead to precision loss, so the tolerance value has been increased.
=> Fix: Increase tolerance for approximate equality in metrics test

static/js/available-fields.js, static/js/log-results-grid.js
- This PR fixes an issue where user selections to unselect all available fields were not being respected in subsequent searches. Now, when all fields are unselected, only the timestamps column will be shown in the search results.
- Removed the timestamps from the logs columns, as it is already shown separately.
=> Fix : Available Fields

cicd/metrics_test.csv, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/tests/metricsresults_test.go, pkg/segment/segexecution.go, pkg/segment/structs/metricsstructs.go
Add Comparison binary operators
The following binary comparison operators exist in Prometheus: https://prometheus.io/docs/prometheus/latest/querying/operators/#comparison-binary-operators
```
== (equal)
!= (not-equal)
> (greater-than)
< (less-than)
>= (greater-or-equal)
<= (less-or-equal)
```
Test with these queries:
```
1. >
(testmetric0) > 132
132 > (testmetric0)
2. >=
(testmetric6) >= 666
(testmetric6) >= 667
667 >= (testmetric6)
3. <
131 < (testmetric0)
(testmetric0) < 10
(testmetric0) < 1000
4. <=
667 <= (testmetric6)
(testmetric6) <= 668
5. ==
(testmetric6) === 666
6. !=
(testmetric6) != 66
(testmetric0) + (testmetric0)
(testmetric0) - (testmetric0)
(testmetric0) * (testmetric0)
(testmetric0) / (testmetric0)
(testmetric0) > (testmetric0)
(testmetric0) >= (testmetric0)
(testmetric0) …
```
=> Feat: Add promql comparison operators

cmd/startup/startup.go, pkg/common/fileutils/fileutils.go
This was already printed to stdout. Now it's also included in the log file.
The log file contains this:
```
INFO[2024-05-29 09:09:36] Initialized FD limiter with 86016 as max number of open files
```
And this was written to stdout:
```
INFO[0000] Initialized FD limiter with 86016 as max number of open files
```
=> Log max allowed open files

pkg/config/config.go, pkg/segment/writer/metrics/metricssegment.go
- Updated the `config.go` to set the default Memory Threshold to 50% for memory < 8GB.
=> Set the memory threshold to 50% by default for Memory < 8GB

pkg/segment/writer/suffix/suffix.go
- Fixes the Error log line for Suffix Functions.
=> fix: Error log line msg for Suffix Files

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/metricsbench/metrics_bench.go
- `metricsbench` CMD in SigClient; Let's you send some predefined queries to the given destination Host for the `timeseries` API for all the available time periods.
Usage:
```
go run main.go metricsbench -d http://18.219.34.37:5122 
```
- Tested by executing above command.
=> feat: metric bench command added

static/cluster-stats.html, static/css/siglens.css, static/js/cluster-stats.js
UI changes for cluster stats page - display separate containers for logs and metrics and display respective stats table after each container. 
- Have a global time picker for all graphs  on the cluster stats page
- Time picker is only applied for the graphs and the table shows details from beginning of time.
- Tested time picker with different windows.
- No errors on console.
=> Cluster stats page UI changes

static/css/siglens.css, static/js/all-alerts.js, static/js/common.js, static/js/contacts.js, static/js/dashboard-logs-results-grid.js, static/js/dashboards-home.js, static/js/log-results-grid.js, static/js/service-health.js
In the PR, the descending is changed as it will reflect as `Z to A down arrow`
I have verified by going through every table which has this sorting option.
=> fix: descending icon of table sorting option

pkg/health/clusterStatsHandler.go, pkg/usageStats/stats.go, static/cluster-stats.html
Get stats by minute intervals if requested time window is less than 24 hours.
- Tested by calling the API with various time intervals like past1h,2h,4h etc.. 
- Verified that the aggregated results of each window matches the one that is sent for hourly granularity and daily granularity.
=> Cluster stats time picker granularity

pkg/segment/query/metadata/tsmeta.go, pkg/segment/search/metricssearch.go, pkg/segment/structs/metricsstructs.go, pkg/segment/writer/metrics/metricssegment.go
- Concurrent Searches managed by Weighted Semaphore is set to 1.
- Block Worked Parallelism for Metrics Search is also set to 1.
- These changes were made to avoid high memory usage after running bench tests.
=> Concurrent searched and block parallelism set to 1

pkg/health/clusterStatsHandler.go
This PR fixes a bug where the cluster stats API would fail to respond if the incoming bytes were 0 for logs or metrics and replace the storage saved with NaN and hence fail marshaling of json
- Tested by ingesting just metrics and both metrics and logs.
=> Fix: Check if incoming bytes is greater than 0 for cluster stats API

static/cluster-stats.html
This is a simple fix to correct the vertical alignment of the time picker on the cluster-stats.html page
Fixes #987  (link all the GitHub issues this addresses)
Changes are cosmetic, i.e. only a single html file is changed.
I have verified the expected behavior: 
Additionally, I also ran `make all` and `make pr`
=> bug-fix #987 Fix time picker alignment on MyOrg cluster status page

static/js/log-results-grid.js
This change adds a copy icon to the `textarea` of the popup of JSON Viewer.
The copy icon is copying contents to the clipboard.
=> feat: add copy icon in the JSON box

pkg/segment/query/metadata/tsmeta.go, pkg/segment/reader/metrics/series/seriesreader.go, pkg/segment/writer/metrics/metricssegment.go
Replaces sync.Pool with our own pool, since we're using large buffers and sync.Pool doesn't give guarantees about when it will free items, or that it will use an existing item if available rather than create a new item.
Ingested 800 million metric datapoints
```
go run main.go ingest metrics -d http://localhost:8081/otsdb -t 800_000_000 -m 8 -p 10
```
And then ran metric benchmarks:
```
go run main.go metricsbench -d http://localhost:5122 -n 50
```
=> Self managed pool for reading metrics files

pkg/common/dtypeutils/dtypeutils.go
- Fixes the issue with Wildcard Search. 
- Currently a search like `app_name=Be*` is converted to `*Be*`.
- Now the search is anchored at both ends, making above search as `^Be.*$`
- Tested by executing similar regex queries through the UI.
=> fix: anchor wildcard search

pkg/segment/search/conditioncheck.go, pkg/segment/writer/rawchecker.go
If we have two indices, `ind-0` and `ind-1`, `ind-0` index contains `http_status` while `ind-1` index contains `http_method`
In the past, If the filter query uses regex(E.g. http_status=2*), it will give us an error as shown below, since `ind-1` does not contain field `http_status`
After this pr, query should just return rows meet the condition without giving error
=> Fix: Dual index bug

pkg/config/config_test.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/structs/metricsstructs.go
Using the for regex operator shifted the flow to iterate over all the values of the tag similar to what happens in case of *.
Checking the tagRawValue with the tagVal (regex expression parsed correctly by the promql parser and returning the expression as a string). Regex check performed between these two is fully anchored similar to what [promql](https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors) uses.
Finally calling BulkAdd to add all TSIDs that successfully matched with the regex to tracker.
Tested various regex expression to check the correctness below mentioned are the queries and …
=> Regex search support for Tag filters

pkg/segment/results/mresults/metricresults.go
Setting default metric name of mQuery does not work with multiple metric based queries. Need to set the metric name according to the grpId received in result, extract the proper metric name and set it for the PromQL response.
Found this bug during query verification.
Sample query for testing
`avg({__name__=~'(usage_user|usage_system|usage_idle|usage_nice|usage_iowait|usage_irq|usage_softirq|usage_steal|usage_guest|usage_guest_nice)'}) by (__name__, hostname)`
Sample API:
`http://localhost:5122/promql/api/v1/query_range?query=avg({__name__=~'(usage_user|usage_system|usage_idle|usage_nice|usage_iowait|usage_irq|usage_softirq|us …
=> Fix for same metric name in promql range query result

pkg/integrations/prometheus/promql/metricsconsts.go, static/js/metrics-explorer.js
Add prompt messages for metrics-explorer page
However, we still do not support using queries that need extra parameters.
E.g: 
- topk(1, metric0)
- present_over_time(avg (system.disk.used[5m]))
=> Add prompt messages for metrics-explorer page

pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/structs/segstructs.go
- Add parser and tests for one of the Multi Value Stand alone SPL Commands: `makemv`
SPL Document reference: https://docs.splunk.com/Documentation/SplunkCloud/9.1.2312/SearchReference/Makemv
- Added test cases that test the parser with various `makemv` commands.
=> feat: Add parser and tests for SPL command: makemv

cicd/metrics_test.csv, pkg/segment/query/metricsquery.go, tools/sigclient/pkg/query/otsdbquery.go
- Updated `otsbdquery.go` with the support to verify regex queries.
- Updated `metrics_test.csv` with some of the regex queries.
- Tested by running ingestion command in the circle ci config.
- And run the `metric_test.csv` query command.
=> feat: Added support for Metrics regex query verification

static/css/dashboard.css, static/css/siglens.css, static/dashboard.html, static/js/common.js, static/js/dashboard-from-logs.js, static/js/dashboard.js, static/js/dashboards-home.js, static/js/edit-panel-screen.js, static/js/event-handlers.js
- Default dashboards cannot be edited. 
- The "Add Panel" button and widget options have been removed, as well as the "Save Dashboard" button from the dashboard screen. 
- From the dashboard settings page, the "Discard" and "Save" buttons have been removed. 
- On the panel, the edit, clone, and delete icons have been removed, leaving only the view option. Also, panels are not resizable or draggable. 
- Changing the time range will not save the dashboards.
These changes apply only to default dashboards.
=> Fix: Prevent Editing of Default Dashboards

pkg/config/version.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler_test.go
- The Metric Timeseries API containing single character as query name, is causing issues when building the query.
Example of this:
```
{
"start": "now-1h",
"end": "now",
"queries": [
{
"name": "a",
"query": "avg by (car_type) (testmetric0{car_type=\"Passenger car heavy\"})",
"qlType": "promql"
},
{
"name": "b",
"query": "avg by (car_type) (testmetric0{car_type=\"Passenger car heavy\"})",
"qlType": "promql"
}
],
"formulas": [
{
"formula": "a+b"
}
]
}
``` 
- Now this fixed through applying a placeholder template string first and then the actual query value to build the final search query.
- Tested by adding test cases for `buildMetricQueryFromFormulaAndQueries` Method.
=> fix: queries with formulas containing single char names

static/css/dashboard.css, static/dashboard.html, static/js/dashboard.js
If no panels the popup shows up -
If panels are present then the popup does not shows up -
Fixes #977
=> Fix : Add Chart Type Popup (Dashboard)

static/css/query-builder.css, static/js/log-search.js, static/js/search.js
Since for Aggs and SegStats queries we do not show any available fields options or allow changing the view, I removed the dropdown and the table view option for these types of queries.
=> Hide Available Fields Dropdown and Table View for `aggs` and `segstats` query

static/js/event-handlers.js, static/js/search.js
1. In wrap line view, \n now correctly moves to the next line.
2. Fixed an issue where a single row result did not display correctly when switching from wrap to single view.
Previously -
=> Fix: Proper Rendering of Line Breaks in Wrap View

pkg/ast/pipesearch/searchQueryParser.go
TimeRange would come from parser we do not need to set it using timepicker if its present.
```
Inserted data at Jun 19th, 2024 @ 18:55:35
Inserted data at Jun 19th, 2024 @ 19:19:19
address = "4852 Lake Ridge port, Santa Ana, Nebraska 13548" | earliest=04/19/2022:00:00:00 latest=04/27/2022:00:00:00
address = "4852 Lake Ridge port, Santa Ana, Nebraska 13548" | earliest=06/19/2024:18:55:00 latest=06/19/2024:18:56:00
address = "4852 Lake Ridge port, Santa Ana, Nebraska 13548" | earliest=06/19/2024:18:55:36 latest=06/19/2024:18:56:00
address = "4852 Lake Ridge port, Santa Ana, Nebraska 13548" | earliest=06/19/2024:19:19:18 …
```
=> Fix: Prevent Overriding of boolNode.TimeRange when not nil

API_README.md, pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/alerts/alertsqlite/alerts_sqlite.go, pkg/alerts/alertutils/alertutils.go, pkg/server/query/server.go, static/js/all-alerts.js
- Updated the Alert state transition logic based on the Evaluations across the Eval window.
- State Transition Rules:
- `Normal` to `Pending`: When an alert condition is matched.
- `Pending` to `Firing`: When an alert condition is matched for all the last (Interval Count) Evaluations.
- `Firing` to `Normal` / `Pending` to `Normal`: When an alert condition is not matched.
- `NotificationHandler` will be called to send an alert notification when:
- The Alert is in `Firing` state or transitioned from `Pending` to `Firing` state.
- ~~The Alert is Transitioned from `Firing` to `Normal` state (to let user know that the alert state reverted to Normal).~~
- **UPDATE:** The Alert is in `Normal` state.
**NOTE**: The implementation of cooldown period on the `NotificationHandler` is expected to …
=> feat: Updated the logic for Alert State Transition during Alert Evaluation based on Alert Eval Window

pkg/alerts/alertsqlite/alerts_sqlite.go
- Removes the restriction to update the `AlertType` for an Alert.
=> refac: Allow update of Alert type for an Alert

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsqlite/alerts_sqlite.go
- Cleaned up the error logs and all the API handlers will return informational Error messages.
=> fix: Alerting: Error logs and return message cleanup

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/notificationHandler.go
Fixes #1194 
I ran the server locally and tried with the "Test" button on the "Contact Points" page, and verified that the color of the notification changed depending on the state.
Alert with a Firing state:
Alert with a Normal state:
=> Alert notifications on Slack computes color based on the alert state

pkg/alerts/alertsHandler/cronJobHandler.go, pkg/ast/pipesearch/searchHandler.go, static/js/alert.js
- Fixed the case where Measure Results exists but the value is nil. The value is considered as `0`.
Fixes #1195 #1197 
- Tested by creating a similar query that results in Measure Val as Nil. And verified that the alert is being triggered.
=> fix: Measure val nil for Alerting

pkg/alerts/alertsHandler/notificationHandler.go
Improve slack alert notification:
- Reduce text
- Move alert name to the top with strong text
- Make the date more readable and move it to the bottom
**Old alert notification:**
**New alert notification:**
**Old alert recovery notification:**
**New alert recovery notification:**
**Old test notification:**
**New test notification:**
Tested the notification locally.
=> Improve slack alert notification

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/alerts/alerts_loadtest.go, tools/sigclient/pkg/alerts/alerts_loadtest_vector.yaml
- Removed Auto Cleanup after a LoadTest when succeeded or failed due to an error.
- Added it as a optional command argument
- The test also will not exit when timeout occurs.
- Tested it by running the command with 10 Alerts.
=> feat: remove automatic cleanup and added it as a command option

docker-compose.yml, install.sh
- Fixes the removal of `siglens.db` when docker container is removed.
- This also fixes for upgrading to a new version by running the `install.sh` script.
- Tested by running the install script and running the commands: `docker-compose down` and `docker-compose up -d`.
- Verified that the Alerts data is being persisted.
=> fix: deletion of siglens.db during recreation of the docker container 

cicd/ingest.csv, cicd/restart.csv, pkg/segment/structs/evaluationstructs.go
This function can take in a string literal or a field value. Here we are just assuming user will pass a field, when a string literal is passed the program crashes due to segfault because self.Val does not have a NumericExpr.
app_name = Bracecould | eval masked_email=replace("xyz@abc.com", "^([^@]+)@", "xxxxx@") | fields email, masked_email
app_name = Bracecould | eval email = "abc@xyz.com" | fields email | eval masked_email=replace(email, "^([^@]+)@", "xxxxx@") | fields email, masked_email
=> Bug: SPL Eval subcommand replace

pkg/segment/writer/agiletreewriter.go
This fixes a panic that sometimes occurs when encoding the AgileAggs tree.
The issue was that we were estimating (not calculating) how large of a buffer we needed, and then assuming that it was sufficient; sometimes we underestimated, and then got a panic when we tried to write too far.
This changes that so we just use bufio to handle all the details of buffering writing to the file for us, and allows us to not have to estimate the buffer size.
I was able to reproduce the bug by running with `pqsEnabled: true` in the config, forcing the estimator function to return a low value like 50, and then starting siglens and running the following
```
"tableName": "ind-0",
"groupByColumns": ["http_method", "weekday"],
"measureColumns": ["http_status"]
}' …
```
=> Fix AgileAggs panic during encoding

pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/segaggs_test.go
Support for negative values for log span in bin command.
=> Bug: Handle negative value for log span for SPL Bin Command

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/alerts/alertutils/alertutils.go, pkg/ast/pipesearch/resultStructs.go, pkg/ast/pipesearch/searchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler_test.go, pkg/segment/structs/segstructs.go, pkg/segment/utils/numberutils.go
- Fixed the Alert logs Query so that:
- It checks for all of the series in a `Group By` request.
-  And now it will also work for queries with nested Group By.
**NOTE:** As of now I am rejecting the query with Multiple Measure Columns even with `Eval` or `where` condition set. But the queries like this with Multiple Columns will still work, if the they are followed by a stats query at the end like below.
```
* | rex field=app_version "(?<major>\d+)\.(?<minor>\d).*" 
| stats count(*) as count, sum(major) as sum_major by minor 
| where minor < sum_major 
| stats count(*) as count
```
- This PR also includes the building and sending the Metrics Query Link while sending an Alert Notification.
- Tested by executing different types of Logs Queries and verified that the Alert Notification is …
=> feat: fixed Alert queries for all types of Logs queries

static/js/metrics-explorer.js
- Changed the function that would actually render the metrics query from the url in the `populateMetricsQueryElement` function.
=> fix: Rendering of Metric Query from the URL

pkg/segment/utils/segconsts.go, pkg/segment/utils/segutils.go
- This Adds a new type for `DtypeEnclosure` that can be used for Multi value functions.
=> feat: Added new DtypeVal []string for MultiValue functions

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, pkg/segment/structs/evaluationstructs.go
Updated the parser for `mvfind`, as the previous parsing logic was inconsistent with other multi-value commands, and fields were being parsed in valueList in the previous version
https://docs.splunk.com/Documentation/SCS/current/SearchReference/MultivalueEvalFunctions#mvfind.28.26lt.3Bmv.26gt.3B.2C_.26lt.3Bregex.26gt.3B.29
=> Update parser for eval mvfind 

pkg/alerts/alertsHandler/notificationHandler.go, pkg/ast/pipesearch/searchHandler.go
- Added closing of webhook request, once an Alert Notification is sent.
- Without closing the request causes the number of file descriptors to keep increasing and eventually it crosses the `os` limits and will not send the requests.
- Tested before making this fix by running the alerts load-test client and the error of sending request would occur approximately around 54th minute for 1000 Alerts and also verified that the number of open files kept increasing over time. 
- Tested after making the fix by running the alerts load-test client and it has been running without any issues for the past 170 minutes for 2000 Alerts. I have verified that the number of open files also stayed consistent with the value that was at the start of SigLens server and before starting the client.
=> fix: Close Webhook Requests After sending an Alert Notification

pkg/alerts/alertsqlite/alerts_sqlite.go
- Fixes the issue with the update or deletion of Labels in an Alert.
- Refactored the `GetAllAlerts` and `GetAlert` method to update the Alert so that the `QueryParams` will be encode to `base64` and stored in the db, if it is already not in `base64` format.
- Tested by updating the Labels in an Alert.
- Tested by verifying that the Alerts are being displayed in the UI.
=> fix: Updating of Alerting Labels

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/integrations/prometheus/promql/metricsSearchHandler_test.go
- Fixes the issue of building queries through formulas, for fomula's like this: `atan(abs(ceil(123 * a)))`
- Tested by executing queries through postman.
- Tested by updating the unit test case.
=> fix: building of PromQL Metrics query from formulas

pkg/segment/tracing/structs/tracestruct.go, pkg/segment/tracing/utils/lineartimefinding.go, pkg/segment/tracing/utils/lineartimefinding_test.go
- FindPercentileData function no longer returns a uint64, and instead a float64
- When a non-integer index is found with a given percentile, it now calculates the weight of the index after and before it and returns that, instead of rounding down the index
- Fixed minor calculation error when calculating index: ``float64(percentile*(len(arr)-1)) / float64(100)`` instead of ``float64(percentile*(len(arr))) / float64(100)``
- Changed expected test results to match new behavior and added one new test
- Changed struct RedMetrics' P50, P90, P95 and P99 variable types to match new FindPercentileData return type
Fixes #1030 
I compared the results given by the tests with percentile calculation of the arrays with outside tools (such as online calculators).
Before marking your pull request as ready …
=> Fix #1030: Linearly interpolate percentile results

static/js/download-logs.js, static/js/metrics-cardinality.js, static/js/navbar.js
1.Metrics Cardinality - Add sorting icons to all columns in all metrics cardinality table
2.the city name is not saved correctly. when performing a query such as * | stats count(city) BY city, the downloaded results do not include the city name.
=> solved 'Download Results' Does Not Save City Name and metric cardinality sort icon

pkg/segment/query/segquery.go
Fixes an issue where we could send aggregation results without waiting for all of them, so the result could be wrong.
The only other call of this `Wait()` function is at https://github.com/siglens/siglens/blob/develop/pkg/segment/query/segquery.go#L223 and I believe the placement of that one is already correct.
Tests continue to pass
=> Wait for all results before returning aggregations

pkg/health/clusterStatsHandler.go, pkg/otlp/otlp.go, pkg/segment/tracing/handler/tracehandler.go, pkg/usageStats/stats.go, pkg/utils/httpserverutils.go
Update usagestats to return TraceSpanCount and TraceBytesCount in cluster stats APIs in addition to metric and logs.
- Ingested traces and verified the traceSpanCount in cluster stats and cluster ingest stats APIs.
=> Update usagestats to store tracing related details and Integrate it in cluster stats APIs

pkg/integrations/prometheus/promql/parser.go, pkg/integrations/prometheus/promql/parser_test.go
- Now the PromQL Parser will handle constant scalar values as Queries. Example queries like: `1`, `1000`, etc.
- Added a new unit test case for the parser.
- Tested by executing the TimeSeries API through Postman.
=> feat: Added support constant value in metrics PromQL Parser

pkg/alerts/alertsHandler/cronJobHandler.go, pkg/alerts/alertsHandler/notificationHandler.go, pkg/utils/httpserverutils.go
- Now the Query results Link or a URL that is in the Message set by the user will render as Buttons in the Slack Notification message.
- Tested by creating alert with a link in the message and verified that both Query Results Link and the Message are rendered as buttons.
This is how the Message looks:
=> feat: added support rendering buttons for URLs in Slack Alert Notifications

static/alert.html, static/css/dashboard.css, static/css/metrics-explorer.css, static/css/siglens.css, static/js/alert.js, static/js/dashboard-from-logs-metrics.js, static/js/metrics-explorer.js, static/metrics-explorer.html
1. Fix the issue of double rendering of the metrics graph when clicking on the URL sent in the alert message.
2. Add better styling to the tooltip on the Alerts screen if logs, metrics, or contact points are empty, and ensure it scrolls to the point where the tooltip is shown.
3. Remove the upper navbar from the alerting screen.
=> Fix : Double rendering of metrics graph and Alerting UI

pkg/utils/logutils.go
We often want to log and return an error, so we have error handling like this:
```
if someCondition {
err := fmt.Errorf("myFunc: failed to do foo using bar; err=%v", err)
log.Errorf(err.Error())
return err
}
```
With the new util we can just do:
```
if someCondition {
return utils.TeeErrorf("myFunc: failed to do foo using bar; err=%v", err)
}
```
We could potentially rename this util to something more verbose like `LogAndReturnErrorf`. I went with `TeeErrorf` (like the unix `tee` command) because it's shorter and if we frequently use this util throughout the codebase, everyone should be able to remember what it does. But I'm open to name change suggestions
Before marking your pull request as ready for review, …
=> Add util to log and return an error

static/js/ag-grid-seg-stats.js, static/js/dashboard-logs-results-grid.js
Previously, queries like `app_name=Bracecould | stats sum(eval(http_status > 301.1))` or `app_name=Bracecould | stats sum(eval(http_status > 301.1)) as sum_http_status`  were not working. The issue was that special characters like `.` were not being handled properly by the ag-grid. Now, the change will replace any special character with an underscore and then do the comparison so it works correctly.
Fix the issue on both alert and dashboards screen.
=> Fix : SegStats Query with Float Value Does Not Display Correctly

cicd/ingest.csv, cicd/restart.csv, pkg/segment/aggregations/segaggs.go, pkg/segment/aggregations/segaggs_test.go
https://docs.splunk.com/Documentation/Splunk/9.2.2/SearchReference/Mvexpand
- `city=Boston 
| eval names="Frank,Grace,Heidi,Ivan"
| makemv delim="," names 
| mvexpand names
`
- `city=Boston 
| eval names="Frank,Grace,Heidi,Ivan"
| makemv delim="," names 
| mvexpand names limit=2
`
- `city=Boston 
| eval names="Frank,Grace,Heidi,Ivan"
| eval cities="Boston, Chicago, Miami"
| makemv delim="," cities | mvexpand cities
`
- `city=Boston 
| eval names="Frank,Grace,Heidi,Ivan"
| eval cities="Boston, Chicago, Miami"
| makemv delim="," cities | mvexpand cities limit=2`
=> Add implementation for mvexpand

.gitignore, pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/cronJobHandler.go, pkg/alerts/alertsHandler/notificationHandler.go, pkg/alerts/alertsqlite/alerts_sqlite.go
- Fixes the database is locked issue when updating the Alert state and last sent notification time.
- This fix includes: 
- Enabling `WAL` for SQLite and setting a busy timeout wait of `5000` ms. The busy timeout is for the scenarios where the database is locked for a relatively small time. The DB operation will wait for the set time before throwing a database is locked error.
- Setting retry for 5 times with increasing delays before a retry.
- This fix seems to work perfectly fine after testing on my local device with 2000 Alerts.
- In future, we may need to do the updates in batches if this not work for more work loads. At that time we can use `chan` to collect the Alerts data and call update every set interval ms.
- Tested by running alerts load-test up to 2000 Alerts per Minute.
=> fix: database is locked issue in Alerting

pkg/alerts/alertsHandler/notificationHandler.go
- Corrects the rendering of the button for a text.
- However, even when a notification is sent as the alert state is updated to `Normal`, the button will still be rendered if a `URL` is provided in the alert message.
Fixes #1358 
- Tested by triggering Alert Notifications with URL and with sample text as Alert Messages.
- Verified that the button is not rendering for text messages.
=> fix: issue of rendering button for a text message in Alerting Notifications through Slack

cicd/sample_log_dataset_queries.csv
We recently fixed our implementation for queries when there's an `eval` inside `stats` for Splunk QL. However, we didn't update all our automated testing with the new version, so the `develop-e2e-install.yml` script was failing. This fixes it.
Later, we might want to use the same dataset for testing this as we do for our normal CICD checks, so that we can just use ingest.csv here and delete sample_log_dataset_queries.csv
Ran `install.sh` to install with docker (with the sample dataset), and ran 
```
go run main.go query esbulk -d http://localhost:5122 -f ../../cicd/sample_log_dataset_queries.csv
```
from sigclient. Now those tests all pass
=> Fix incorrect automated tests

static/js/edit-panel-screen.js, static/js/metrics-explorer.js
Fix for issue - When editing metrics queries or formulas, on the panel overview the changes were not reflected correctly. Switching back to edit mode or using the time picker reverted the panel to its previously saved state, removing all recent edits.
=> Fix - Panel Overview and Time-picker of Metrics Panels

pkg/utils/debugutils.go
Add some utils for debugging the flow of functions, and allows you to log extra relevant info. These functions are intended to be used just while debugging.
For example, at the top of the function you can add:
```
utils.TraceEnter(fmt.Sprintf("len recs: %v", len(recs)))
defer utils.TraceExit(func() string { return fmt.Sprintf("len recs: %v", len(recs)) })
```
Then when that function is called, you'll get something like:
```
Entering performAggOnResult (segaggs.go:183) from PostQueryBucketCleaning at segaggs.go:146; len recs: 1000
```
And when the function exits you'll see:
```
Exiting PostQueryBucketCleaning at segaggs.go:162; len recs: 2000
```
Also the the line number it mentions here (segaggs.go:162), is the exact line number of the `return` that got triggered, so if the function has …
=> Add utils for debugging

pkg/health/clusterStatsHandler.go
Fixes a bug where if an index only has unrotated data, the stats on MyOrg doesn't show any data for that index (and the unrotated data is not included in the total amount of ingested data).
Manual testing:
1. Ingest 100k records into 10 indexes
2. Go to MyOrg and verify the correct stats are there
3. Restart siglens to force rotation
4. Check MyOrg again (nothing should change)
5. Ingest another 100k records
6. Check MyOrg again (now there's twice the data)
=> Fix ingestion stats bug for unrotated-only index

pkg/segment/reader/record/rrcreader.go
Earlier for non-search events like gentimes, etc. fields command was erroring out due to nil map for nodeResult.ColumnsOrder at this [line](https://github.com/siglens/siglens/blob/a5bda9c262fe5e30552d62355eee5fb0f0c2ebf2/pkg/segment/aggregations/segaggs.go#L834).
nodeResult.ColumnsOrder must be initialized like over [here](https://github.com/siglens/siglens/blob/a5bda9c262fe5e30552d62355eee5fb0f0c2ebf2/pkg/segment/reader/record/rrcreader.go#L216).
```
| gentimes start=-2 increment=5m | fields starttime
```
=> Bug Fix fields command after generating commands.

pkg/systemConfig/systemconfig.go
We were using the fixed root path location to find the disk usage. Use config.GetDataPath() to identify where the data directory. disk.Usage will then resolve to the correct disk/partition path and show the usage for that disk and not the default root disk usage.
Created a 60 GB partition on mac and ran siglens from that directory. In the previous case it was showing around 400 GB which is the size of the root partition. After this change its showing around 55 GB which is the size of the newly created disk partition from where siglens is running.
Previously it was showing this
Before marking your pull request as ready for …
=> Fix: Display correct disk usage

static/js/cluster-stats.js
Display segment count along with other stats for logs and traces
=> UI changes to display segment count on cluster stats screen

pkg/segment/query/metadata/segmentmicroindex.go, pkg/segment/writer/segmetareader.go, pkg/segment/writer/segwriter.go, tools/sigclient/pkg/alerts/alerts.go
- Refactored `smrLock` to use `RWMutex` instead of `Mutex`. 
- Changed all the read functions to use `RLock()` instead of `Lock()`.
- This also made the `clusterStats` endpoint to load the data faster.
- Fixed an issue with `nil pointer` error in `segmentmicroindex` while getting the `CMIsForBlock`.  
- All the tests passed.
- Verified that the cluster stats is showing correctly and the queries are working.
=> refac: Refactored smrLock to use `RWMutex`

pkg/segment/structs/segstructs.go, pkg/segment/structs/segstructs_test.go
Cleanup for multiple segments was not happening properly cause postQueryBucketCleaning was not being called as hasQueryAggregatorBlock was returning false for second or later segments if the rows were added. Due, to this, the left-out rows were just getting added to the result.
This condition was added from the earlier hasQueryAggregator block method.
HasQueryAggregatorBlock now returns true in all cases when there is a headRequest, so that either performMaxRows or performConditionalHead is always called.
The issue is only present for performMaxRows, performConditionalHead is working fine as expected.
For multiple …
=> Fix: Multiple segment/index Head issue

cicd/ingest.csv, pkg/segment/structs/segstructs.go
When specific query is where the GetSortLimit method fails. After the qa.HasSortBlock fails there is no nil check for query aggregator. Added the check to prevent seg fault.
nodeResult.NextQueryAgg will not be set and will come up as [nil](https://github.com/siglens/siglens/blob/239c57ac284c608db219d02a533173c7f412794a/pkg/segment/aggregations/segaggs.go#L144) because len of recs is zero for the case where condition returns 0 records before stats.
Updated the head queries that were giving inconsistent results due to different ingestion order.
Tested the queries manually as well by running the ingest.csv
Before marking your …
=> Bug: Panicking on certain queries

pkg/segment/query/pqs/pqs.go
Avoid using pqs query flow if pqs is disabled even if pqmr file is present
- Tested by enabling PQS, running a query and then disabling PQS. Verified that the code follows the rawSearch query flow for the same query instead of the PQS query flow, even though the PQMR file was present.
=> Avoid using pqs query flow if pqs is disabled even if pqmr file is present

cicd/ingest.csv, pkg/ast/pipesearch/searchQueryParser.go, pkg/segment/aggregations/segaggs.go, pkg/segment/results/segresults/segresults.go
Setup
Upon ingesting the same amount of data across multiple indexes as given below
```
go run main.go ingest esbulk -n 10 -g benchmark -d http://localhost:8081/elastic -t 100_000
go run main.go query esbulk -d http://localhost:5122/ -f ../../cicd/ingest.csv
```
These 8 queries were failing. The rest of the queries were tested for 50+ runs and worked fine.
```
"app_name=Bracecould | bin span=5s http_status as bin_http | stats count by bin_http | stats count",now-1d,now,*,countRecord:count(*):*,eq,3,Splunk QL
"app_name=Bracecould | bin span=2log3 http_status | stats count by http_status | stats count",now-1d,now,*,countRecord:count(*):*,eq,2,Splunk QL
"app_name=Bracecould | stats values(eval(http_status > 400)) as values",now-1d,now,*,group:values:*,eq,1,Splunk QL …
```
=> Fix: Some queries were not working for multi segment/index data.

pkg/health/clusterStatsHandler.go, pkg/hooks/hooks.go, pkg/utils/httpserverutils.go
This cleans up some code related to storing index stats. It mainly avoids the need for a type assertion by making a dedicated struct type for handling index stats. I had gotten a panic on one of the type assertions, but can't reliably reproduce in siglens.
The code is still a little awkward. For example, in `getStats()` we return `stats` of type `map[string]utils.AllIndexesStats`; since `AllIndexesStats` has a map of index name to stats for that index, the type of `stats` is basically this: `map index -> map index -> stats for the index`. I only kept it like this because that is what we were doing previously, and I wanted to keep this PR small.
I manually checked the MyOrg page after ingesting some data. It looks the same as before this PR. I checked with rotated and unrotated data. …
=> Clean up index stats

pkg/segment/query/segquery.go, pkg/segment/query/segquery_test.go
- Removed the part where we are checking and doing raw search for missing blocks. 
- This fix assumes that there will be no missing blocks.
- And for this we need to handle two cases so that there will be no missing blocks:
- If persistent query is enabled in the middle of the segment, we should not create a PQS for that segment.
- We should not do `BackFillPQSSegmetaEntry` for the segment if the segment is not fully enclosed in the PQS time range.
- We should also avoid any other cases that might create the scenario where there can be missing blocks.
- Also now for PQS, even for the segments that can be skipped, the code will now call `IncrementNumFinishedSegments`, so that query update for this segment is processed.
- Tested by running the queries while PQS is enabled.
- Commented the …
=> fix: Resolved Issue of Incorrect segKeys Addition to pqsmeta When Handling Missing Blocks

pkg/segment/writer/agiletreewriter.go
- Fixes overriding of startTree file encoding type with the Metadata.
- Tested by executing the group by queries.
=> fix: overriding of starTree file encoding type

pkg/segment/writer/stats/segstats.go, pkg/segment/writer/stats/segstats_test.go
Fixes a bug in `MergeSegStats()`. This bug only happens when we have `fileParallelism > 1` here: https://github.com/siglens/siglens/blob/develop/pkg/segment/search/searchaggs.go#L694-L698
We've been using `fileParallelism == 1`, so this hasn't been an issue yet because in that case we never actually merge two non-empty SegStats maps.
Added new unit test that fails without this bug fix. It only tests very basic merging behavior.
=> Fix a bug with merging SegStats maps

pkg/segment/query/segquery.go
When running a single query, this allows for more parallelism in the query and so it runs faster.
With about 110 million rows, I ran this query:
```
* | timechart span=1m avg(latency)
```
On my local machine this took 24.7 seconds before. With this PR, it's about 7.4 seconds.
=> Increase parallelism per file

tools/sigclient/pkg/alerts/alerts.go
- Wait for AlertHistory to be updated, before querying it.
=> fix: Wait for Alert History to be updated

pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/querystatus.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/structs/segstructs.go, pkg/utils/logutils.go
Added a global logger to log common error and prevent log fill up.
For now, the ErrorInfo struct has Count, later we can add more meta data like segmentkey etc.
This particular query produces multiple "Did not find index for record identifier" errors for many records.
Verified the count and errors reported.
```
country=United* | fields app_name, app_version, country, city, user_email, http_status, http_method | transaction app_name startswith=eval(http_status=301 OR http_status=200) endswith=eval(http_status>=400)
```
=> Global Logger to reduce Log Counts

tools/sigclient/README.md, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/query.go
- Added a new function to run the given queries and the update the response time to the given file.
- Tested by running the commands:
`go run main.go query esbulk -d ws://localhost:5122 -f ../../cicd/restart.csv -o local_res.csv -t true`
`go run main.go query esbulk -d ws://localhost:5122 -f ../../cicd/SPL_Playground.csv  -t true`
=> feat: SigClient: Added a function to get Query Response Times

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/querytracker/querytracker.go, pkg/querytracker/querytracker_test.go, pkg/segment/query/segquery.go, pkg/segment/search/segsearch_test.go, pkg/segment/structs/querystructs.go, pkg/segment/writer/unrotatedquery_test.go
Store search text in pqs query info for wssearchhandler and searchhandler.
- Verified that the searchtext is being populated correctly for simple search without aggs, and also search with aggs.
=> Store search text in pqs query info

benchmark_test.go, metricsbenchmark_test.go, pkg/config/derivedConfig.go, pkg/segment/query/queryrefresh.go
- The benchmark test will set the machine host name, set the `SmrBaseDir`, load `vtables`, `populateMicroIndices`, and `InitQueryNode`.
- Then it will start a `websocket` server and will call `ProcessPipeSearchWebsocket` within a websocker handler.
- Tested by executing the benchmark
=> feat: Added E2E Benchmark Test for Logs

pkg/ast/spl/tests/splParser_test.go, pkg/segment/search/conditioncheck.go, pkg/segment/search/filtersearch.go, pkg/segment/utils/segconsts.go
1. Remove unused mem constant and increase raw search mem percentage
2. For wildcard queries on all columns, remove the dictEncColnames from the cmiPassedCnames at the top of block search, so that when we iterate through records, we don;t check if the current colname is a dictColName. If there are 16K records per block , it will remove `16K * Num_dict_columns` times of map checks. This helps in search queries like `search = whatever*`
=> performance fixes for allcolumns search for wildcards

static/css/siglens.css, static/js/query-builder.js, static/js/search.js
**Enhanced the Info Icon Popup**: The popup now displays additional details about the query response, including:
- First Result Response Time
- Final Result Response Time
- Records Searched
- Time Range of the Query
=> UI: Update Info Icon to Include Response Time Details

static/css/siglens.css, static/js/pqs-settings.js, static/pqs-settings.html
1. Separate Tables for Promoted Searches and Promoted Aggregations
2. Total Tracked Row as a Final Non-Sortable Row
=> UI : Display PQS Details in Separate Tables

pkg/config/config.go, pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/multicolreader_test.go, pkg/segment/search/conditioncheck.go, pkg/segment/search/filtersearch.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go
During multicol file reading, record by record, pull out the fileReader ptr that is inside MultiColReader for a column by passing in the keyIndex, instead of doing a lookup in a colNameToKeyIndex every record, this way we only find all the keyIndices once every block instead of once every record
With this change, if there are `5 Million` records and `270` blocks in one segfile then we do the 
`sfr := mcsr.allColsReverseIndex[cName]` 270 times instead of 5 Million times per segfile
=> avoid revereKeyIndex lookups per record and do it once every block

pkg/ast/pipesearch/resultStructs.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/querystatus.go, pkg/segment/query/segquery.go
Added totalRecsToBeSearched which has the total number of records to be searched calculated before executing the actual query.
Total possible events should have the correct count seen below. UI can use this variable to update the progress bar.
Always shows the same total number of records to be searched.
=> Show correct total number of records to be searched in progress bar

pkg/segment/query/metadata/blockmeta.go
- For wildcard value searches, the cmi check will not read/load CMIs.
- Tested by running the query `whatever*`
=> Do not Read cmis for wildcard value searches

pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats_test.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go
For each bucket key we create during historgram queries, we were using bytes.Buffer and growing it by adding all the groupby cols to it. This bytes buffer was reset on every record. Now pre-allocate a byte slice per block worker and reuse that bytes buffer during each record processing. This helps in runtime memory allocations.
=> Use pre-alloc byte slice instead of buf.Bytes during AddMeasureToRes

pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/multicolreader_test.go, pkg/segment/reader/segread/segreader_test.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go
Reuse Cval in each blockworker/segment worker while extracting values from csg files. By doing this we save 10 GB of runtime mem alloc on a 456 million data size for a query like `"* | stats avg(http_status) by hobby, http_method`
=> reuse cval per segment and avoid using it per rec

pkg/segment/reader/segread/segreader.go
This was the main change:
```diff
-	uncompressed, err := decoder.DecodeAll(buf[0:], sfr.currUncompressBuffer[:0])
+	uncompressed, err := decoder.DecodeAll(buf[0:], sfr.currRawBlockBuffer[:0])
```
I think the original version was due to a misunderstanding. From the zstd docs on [DecodeAll](https://pkg.go.dev/github.com/klauspost/compress/zstd#Decoder.DecodeAll):
> Output will be appended to [the second parameter]
But I think the original code meant for zstd to use `currUncompressBuffer` for internal use, as `currUncompressBuffer` isn't used anywhere else.
Since immediately after decoding we have `sfr.currRawBlockBuffer = uncompressed`, I used `currRawBlockBuffer` in the decoding and deleted the `currUncompressBuffer` field
Unit tests and e2e tests continue to pass
I ran the query …
=> Fix zstd memory overuse issue

pkg/segment/reader/segread/dechecker.go, pkg/segment/search/conditioncheck.go, pkg/segment/search/filtersearch.go, pkg/segment/writer/rawchecker.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segstream.go
Pass the compiled regex with a fast flag for applying match filter on records. Compile the regex at block level.
CPU Time
flat flat%  sum%    cum  cum%
Before: 19.52s 3.92% 58.88%  135.90s 27.32%
After: 15.23s 3.13% 62.73%  128.84s 26.46%
Before Total time: 161.73s
After Total time: 158.17s
Memory Usage:
No change, used 512.06kB memory in regexp.Match for both the cases.
Summary:
Total time reduced by ~3s.
Time reduced in this function ~4s
Memory consumption: No change
=> Use pre-compiled regex for applying match filter on records

.github/workflows/uts.yml
When a PR is made in Draft and then marked Ready for Review, the uts.yml action doesn't run, this should fix that.
From the [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request):
> By default, a workflow only runs when a `pull_request` event's activity type is `opened`, `synchronize`, or `reopened`
So the only change should be the addition of the `ready_for_review` trigger.
Not tested
=> Run workflow if Draft PR becomes Ready for Review

pkg/utils/maputils_test.go
Missed to sort the addedEntries in the first test of SetDifference.
Improved it by using ElementsMatch instead of sorting and then comparing slices.
=> Fix: Map utils test

API_README.md, pkg/lookups/lookups.go, static/css/siglens.css, static/js/lookups.js, static/lookups.html
This PR adds the ability to overwrite existing files when uploading lookup files.
- Modified the backend to accept an 'overwrite' parameter in the form data
- Updated the frontend, added a confirmation dialog in the UI for overwriting files
- Updated API README to reflect the new overwrite option
=> Add file overwrite option to Lookup File Upload

cicd/ingest.csv, cicd/restart.csv, pkg/segment/query/metadata/segmentmicroindex.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/segreader.go, pkg/segment/writer/rawchecker.go
Previously, a search containing a column that doesn't exist, like 
```
weekday=Monday OR foo!=false | stats count
```
would show an error on the UI like:
```
Message: MultiColSegmentReader.ValidateAndReadBlock: keyIndex 0 is out of bounds, len of allFileReaders: 0,
```
This PR fixes that so that the query gives proper results. For the above query, `foo` does not exist, so `foo!=false` is always `true`, so all records pass the search
New e2e tests
=> Fix searches that don't find a column

pkg/segment/utils/segconsts.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/agiletreewriter.go, pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go, pkg/segment/writer/segstore.go, pkg/segment/writer/startree_test.go
1. Use in in place conversions for NumTypeEnclosures
2. pre-alloc pointer array for node.children
=> In place NTE conversion and pre-alloc node ptrs

pkg/segment/search/searchaggs.go
For queries like `app_name=Bracecould | stats min(http_status)`, `http_status` which is a numeric dict encoded value was being treated as nonDeCol. Over [here](https://github.com/siglens/siglens/blob/ed6891239e65e973446a5f0783b75e32d911242b/pkg/segment/search/searchaggs.go#L988) there are no checks for int64 and float64 type values which also can be dict [encoded](https://github.com/siglens/siglens/blob/ed6891239e65e973446a5f0783b75e32d911242b/pkg/segment/reader/segread/segreader.go#L427). Added numeric stats accumulation similar to how its done over [here](https://github.com/siglens/siglens/blob/ed6891239e65e973446a5f0783b75e32d911242b/pkg/segment/search/searchaggs.go#L906).
Describe how you tested …
=> Numeric dict encoded values

pkg/segment/reader/segread/segreader_test.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
1. Switch `recNums` for dictEnc columns from array to bitset
2. This saves about `3.1 GB` of mem  (about `6%`) on a `1 index, 10 segment, 3.2 million recs/seg` test 
=> use bitset for storing recnums for dictEnc columns

pkg/health/clusterStatsHandler.go, pkg/segment/tracing/handler/tracehandler.go
Do not run tracing related queries if trace index count is 0.
This code uses 0 as `myID` since there is no way to retrieve the orgID from the caller in `startup.go` ([link](https://github.com/venkateshamatam/siglens/blob/29e9253627d4a58870d4df31f19f5a24cede6c39/cmd/startup/startup.go#L291)) and the current implementation uses 0 as myID ([link](https://github.com/venkateshamatam/siglens/blob/29e9253627d4a58870d4df31f19f5a24cede6c39/pkg/segment/tracing/handler/tracehandler.go#L356))
=> Do not run tracing related queries if trace index count is 0

pkg/es/writer/esBulkHandler.go, pkg/es/writer/esBulkHandler_test.go, pkg/integrations/loki/loki.go, pkg/integrations/splunk/splunk.go, pkg/otlp/otlp.go, pkg/sampledataset/sampledataset.go, pkg/segment/segexecution_test.go, pkg/segment/tracing/handler/tracehandler.go, pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/startree_test.go, pkg/segment/writer/unrotatedquery_test.go, pkg/utils/segutils.go
The call to `jp.ParseString()` was using up `19 GB` during a `1 index, 10 segments` test. The call inside this function was doing `string(retVal)` where retVal was `[]byte`. All this function was doing was unescaping the incoming bytes and converting the result into string. We don't necessarily need the string and work around by just using the bytes. So switched this processing logic to only do the unescaping and returning the resultant byte array as is. 
This resulted in savings of about `13 GB` or so
=> avoid string conversion during jp.ParseString and use bytes all along

pkg/segment/writer/segstore.go
Optimize writing of bytesWritten by first writing dummy data and then overwritting it with the correct size.
This prevents writing the bloom twice.
Tested on a sample 20M records 1 index 10 segment test for [Benchmark_agileTreeIngest](https://github.com/siglens/siglens/blob/ed6891239e65e973446a5f0783b75e32d911242b/benchmark_test.go#L379).
Before
Total Memory used: 166.44MB
Memory used by allocation of bufio writer: 25 MB
Memory used by `bi.Bf.WriteTo(bufWriter)`: 96 MB
After
Total Memory used: 46.43MB
Memory used by additional os.Open: 1 MB
We noticed a sudden drop from 166 MB to 46 MB of memory usage. It would be even more efficient for large data sizes.
Describe how you tested this code. How can the …
=> Optimize Flushing of Bloom

go.mod, go.sum, pkg/segment/aggregations/streamstats.go, pkg/segment/aggregations/timechartagg.go, pkg/segment/reader/segread/segstatsreader.go, pkg/segment/reader/segread/segstatsreader_test.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch_test.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/segstructs.go, pkg/segment/structs/segstructs_test.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/stats/segstats.go
- Migrates to Segmentio Hll from Axiom Hll.
- Segmentio Hll requires some default settings to be set and it will throw an error if the settings are invalid. For that we are using the defined settings instead of default.
- But from the query side for timechart and stats cardinality, we will try to create the Hll with same settings if failed, it will be return the default hll. 
- All Unit tests passed
=> Migrate to Segmentio Hll from axiom Hll

pkg/segment/writer/agiletree.go, pkg/segment/writer/segstore.go
Created an STBHolderPool to get and release StarTreeBuilder for memory management.
In future PR, we will release memory based on specific timeouts.
Also, `usingSegTree` variable is not needed as this could be checked directly via stbHolder.
Manually ran multiple segment ingest and monitored logs to check the allocation of stbHolders to segStore.
Also, tested the same using the [Benchmark_agileTreeIngest](https://github.com/siglens/siglens/blob/ed6891239e65e973446a5f0783b75e32d911242b/benchmark_test.go#L379).
=> StarTreeBuilderPool for managing STBs

pkg/segment/reader/segread/agiletreereader.go, pkg/segment/utils/number.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/agiletreewriter.go, pkg/segment/writer/startree_test.go
Switch from using `CvalEnclosure (interface)` to a number union type.
This saves about `1.5 GB` per agile tree
=> Use number union for node.AggValues

pkg/segment/writer/agiletree.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
1. Create a new method that converts from rec bytes directly to `Number` type instead of the intermediary Cval
2. Move the `workBufForComp` from ColWip to segstore so that it does not get cleared out on every segment rotation.
memory Savings:
1. Saves about `80 MB` per segment
2. Saves about `60 MB` per segment
=> memory optimizations: create getnumfromrec and move the compWokrBuf from wip to segstore

pkg/segment/utils/segconsts.go
Currently, we are just marshaling the PQS data and writing it to the file. We are not encoding it before writing.
Unexported fields are not marshaled and so compiled regex was not written to disk. Upon reading the PQS info, we were getting `nil` compiled regex due to which all regex based PQS queries were failing during ingest with error. 
`
time="2024-08-24 21:40:30" level=error msg="SegmentKey: data/sigsingle.NAxq42aiGpFefVVpoAEuYJ/active/bidx-7/0-0-10969000109510147866/999/999, applySearchSingleQuery: failed to apply wildcard expression search on RegexExpression, Count: 22942336, ExtraInfo: qValDte had nil regexp compilation"
`
For now, have made the field exported. In future, when we plan to encode and write to disk we can revert this change.
Fixes …
=> Compiled Regex is not persisted for PQS due to unexported field

pkg/es/writer/esBulkHandler.go, pkg/segment/reader/segread/segreader_test.go, pkg/segment/utils/segconsts.go, pkg/segment/utils/segutils.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/agiletreewriter.go, pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/startree_test.go
1. Use sync pools for colWip.cbuf and avoid reallocs of 2 MB per wip
2. Reuse buf for indexname parsing
3. Use sync pool for items array while doing json parsing for es bulk index requests
4. Encode and write atree in 128k chunks and avoid one large write and reduced mem usage
5. Use pre-allocated array for agile tree traversal
6. Simplify `deData` and reduce the num of maps used, and reduce mem consumption
7. simplify json parsing code and remove unused return variables of encodeXXType
8. do maxIdx calculation once after all columns have been parsed.
These changes brings down the memory consumption by more than `40%`  
=> mem fixes: dedata, sync pools for cbuf, items, tree traversal, atree file size chunk writing

pkg/segment/writer/segstore.go
`AppendWIP..` would crash if the num of columns changed between each wip, because we were incorrectly resizing slice.
=> fix bug with resizing of slices

pkg/segment/tracing/handler/tracehandler.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
1. concurrent map read/write was causing a panic during ingestion. Added missing segstore.lock
2. Don't create dependency graph if traces count is 0
3. Use cbufpool for de packing instead of a const size of 200k (fixes a panic in some scenarios)
=> fix missing lock and de pack buf panics

pkg/es/writer/esBulkHandler.go, pkg/es/writer/esBulkHandler_test.go, pkg/segment/reader/segread/segreader_test.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/packer.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/segwriter_test.go, pkg/utils/bitutils.go
1. This avoids looping through the colValue twice and does it only if there is an upper case letter
2. Avoids testAdd call to bloom if there is no upper case letter
3. Add to bloom during the time of wipPacking to avoid bloom adds for the dict columns for the same dict encodings
4. Switch to using `Add` call for bloom instead of `TestAdd`
5. Fix a buf with itemsLen if batchsize was greater than 4k
6. All of these improvements increase the ingestion performance by `40%`
=> perf improvements: bloom writing optimizations

cicd/ingest.csv, cicd/restart.csv, pkg/segment/aggregations/evalaggs.go, pkg/segment/aggregations/evalaggs_test.go, pkg/segment/reader/record/rrcreader.go, pkg/segment/reader/segread/segstatsreader.go, pkg/segment/reader/segread/segstatsreader_test.go, pkg/segment/results/segresults/segresults.go
Fixes stat aggregators being ignored are fields in a query.
Fixes values and average stat aggregators giving inconsistent results after fields.
Fixes #885 (link all the GitHub issues this addresses)
app_name=Bracecould | fields latency | stats avg(latency) as avg
app_name=Bracecould | fields latency | stats values(latency) as values
app_name=Bracecould | fields latency | stats count 
app_name=Bracecould | fields latency | stats min(latency)
app_name=Bracecould | fields latency | stats max(latency)
app_name=Bracecould | fields latency | stats sum(latency)
app_name=Bracecould | fields latency | stats list(latency)
app_name=Bracecould | fields latency | stats range(latency)
In all queries the result should be the …
=> Bug fix: aggregations do not work after fields

pkg/segment/query/metadata/metadata.go, pkg/segment/query/metadata/segmentmicroindex.go, pkg/segment/query/segquery.go, pkg/segment/query/segqueryhelpers.go, pkg/segment/results/segresults/segresults.go, pkg/segment/structs/querystructs.go, pkg/segment/writer/unrotatedquery.go
In the case of matchAllQuery like `* | stats count` we were just picking up a random column from the sstMap and then using that count. If records have NULL values, the count would vary based on the column picked (Note: Map iteration order is not deterministic).
Find the total records in the segment from microIndices and then pass that on to the SegmentQueryRequest. Use this value to get the count.
Showing the message explicitly because, often it is confusing for people to apply operators with `*` which is only supported for count.
`request_id=* | stats count` was giving correct results because we are [populating](https://github.com/siglens/siglens/blob/523968fba532486e00054b05e924757b25cdb7db/pkg/segment/search/searchaggs.go#L958) sstMap for `*` because for raw …
=> Fix stats count for MatchAllQuery

RELEASE_README.md, cmd/startup/startup.go, pkg/config/version.go
- Bumps the version to `0.2.35d`
- Also includes an update to the `Release_read_me` file.
=> Bump Version to 0.2.35d

pkg/segment/segexecution_test.go
Unmerged changes in a different branch caused some tests to panic. This inhibited the cleanup logic, so then during development when you switch back to a branch like develop where the tests should pass, they were still failing because there were leftover files. This PR fixes this issue by using `t.Cleanup()` to ensure the cleanup logic happens even in the case of panics (see https://go.dev/play/p/I4UaAb5Fd8Z)
The leftover data was in `pkg/segment/data`. After running `make test` again with these changes, the tests still panicked (as I was on a feature branch that has issues), but `pkg/segment/data` got cleaned up correctly. Then switching back to develop and running `make test`, the tests all passed (as expected)
Before marking your pull request as ready for review, complete the …
=> Remove test data even when tests panic

pkg/utils/debugutils.go
This adds a util that can be helpful during development to estimate how much memory a struct is consuming at runtime.
Not tested
=> Add util to estimate runtime size of struct

pkg/config/config.go, pkg/config/config_test.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/packer.go
1. Increase segfile size to avoid too fast rotations on high load
2. Decrease dict card limit for perf reasons when hihg card columns were present, we were doing too many string conversion on each new wip to check if we have exceeded card limit and allocating a rec array for each unique value
=> increase segfile size to avoid too fast rotations

pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segwriter.go
This PR reduces some unnecessary locking. Theres a `RWMutex` used to control access to a map of all unrotated segstores. Previously, when getting or creating a segstore, we would always acquire the write lock; now we generally acquire the read lock, but still acquire the write lock if necessary.
Manually tested an ingestion with ~20 threads and indexes, and there wasn't any panic like "concurrent map read and write"
Ran ingestion like this:
```
go run main.go ingest esbulk -n 20 -g dynamic-user -d http://localhost:8081/elastic -p 23 -t 5_000_000 -i bidx -b 1000
```
and then pprof:
```
go tool pprof http://localhost:5122/debug/pprof/block
```
Before, locking in `getSegStore()` was blocking for 3.31 seconds. Now, `getOrCreateSegstore()` (it was renamed) only blocks for 0.00525 seconds. …
=> Use read lock to get segstore

.github/workflows/publish-prod-images.yml, cmd/startup/startup.go, pkg/config/version.go
- Bump version to 0.2.36d
- This also includes a change to SigClient-docker job in `publish-prod-images.yml` file. Pointing to the correct dockerfile.
=> Bump Version to 0.2.36d

pkg/segment/utils/segconsts.go, pkg/segment/writer/segwriter.go
When multiple threads call `AddEntry` function, they each call  `getOrCreateSegStore` and multiple of them could be waiting for lock , one of them succeeds, creates a the NewSegStore, and then others try to do the same thing. The original thread writes the the bulk batch it received in its segstore. But that segstore get's overwritten in the map with the latter threads, thereby causing loss of data. 
This more restrictive lock fixes that.
=> add more restrictive lock during creation of segstore

pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/segwriter_test.go
There's a concurrency bug that sometimes happens:
1. We get a query, and find the segments that match it; one of the unrotated segments match it
2. Concurrently, we receive more data, and rotate the segment that matched it
3. We continue processing the query, and try to read from the files where data is stored. But the segment got rotated, so it's in the `.../final/...` directory instead of the `.../active/...` directory. We log and return an error for that segment.
This PR fixes the issue by looking in `/final/` if we got an error looking in `/active/`
Mostly manual testing. I decreased the size of segments via `maxSegFileSize: 200000000` in my server.yaml. I also added a 5-second sleep just above this line: https://github.com/siglens/siglens/blob/develop/pkg/segment/reader/record/recordr …
=> Check rotated files when unrotated are absent

cmd/startup/startup.go
Cleans up the startup sequence for siglens server.
Ports should be opened at last, that are `startIngestServer`, `startQueryServer` and `InitMetrics`
After this change started a server, ingested data and queried.
=> Cleanup the startup sequence

pkg/segment/writer/agiletree.go, pkg/segment/writer/segwriter.go
- Initialize the aggValues during the creation of node to prevent inconsistencies and scenarios where sometimes measureVal is not found for a record is [missing](https://github.com/siglens/siglens/blob/4daa08c5309ddb937783c149bbb4764ca3633c07/pkg/segment/writer/agiletree.go#L636).
- Added checks to report errors during agileTree creation
- We were not encoding numerical values because of which this issue happened and there was a mismatch.
Stack trace
```
panic: runtime error: index out of range [0] with length 0
goroutine 541 [running]:
github.com/siglens/siglens/pkg/segment/writer.(*StarTreeBuilder).Aggregate(0xc030d56000, 0xc038c40d00)
/usr/app/pkg/segment/writer/agiletree.go:384 +0x5bf
github.com/siglens/siglens/pkg/segment/writer.(*StarTreeBuilder).Aggregate(0xc03 …
```
=> Fix: Mismatch of aggValues in agileTree

pkg/blob/local/localstorage.go, pkg/segment/search/segsearch.go, pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/segwriter_test.go, pkg/segment/writer/unrotatedquery.go, pkg/utils/segutils.go, pkg/utils/segutils_test.go
Previously we would flush WIP blocks for a segment into an `active` directory, and when we rotated the segment we'd move that `active` directory to `final`. This causes some problems during query because sometimes we obtain segkeys for `active`, but then the segment rotates, and then when we look for that data we can't find it because it's in `final`. This PR addresses this issue by removing the `active` dir; now we put all data—even unrotated data—in `final`.
With this, we do lose some ease of identifying if a segment is rotated or not. We can look in segmeta.json for the segkey; also, this PR adds a new file (segment-validity.json) that is created during segment rotation—if that file is present, then the segment is valid and rotated.
Ran continuous ingest and query, and it seems to be …
=> Merge active and final data directories

.github/workflows/playwright-test.yml, playwright-tests/tests/common-functions.js, playwright-tests/tests/dashboard.test.js, playwright-tests/tests/index.test.js, playwright-tests/tests/navbar.test.js, static/js/dashboard-from-logs-metrics.js, test-results/.last-run.json
1. Modified the playwright.yml to include data ingestion, ensuring that logs & metrics are ingested before running tests.
2.  Added Playwright tests for the Logs screen to test the functionality of features such as saving queries, adding logs to dashboards, creating alerts, downloading logs and available fields toggle.
3. Refactored the dashboard.test.js file for faster test execution.
=> Add Playwright Tests for Logs Screen with Ingested Data

pkg/segment/reader/segread/segreader.go
We were facing errors from filterSearchQuery because ValidateAndReadBlock was returning error when some blocks did not have specific columns that are present in the segment.
`
filterRecordsFromSearchQuery: failed to validate and read block: 3, err: SegmentFileReader.readBlock: column does not exist in block: 3 colNum: perseite-u file: data/sigsingle.9rDJ3exZ6KfZJskdDj34WP/final/svcgroup-1/0-0-13435680861203573242/0/0_15363296528398503342.csg 
`
Steps to reproduce:
- Make max_recs per wip to 1
- Based on a random number assign an extra column
- Run query say `*vector*`
Earlier I was getting the above mentioned error, with …
=> Fix for column does not exist in block error

pkg/config/config.go, pkg/config/config_test.go
Previously, if the config file (server.yaml) had fields that we didn't expect, we'd silently ignore them. Now we crash on startup. The benefit of this is that if someone makes a typo in their server.yaml, that issue will be very prominent, so they'll know to fix it.
Updated the unit tests.
=> Disallow unknown fields in server.yaml

pkg/config/common/common.go, pkg/config/config.go, pkg/config/config_test.go, pkg/server/query/server.go
This adds a config option to not compress files in `static/`. By default, these will be compressed. When compression is enabled, there will be some files like myfile.fasthttp.br that get written to `static/`. For some use cases, users may want to have `static/` be read-only; this new option allows that.
1. Clear the .br files: `find . -name "*.br*" | xargs rm`
2. Start siglens
3. Run `watch -n 1 'find . -name "*.br*" | xargs ls'`
4. Go to the UI and click on several pages. Without this PR (or with this PR and having `compressStatic: true`), after a while your `watch` command should show some files; but with compression disabled, your `watch` command should continue showing no files.
=> Add option to not compress static files

docker-compose.yml, install.sh
Fixed the install.sh script to migrate `siglens.db` from the dockerbased installation folder to its relevant data directory.
Cleaned up the docker-compose.yml file.
install.sh Testing
- Installed siglens using docker
- Created some alerts.
- Stopped and restarted the siglens using docker-compose and verified that alerts are present as expected.
- Moved the siglens.db outside the data folder.
- Re-ran siglens and verified that alerts are not visible (cannot find siglens.db)
- Updated the script and docker-compose.yml and ran the installation with the updated script
- It migrated the correct, existing siglens.db from the …
=> Fix install.sh for migrating siglens.db

pkg/segment/reader/record/recordreader.go, pkg/segment/writer/unrotatedquery.go
Most of the repo was using `blockNum` but some parts used `blockIdx`. Now everywhere uses `blockNum`.
unit tests
=> Rename blockIdx to blockNum

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/dataprocessor_test.go
This adds the `DataProcessor` type that will handle the execution of an individual query command (e.g., eval, stats, etc.). The logic specific to each command will be implemented by a type implementing the `processor` interface. This PR adds the general functionality that is shared across all commands.
Merging multiple input streams is not yet implemented—that will come in the next PR
New unit tests
=> Add Data Processor

pkg/config/common/common.go, pkg/config/config.go, pkg/config/config_test.go, pkg/server/ingest/server.go
- Enable `pprof` through a new config variable. By default the `pprof` is enabled.
- All unit tests pass
- Tested by starting the server and going to the pprof endpoint.
=> Config var for Enabling pprof

pkg/es/writer/esBulkHandler.go, pkg/segment/writer/logpacker.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go
- Fixes the Nested json ingest.
- Fixes the handling of null values
- Tested by ingesting a nested json with some null values
=> fix: Nested json ingest and handling of null values

static/css/dashboard.css, static/css/siglens.css, static/dashboard.html, static/js/dashboard.js, static/js/edit-panel-screen.js
This PR adds a search bar to the dashboard screen, allowing users to filter existing SplunkQL log panels.
Users can save the filter for all panels or edit a specific panel, which will reset the rest to their original state.
The filter only supports valid filter commands—stats and group by commands are not allowed - a tooltip shown for invalid inputs.
Fixes https://github.com/siglens/siglens/issues/901
=> Add Search Bar for Filtering Log Panels

playwright-tests/tests/all-alerts.test.js, static/js/common.js, static/js/event-handlers.js, static/js/settings.js
- Display the error message `This chart type is not compatible with your query. Please select a different chart type.` for cases where the chart type selected is incompatible with the query.
Example - Metrics queries support only number and line charts and do not support other chart types.
- Fix the issue where running a query and changing the time range was triggering two backend calls
Fixes #440 
=> Improve Error Handling for Invalid Chart Types on Dashboard Panel Query Execution

static/js/cluster-stats.js
Updated storage graphs on the cluster stats page to correctly convert total volume from bytes to GB
For the index table, we updated the backend to send the total volume in bytes, but for the graph, we need to convert the bytes to GB to display the correct values.
=> Fix Storage Graphs on Cluster Stats Page

pkg/server/ingest/server.go, pkg/server/query/server.go
- Removed the `pprofHandler` on the ingest server and enabled it on query server
- Tested by running the server and calling the pprof endpoint.
=> Enabled pprof on query server and remove it on ingest server

pkg/segment/writer/segstore.go
We should use a temp file to write the stats and rename it to correct name only after all the data is written.
Moreover, in this PR we are doing an os.Rename before closing the file. This is safe for [Linux/Unix](https://github.com/golang/go/issues/32088) based systems and should not cause issues. But this is not allowed in windows. Since, siglens is supported for MacOS/Linux this shouldn't be a problem.
=> Overwritting the SegStat file should happen atomically

pkg/segment/query/segquery.go
- When a query (`qid`) is not found in the `allRunningQueries` map, the raw search should stop and should not continue further.
=> fix: stop raw search when a query is not found in the allRunningQueries Map

pkg/ast/pipesearch/searchQueryParser.go, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/wherecommand.go, pkg/utils/sliceutils.go, pkg/utils/sliceutils_test.go
Using the new query pipeline, `where` commands now work. For example, `city=Boston | where weekday="Monday"`
Some new unit tests.
After enabling the new pipeline in config.go, I also tested manually with benchmark data and running queries like this
```
"searchText": "city=Boston | where weekday=\"Monday\" OR latency<100000",
"startEpoch": "now-24h",
}' http://localhost:5122/api/search | python3 -m json.tool | less
```
This gave the same number of results as the equivalent query `city=Boston AND (weekday=\"Monday\" OR latency<100000)` on the same dataset. 
=> Add where command to new query pipeline

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/processor/sortcommand.go, pkg/segment/query/processor/sortcommand_test.go, pkg/segment/structs/evaluationstructs.go
Now `sort` queries can be run on the new query pipeline. The only caveat is that sorting items as an IP is not supported (see https://docs.splunk.com/Documentation/Splunk/9.1.1/SearchReference/Sort#Sort_field_options); but that also is not supported with our existing pipeline.
New unit tests.
I also manually tested with:
```
"searchText": "* | sort limit=10 -latency",
"startEpoch": "now-24h",
}' http://localhost:5122/api/search | python3 -m json.tool | less
```
I also tried `* | sort limit=10 latency` and `* | sort latency`. They all seemed to give correct results.
=> Add sort command to new query pipeline

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/processor/bincommand.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/structs/evaluationstructs.go
Now [bin commands](https://docs.splunk.com/Documentation/Splunk/9.1.1/SearchReference/Bin) can be used in the new query pipeline as long as the span is specified. Handling the case where the span is not specified will be done in a different PR.
Most of the actual bin calculation was copied from segaggs.go and slightly modified.
```
"searchText": "* | bin span=10000 latency",
"startEpoch": "now-24h",
}' http://localhost:5122/api/search | python3 -m json.tool | less
```
I also tried `* | bin span=10000 latency as latencyBin` and the column renaming worked as expected.
=> Add bin with span to new query pipeline

pkg/retention/retention.go, pkg/segment/query/pqs/meta/pqsmeta.go, pkg/segment/writer/segmetarw.go, pkg/segment/writer/segstore.go, pkg/utils/maputils.go, pkg/utils/maputils_test.go
- All the writes to empty PQS meta is only done through the `PQSChan` channel.
- Tested by ingesting and making some queries and ensuring those were written to the empty pqid meta file and sfm file.
=> write empty pqs meta only through channel

pkg/retention/retention.go, pkg/segment/writer/segwriter.go
When retention based deletion is kicked in, we have to delete a bunch of things. The sequence on how we delete those things matter. This PR fixes a bug wherein an incorrect sequence caused `allSegmentMicroIndex` to have entries for segments that were already deleted and removed from segmeta.json.
When a deletion is kicked off, we were
1. Deleting the segkey from metadata.allSegmentMicroIndex
2. deleting pqmr files
3. Removing entry from segmeta.json
4. Deleting all files as part of the segment
After 1 was executed and before 3, some other segment got rotated and caused the segmeta.json file's timestamp to get modified. The populateMicroIndex thread would come in and read the segmeta.json. It would also read the segkey that was just deleted in step 1, and then it would add it back to …
=> fix the segment deletion sequence during retention

pkg/segment/utils/segconsts.go, tools/sigclient/functionalQueries/simple_sort.json
- Sets the query exit limit to 100
- Ran `*`  query and verified that the result has only 100 Records
=> Set query early exit limit to 100

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/query/processor/bincommand.go, tools/sigclient/functionalQueries/functionalQueries.yml
- There is a `bin` command version without bins and span and for that new column name and parser output is not being set to the `BinExpr`.
- This is fixed and the below query will work now
```
curl --location 'http://localhost:5122/api/search' \
--header 'Content-Type: application/json' \
--data '{
"state": "query",
"searchText": "app_name=Bracecould | bin http_status as bin_http | bin bins=2 http_status as bin_http_2 | bin span=5s http_status as bin_http_3 | bin span=2log3 http_status as bin_http_4 | bin minspan=500 http_status as bin_http_5 | bin bins=50000 http_status as bin_http_6 | bin bins=50000 minspan=2 http_status as bin_http_7 | bin end=100000 http_status as bin_http_8 | bin start=-10000 http_status as bin_http_9",
"startEpoch": "now-7d", …
```
=> fix: Bin CMD renaming of columns plus Bin CM without bins and without span

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go
Earlier this query was returning all columns because the [mergedIQR](https://github.com/siglens/siglens/blob/2442244de2c6b5ae08f04decf79ac031c0c7cd1e/pkg/segment/query/iqr/intermediateQueryResult.go#L361) metadata was not reflected in the iqr created for append. So deletedColumns and columIndex were not updated.
`http_method=POST AND (app_name=Bracecould OR app_name=R*could) | fields app_name, app_version`
Not sure on do we want groupByColumns, and measureColumns to update as well, shouldn't they be same every time. I was not sure so I have not updated those.
- Ingest benchmark dataset
- Run the given query
- Observe that …
=> Fix Append method was not updating deleted columns and columnIndex

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go
**Sort Crash**
- For a certain query, the sort command was crashing siglens.
Stack trace
```
panic: runtime error: index out of range [0] with length 0
goroutine 102 [running]:
github.com/siglens/siglens/pkg/segment/query/iqr.MergeIQRs({0x140257efb68, 0x2, 0x1402429ba98?}, 0x140257efb78)
/Users/Kalariya/siglens/pkg/segment/query/iqr/intermediateQueryResult.go:520 +0x5e0
github.com/siglens/siglens/pkg/segment/query/processor.(*sortProcessor).Process(0x14024402260, 0x1400945d100)
/Users/Kalariya/siglens/pkg/segment/query/processor/sortcommand.go:60 +0xf8
github.com/siglens/siglens/pkg/segment/query/processor.(*DataProcessor).Fetch(0x1402440c080)
/Users/Kalariya/siglens/pkg/segment/query/processor/dataprocessor.go:88 +0xa4
```
Root cause is that for an IQR that is not …
=> Fix sort crash and search issues with the new pipeline

pkg/segment/query/processor/searcher.go
This fixes a panic when PQS had to read multiple blocks in a segment.
There's still an issue to fix, that will come in a future PR. When a segment has multiple blocks and PQS is enabled, on the first query it writes the pqmr file incorrectly; when future queries read the file, they think only one of the blocks in the segment has matches, so query results are inaccurate.
1. Ingest multiple blocks of data into one segment: `go run main.go ingest esbulk -n 1 -g benchmark -d http://localhost:8081/elastic -t 100_000 -p 1
`
2. Restart siglens, to rotate the segment
3. Make sure PQS is enabled
4. Run this query twice: `city=Boston | eval temp_value = http_status%2 | stats count, sum(latitude) BY gender, temp_value`. The first one works correctly (since there's no pqmr data yet); without this PR, …
=> Fix PQS panic when a segment has multiple blocks

pkg/segment/query/metadata/unrotatedmeta.go, pkg/segment/query/segquery.go
- Checks if the SegKey is rotated for Segment Stats Search and assigns the proper search type
- Tested by running the log bench tool and verified that there were no errors.
- All unit test cases pass.
=> Check If SegKey is Rotated for Segment Stats Search

pkg/segment/query/processor/searcher.go, pkg/segment/search/segsearch.go
This fixes the remaining issue mentioned in https://github.com/siglens/siglens/pull/1793
The function that writes the pqmr file previously assumed we already searched all the blocks that we're going to (for that segment). Then it compares that to the blocks that passed CMI to figure out which blocks have no results, and it writes the results in the pqmr file. However, that assumption doesn't hold for the new query pipeline; in the new pipeline, we generally search one block at a time instead of one full segment at a time. This caused the pqmr file to get written like this (for a segment with N blocks):
```
[block 1 results][N-1 blocks with no data][block 2 results][N-1 blocks with no data]...
```
No that function is changed so the file will look like this
```
[block 1 results][block 2 …
```
=> Fix PQS bug in new query pipeline

pkg/ast/spl/tests/splParser_test.go
Fix relative time modifier parsing for month boundaries
When parsing relative time modifiers (-mon@mon, +mon@mon) on the last day of month, adjust the calculation to use current month for earliest and next month + 7 days for latest time range.
=> Fix relative time modifier parsing for month boundaries

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/processor/fillnullcommand.go, pkg/segment/query/processor/renamecommand_test.go, pkg/segment/query/processor/rexcommand.go, pkg/segment/query/processor/rexcommand_test.go
Now [rex](https://docs.splunk.com/Documentation/Splunk/9.1.1/SearchReference/Rex) can be used in the new pipeline
Mostly through new unit tests. I also ran some manual queries like
```
city=Boston | stats count AS Count BY http_status | rex field=http_status "(?<first>\d)(?<second>\d)(?<third>\d)"
```
and a similar version where rex was given an invalid field.
=> Add rex command to new query pipeline

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, tools/sigclient/functionalQueries/eval_fields_timechart.json
- Fixed an issue with Time modifier parsing.
- Added time modifier to the command to snap back to hour.
- All test cases pass
=> fix: change timechart test query to large enough span and add Time modifier to snap back to hour

pkg/segment/query/processor/wherecommand.go, pkg/segment/utils/segconsts.go, tools/sigclient/pkg/query/query.go
This change is for the query `city=Boston | eval nullField1=null() | eval nullField2=null() | eval nullStatus=nullif(http_status, 200) | fillnull value=FILLING nullField1 nullField2 | fields city, http_status, nullField1, nullField2, nullStatus | where nullStatus=null() | stats count(*)`.
Earlier in the old pipeline we were just [logging the error and moving on](https://github.com/siglens/siglens/blob/d96796f01f64b3dd9fdd400bdbf1c5c36519c3d2/pkg/segment/aggregations/segaggs.go#L3653) while computing where command.
All the null fields were generating the error because they were not being converted to float or [string](https://github.com/siglens/siglens/blob/d96796f01f64b3dd9fdd400bdbf1c5c36519c3d2/pkg/segment/utils/segconsts.go#L964) from …
=> Fix for query 293 not working on the new pipeline.

pkg/segment/query/metadata/blockmeta.go
This fixes a bug with PQS in the new query pipeline. For PQS, each segment has a .pqmr file for each persistent query being tracked that stores results for that query. Also, there's one .meta file for the segment storing which of those .pqmr files have no results. There was a bug where that .meta file would have entries that it shouldn't have, causing queries to give too few matches. We were writing to the .meta file after doing CMI checks; this worked for the old pipeline because we do CMI checks for all the relevant blocks in a segment at once; however, in the new pipeline we often to CMI checks for just some of the blocks in a segment, and do checks for other blocks in that segment later (if at all). So in the new pipeline we incorrectly wrote to the .meta file when none of the blocks …
=> Avoid prematurely writing to pqmeta file

pkg/ast/spl/tests/splParser_test.go
- The test was failing in time zones with DST changes because it was hardcoding expected times (noon and end of day)
- During DST transitions, these fixed times would not match the actual times returned by the query parser
- Now, instead of hardcoding expected times, we derive them from the actual times.
=> Fix: Test_ParseRelativeTimeModifier_Chained_2

pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/multicolreader_test.go, pkg/segment/reader/segread/segreader_test.go, pkg/segment/search/filtersearch.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go
- Fixes flooding of error logs due to the error in reading Column files.
- Stores those errors in `NodeResult.GlobalSerachErrors` which will be logged at the end.
- Verified by running the particular queries and observed that error is being logged only once at the end.
=> fix: flooding of error logs from MulticolReader

cmd/startup/startup.go, pkg/config/version.go
=> Bump Version to 0.2.45

pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/querystatus.go, pkg/segment/segexecution.go
Sometimes a query will yield an error instead of a response. In those cases, the UI was erroneously hanging. Now the query gets stopped.
I made `GetStreamedResult()` always return an error, and then ran a query on the UI. Without this PR, the UI would hang and the cursor would spin. With this PR, the error message is displayed on the UI and the query is terminated
=> Stop a UI query if it gets an error

.circleci/config.yml, .circleci/continue-config.yml, .github/workflows/jsformat.yml, .github/workflows/playwright-test.yml, .github/workflows/uts.yml
Currently we run CICD on every PR. When only pkg/config/version.go is changed, we want to skip CICD. If a PR changes that file and other files, we want to run CICD. This PR should make those changes.
For the github workflows, I followed this doc: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-excluding-paths
For CircleCI I followed https://gist.github.com/ryanpedersen42/c867acd9b0837789a92836e8f5bd8b55 from https://support.circleci.com/hc/en-us/articles/10269416203163--Advanced-path-filtering
The diff doesn't show well because I renamed config.yml to continue-config.yml. There I added
```
parameters:
run-tests:
type: boolean
default: true
```
and changed this part to use `when`:
```
workflows:
test_and_lint:
when: << …
```
=> Skip CICD when only the version changes

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/query/querystatus.go, pkg/segment/segexecution.go
- Limit the number of running queries to 100.
- Tested by running parallel queries greater than the limit.
- Verified that siglens only accepts 100 queries and will reject the rest of them.
- Added delay to check the scenario where more than 100 queries are sent but with delay to ensure that only running queries are considered.
=> Limit number of running queries

pkg/config/common/common.go, pkg/config/config.go, pkg/config/config_test.go, pkg/segment/memory/limit/memorylimit.go, pkg/segment/metadata/metadata.go, pkg/segment/structs/memorystructs.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/segwriter.go
1. Moves some limits from segconsts.go into config.go
2. Added a `MaxOpenColumns` config to better estimate how much memory should be reserved for ingestion. However, the limit is not enforced yet.
Unit tests
=> Make memory limits configurable

pkg/segment/query/processor/statscommand.go, pkg/segment/query/processor/statscommand_test.go, pkg/segment/utils/segconsts.go
- The bucket key on the group by is paniced because the buffer allocated for the bucket key is not enough.
- In this PR, it will check the size being written and if that size is not enough then it will increment the buffer.
- Tested by making a new unit test that checked whether the buffer size is being incremented according to column sizes.
- All unit and functional test cases pass.
=> fix: panic on bucket key buffer for Stats Group By CMD

pkg/segment/results/blockresults/blockresult.go, pkg/utils/sliceutils.go, pkg/utils/sliceutils_test.go
The `BlockResults` type was storing at most `MAX_RECS_PER_WIP` results. This caused some issues because sometimes we use one `BlockResults` to store results from many blocks, in particular `SearchResults` uses one  `BlockResults`. Now `BlockResults` can store more records.
```
go run main.go ingest esbulk -n 1 -g benchmark -d http://localhost:8081/elastic -t 200_000
```
Then query:
```
* | eval n=1 | stats count
```
Without this PR, I was getting 84606 on my machine instead of 200k. Now I get 200k.
=> Fix issue saturating block results

.circleci/continue-config.yml
The CircleCI test is required for PRs to merge, so we need to actually run some test; otherwise, CircleCI won't tell GitHub the test was skipped, so GitHub hangs waiting for the test.
Not tested
=> Run dummy CircleCI instead of skipping 

pkg/segment/reader/segread/segreader_test.go, pkg/segment/writer/agiletree.go, pkg/segment/writer/packer.go, pkg/segment/writer/packer_test.go, pkg/segment/writer/rawchecker_test.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segstream.go, pkg/segment/writer/segwriter.go, pkg/utils/buffer.go, pkg/utils/buffer_test.go, pkg/utils/randutils.go, pkg/utils/segutils.go
1. Make a new `Buffer` type that's useful for large buffers that get appended to a lot. Instead of resizing the buffer (and potentially copying all the data to the new buffer), the `Buffer` uses fixed-size chunks of data; when the `Buffer` needs more space it gets a new chunk and updates its internal data structure so it acts like that next chunk is contiguous.
2. Use the `Buffer` instead of `[]byte` during ingestion for the `cbuf` and `dePackingBuf` which store compressed ingestion data
3. Limit the parallelism of flushing columns in a block to files. Each column uses a 2MB `[]byte`, so limiting the parallelism to the number of CPUs greatly reduces the memory usage.
New unit tests, and existing unit/E2E tests
The below ingestion task would OOM my 16GB machine (because it creates a lot of …
=> Reduce ingestion memory via new Buffer type

pkg/config/config.go, pkg/segment/writer/segwriter.go, pkg/utils/buffer.go, tools/sigclient/pkg/query/functional.go
1. Increase active cols to 20K across all indices
2. Fix the memory size estimation for segwriter
=> better estimation of cwip.cbuf size and increase active col limit to 20k

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/dataprocessor_test.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/statscommand.go
- The stats command was panicing because: when we call cancel when a query is in still execution, it would call cleanup and the cleanup would remove the resources, but the actual command processing is still using those resources, which causes the panic.
- And this type of panic can happen to any command data processor during execution.
- Now I have made a flag to know whether to remove the resources or wait and remove the resources.
**UPDATE:**
- I have reverted my previous commit and added a new fields called `processorLock` in the `DataProcessor` struct and call `processorLock.Lock()` before calling `dp.Process()` and also again acquire lock before calling `dp.Cleanup()`.
- Tested by executing this command which will panic on develop branch but will not on this PR.
```
CounterID = 38 …
```
=> fix: processing panic on cleanup

static/js/search.js
First Byte Response Time: Displays the time in milliseconds it took to receive the first byte of the response.
Elapsed Time: Shows the total time taken from the start of the query to its completion.
=> UI : Add First Byte and Elapsed Time to Query Response Info

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/utils/segconsts.go
If a column has some backfilled values and if we groupBy on it, we get the following error
```
GetStreamedResult: failed to get WSResult from iqr; err: IQR.AsWSResult: error getting result: qid=1, IQR.AsResult: error getting final result for GroupBy: IQR.getFinalStatsResults: conversion error for aggGroupByCol variable_col_0 with value:{8 }. Error=CValueEnclosure GetString: unsupported Dtype: 8
```
This is because `CValueEnclosure.GetString` method does not have a way to get string for backfilled value. Changing this method is causing evaluation to break (We often expect errors and assume it as NULL value in evaluation). So, have created a new method to return string for all the types explicitly. When we fix the evaluation to use concrete data types, we will merge …
=> Fix bug for stats if a groupBy column has Backfill value.

pkg/segment/query/processor/rexcommand.go
- If there are no matches `MatchAndExtractGroups` will return an error. We should not log warnings for these cases, rather just ignore the record. By default initialize all the values for newly created columns to be BACKFILLED. 
- The required column values will be overwritten based on the match.
`Referer != "" | rex field=Referer "^https?://(?:www\.)?(?<k>[^/]+)" | fields k | stats count as cnt by k | sort -cnt` query for clickbench dataset was causing log flood.
After this fix, the warnings on no match should not be logged.
=> Fix rex log flood

pkg/hooks/hooks.go, pkg/segment/query/distributedquery.go, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/dataprocessor_test.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/searcher.go, pkg/segment/query/processor/streamer.go, pkg/segment/query/segquery.go
- Calls cleanup for the input stream in the first DP. Based on how the `chainedDp` is set up, we are not initiating cleanup for the input stream of first DP. Now this PR initiates that.
- Also set up less functions for DP.
- All unit tests passed
=> Cleanup for the Input Streams and Set IQR sorting function

pkg/segment/query/processor/rexcommand.go
Earlier a query like this was not working because `GetString` is not working for BACKFILLED values. Use `GetStringForGroupByCol` to get the string value.
```
city=Boston | rex field=variable_col_5 "(?:https?://)(?<uri_segment>[^/]+)" | fields uri_segment, variable_col_18, variable_col_5, variable_col_19 | stats count, avg(variable_col_18) as avg_response, max(variable_col_19) as max_response by variable_col_3 | eval response_category = case( avg_response < 500000, "Fast", avg_response < 1000000, "Medium", avg_response >= 1000000, "Slow") | stats count, avg(avg_response) as avg_response by response_category | sort response_category
```
Describe how you tested this code. How can the reviewers reproduce …
=> Fix GetString for rex

pkg/segment/results/blockresults/blockresult.go
- Fixed Stats group by `nil` column values panic. if for a bucket a value is `nil`, the code is not properly incrementing the idx. Due to which for a function like `List`, `Values`, we might be accessing `sum`, `Range`, or any other function measure result instead of the specific functions measure results.
- Now with this PR through `defer` we can be sure that the idx is incremented properly.
- Ran this query and this passed without any issues
```
variable_col_3=male AND (app_name=Bracecould OR variable_col_7=C*) | regex variable_col_8=".*s" | stats avg(variable_col_4), max(variable_col_19) as max, min(variable_col_18) as min, sum(variable_col_17) as sum, range(variable_col_15), count as cnt, values(variable_col_9), dc(variable_col_6) as distinct_count, list(variable_col_2) BY …
```
=> fix: Group By Nil Columns panic

pkg/segment/query/querystatus.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/results/segresults/segresults.go, pkg/segment/structs/segstructs.go, pkg/utils/errorutils.go
- PR: #1905 Needs to be Merged First.
- Added New Error utils, that is initialized at the start of the query and logs the errors at the end. 
- The Error use a `sync.Map` to avoid locking for every update for performance, but also safe from concurrent map write errors.
- Added `ErrorWithCode` type that is compatible with `error` interface. 
- All unit test cases pass
- And ran the below query and verified that the there is no any log flooding
```
variable_col_3=male AND (app_name=Bracecould OR variable_col_7=C*) | regex variable_col_8=".*s" | stats avg(variable_col_4), max(variable_col_19) as max, min(variable_col_18) as min, sum(variable_col_17) as sum, range(variable_col_15), count as cnt, values(variable_col_9), dc(variable_col_6) as distinct_count, list(variable_col_2) BY …
```
=> Added New err utils to manage Errors and fixed some log flooding with Stats Group By Queries

pkg/segment/results/segresults/segresults.go, pkg/segment/search/searchaggs.go, pkg/segment/structs/segstructs.go, pkg/segment/writer/stats/segstats.go
The below mentioned queries were panicking because of merging on `nil` segstats.
```
* | stats avg(variable_col_4), max(variable_col_18), sum(variable_col_17) | eval temp_value = 1
* | eval n = 1 | stats avg(variable_col_4), max(variable_col_18), sum(variable_col_17) | eval temp_value = 1
variable_col_7=Human http_method != "POST" gender=ma* | stats avg(variable_col_4) as avg, max(variable_col_15), min(variable_col_18), sum(variable_col_17), range(variable_col_19), count, values(variable_col_3), dc(variable_col_2) as distinct_count, list(variable_col_16)
city=Boston | stats count(eval(2)) as cnt_const, count(eval(variable_col_4 > 400)) as cnt_bool, count(eval(variable_col_4+10)) as cnt_exp, count(eval(if(variable_col_4 > 300, 1, 0))) as cnt_if, sum(eval(2)) as …
```
=> Fix stats panic

pkg/segment/search/searchaggs.go
Query: `variable_col_7=Human http_method != "POST" gender=ma* | stats avg(variable_col_4) as avg, max(variable_col_15), min(variable_col_18), sum(variable_col_17), range(variable_col_19), count, values(variable_col_3), dc(variable_col_2) as distinct_count, list(variable_col_16)` 
was causing this log flood 
`segmentStatsWorker found a non string or non-numeric in a dict encoded segment. CName variable_col_3`
=> Fix log flood

pkg/segment/metadata/segmentmicroindex.go, pkg/segment/structs/segmeta.go
We have configurable limits to reduce how much memory siglens can use for various tasks. The `rebalanceSsm()` function was using too much memory because it's estimate for the memory of one segment was too low. This PR fixes that.
Similar to https://github.com/siglens/siglens/pull/1924, but I also reduced the memory allowed for SSM down to 17 MB
Without this fix, `ReadBlockSummaries()` was taking more memory that it should.
=> Fix metadata size calculation

pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go
- We already [set](https://github.com/siglens/siglens/blob/e31a15b3d719ab6fd7a75474cb93c1c214ca489b/pkg/segment/results/blockresults/blockresult.go#L119) the batchErr in Blockresults, we do not need to retrieve it using the `GetOrCreateBatchErrorWithQid` function while Adding measure results to the block.
- Reduces the execution time of this query `* | stats dc(UserID) as u BY RegionID | sort -u | head 10` on 100M Clickbench dataset by 2s.
=> Optimize batchError passing

pkg/segment/results/blockresults/runningstats.go, pkg/segment/writer/segmetarw.go
1. Use the xxhash.Sum64String version and avoid getting mem from bufpool.
2. Reuse sfmData struct when doing cluster stats handling. When there are lot of columns (7800+), this would cause a mem spike of 1.5 GB
with #1 this query now `* | stats dc(UserID) as u BY RegionID | sort -u | head 10` now completes in `8 s` as opposed to `13 s`
=> Spl perf improvements

pkg/segment/query/processor/statscommand.go
- Added safety to log search result errors only when `searchResults != nil`
- tested by running the ci/cd queries
=> stats command panic fix on logging of empty search results

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/timechartcommand.go, pkg/segment/query/processor/timechartcommand_test.go, pkg/segment/structs/evaluationstructs.go
With the new query pipeline, we want to parse to these fields: https://github.com/siglens/siglens/blob/develop/pkg/segment/structs/segstructs.go#L180-L202
This fixes a few commands that were only getting parsed to the old fields.
=> Clean up parsing some commands

pkg/config/config.go
Updated logic for handling missing content in `runmod.cfg`:
- If certain contents are not present in `runmod.cfg`, they will not be defaulted immediately.
- Instead, will check `server.yaml` values before falling back to defaults.
=> Improve default handling in runmod.cfg

pkg/segment/metadata/metadata.go, pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/iqr/iqrreader.go, pkg/segment/query/iqr/iqrreader_test.go, pkg/segment/query/segqueryhelpers.go, pkg/segment/reader/record/mockrecordreader.go, pkg/segment/reader/record/recordreader.go, pkg/segment/utils/segconsts.go
- Now the IQR reader can read from Multiple readers, each tracked with the readerId.
- `IQRReader` has two modes: `ReaderModeSingleReader` and `ReaderModeMultiReader`. In `ReaderModeSingleReader`, the flow is exactly same as now.
- For `ReaderModeMultiReader`, the `IQRReader` will group the RRCs based on the `readerId` and call respective readers with these RRCs and then finally merge the results maintaining the order.
- Added unit tests for the IQR reader
=> Enable IQR to read from Multiple readers

API_README.md, pkg/dashboards/dashboard_test.go, pkg/dashboards/dashboards.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, static/css/siglens.css, static/js/dashboard-from-logs-metrics.js, static/js/dashboards-home.js
Backend Update:
- Previously, three separate API calls were made to fetch dashboards, favorites, and default dashboards.
- Now consolidated into a single API call, with metadata updates to include createdAt, isFavorite, and isDefault, simplifying the dashboard data retrieval process.
Frontend Update:
- Dashboards are now displayed with favorites at the top, sorted by createdAt (most recent first).
- Other dashboards are also sorted by creation time.
- For legacy dashboards (created before this change), the createdAt will default to the last modification time.
- For default dashboards, the createdAt is set to 0.
Before marking your pull request as …
=> Dashboard creation time

pkg/health/clusterStatsHandler.go, pkg/segment/writer/segmetarw.go, pkg/utils/httpserverutils.go, static/cluster-stats.html, static/css/siglens.css, static/js/cluster-stats.js
Updated the index summary on the My Org page to include the following new fields:
- CMI Size: Calculated by summing up all cmi sizes from the .sfm file (full segment metadata) for each segment in the index.
- CSG Size: Calculated by summing up all csg sizes from the .sfm file for each segment in the index.
- Number of Segment Files: Total count of cmi + csg files across all segments in the index.
- Number of Blocks: Extracted from segmeta.json to calculate the total number of blocks in the index.
=> Added Additional Metrics to  Index Summary

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/queryprocessor_test.go, pkg/segment/query/processor/rarecommand.go, pkg/segment/query/processor/searcher.go, pkg/segment/query/processor/statisticexprcommand.go, pkg/segment/query/processor/statscommand.go, pkg/segment/query/processor/statscommand_test.go, pkg/segment/query/processor/timechartcommand.go, pkg/segment/query/processor/topcommand.go, pkg/segment/query/segquery.go, pkg/segment/query/segqueryhelpers.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch_test.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/structs/segstructs.go, pkg/utils/sliceutils.go
- Now the IQR will also have `statsResults` that contains Group By and Segment Stats cmd results in Aggregated format.
- Updated the Gob encoding
- MergeIQRs now also merge these stats from multiple IQR streams.
- Added tests to test the merging of IQR stats.
- Refactored the code for `stats`, `timechart`, `top`, and `rare` commands.
- Added new tests to test the merging of IQR and updated gob encoding/decoding test of IQR.
- All test cases are passed.
- Tested by running some of stats and top/rare queries
=> Enabled IQR to store stats in Aggregated format

pkg/segment/metadata/metadata.go, pkg/segment/query/processor/searcher.go
- We need to skip CMI checks if the results can be obtained from PQMR.
- This [PR](https://github.com/siglens/siglens/pull/1805), fixed a bug regarding results being incorrect because we were skipping even the results if a PQMR result irrespective of the timerange filter. When a large time range is given, this approach can cause issues with some of the blocks in the segment being skipped even though they might have valid results.
- Check if the total number of blocks in the segment is equal to the total number of blocks in the PQMR result. If so, we can safely assume that all of the data in the PQMR result can serve the query correctly without missing any result that could have been expected.
Describe …
=> Skip CMI if PQS data can handle entire segment

pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/segreader.go, pkg/segment/reader/segread/segreader_test.go
Rename `ReadRecordFromBlock()` to `RenameRecord()`; the function used to take the block number as a parameter, but it was only used for logging; the block wasn't loaded if the block number differed from the currently-loaded block number.
I think this function isn't loaded the block as a performance optimization
Unit tests
=> Rename misleading function

pkg/server/query/entryHandlers.go, pkg/server/query/server.go, pkg/systemConfig/systemconfig.go, static/js/settings.js
Updated the "System Configuration" section on the Settings page under "My Org" to include a new row displaying:
- iNodes Total: The number of total iNodes.
- iNodes Used: The number of iNodes currently in use.
- iNodes Available: The number of iNodes still available.
=> Add iNodes Usage Information to System Configuration

pkg/common/fileutils/fileutils.go, pkg/segment/query/iqr/iqrreader.go, pkg/segment/reader/record/mockrecordreader.go, pkg/segment/reader/record/mockrecordreader_test.go, pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/writer/segmetarw.go
- This PR needs to be merged before. #1961 
- `GetColsForSegKey` is returning empty columns map because, the `.sfm` file is not present when populating the micro indices during the loadup. 
- Now this PR fixes this issue.
- Tested by ingesting some data, and then rotating the data.
- All unit test cases pass.
=> fix: Reading of columns

.github/workflows/nightly-longer-functional.yml, pkg/segment/reader/segread/timereader.go
Due to a bug in Go 1.19, scope of the loop variable is per loop not per iteration and thus inserting the same value multiple times in the pool which can cause the same pointer to a slice being returned multiple times.
Refer https://go.dev/blog/loopvar-preview and https://github.com/golang/go/discussions/56010 for more details.
After this fix longer functional should pass for github actions
=> Fix for incorrect timestamps being read when PQS is enabled

.github/workflows/nightly-longer-functional.yml, tools/sigclient/pkg/query/clickbench.go
- Cleanup the logs for clickbench results.
- Ensure it to run all queries and print summary at the end.
- Run longer functional at 3PM and 9PM EST daily.
=> Cleanup clickbench results and schedule longer functional

pkg/segment/metadata/metadata.go, pkg/segment/metadata/metadata_test.go, pkg/segment/metadata/metaupdater_test.go
- Refactor the function names for Getter functions of Global Metadata
- And Add `RLock` before accessing them.
=> refac: Global Metadata get functions

pkg/segment/sortindex/sortindex.go, pkg/segment/sortindex/sortindex_test.go
- JSON marshaling and unmarshaling takes a lot of time for large srt files.
- With this new format we should be able to read information quickly.
- Currently, we are only supporting strings so `writeCValEnc` method is only handling strings. Later we should add support for numbers. The format for the same is specified in the comments.
- Morevoer, when maxRecords are specified, we would want to restrict the number of records to this value and not read anything extra, in the earlier format we were reading all the records in a block. In this new format we would skip reading once we reach `maxRecords`.
- Ran query `SearchPhrase …
=> New format for sort index files

pkg/segment/writer/segmetarw.go
- Exported the function `GetSegFullMetaFnameFromSegkey`
=> refac: Make GetSFMfilename function exported

pkg/segment/query/processor/searcher_test.go, pkg/segment/sortindex/sortindex.go, pkg/segment/sortindex/sortindex_test.go, pkg/segment/sortindex/sortindexmock.go, pkg/segment/utils/segconsts.go, pkg/segment/utils/segconsts_test.go, pkg/segment/writer/segstore.go
The sort index can currently only be written for columns with string values. This refactors that to make it easier in the next PR to allow numeric columns.
Unit tests
=> Refactor writing the sort index

pkg/segment/query/processor/searcher.go, pkg/segment/query/processor/searcher_test.go, pkg/segment/sortindex/sortindex.go, pkg/segment/sortindex/sortindex_test.go, pkg/segment/writer/segstore.go
Previously the sort index only worked for string columns; now it can also handle cases where you sort by numbers or as auto. Each of these sorts has a different sort index file, and the correct file is chosen based on the query.
Some new unit tests. I also manually tested that all the sort index files get written, and that the correct file is read during query.
=> Handle sorting as numbers

.github/workflows/nightly-clickbench.yml, .github/workflows/nightly-longer-functional.yml, .github/workflows/playwright-test.yml, .github/workflows/uts.yml, pkg/segment/query/processor/searcher_test.go, pkg/segment/sortindex/sortindex.go, pkg/segment/sortindex/sortindex_test.go, pkg/segment/sortindex/sortindexmock.go, pkg/segment/utils/segconsts.go, pkg/segment/utils/segconsts_test.go
For the sort index keys/values, we were using a `map[*K]T` instead of `map[K]T`. So for `k1==k2`, if we did `map[&k1] = t1` and `map[&k2]=t2` we'd end up with two entries instead of just one, since the pointers are different.
Manual testing. I wrote the sort indexes for a column with some duplicates. Without this fix, there was one entry per record, and the file size was larger than expected. With the fix, sorting happened much faster (since there's fewer keys) and the file size is the same as when I was using `string` instead of `CValueEnclosure` for keys
=> Fix bug causing duplicate sort keys

pkg/segment/query/processor/searcher.go
Previously, whenever we read from a sort index we tried to read 1000 records. Now we try to read `max(100, sort.Limit / numSegments)`; the `sort.Limit` is usually 10k. This computation is kind of arbitrary; assuming a uniform distribution, we do expect to need `sort.Limit/numSegments` from each sort index; if there's filter criteria we'll generally need more than this (the logic for fetching more records as needed is already setup).
Manually tested with 0 segments and with more segments, printing the batch size.
=> Compute num sort index records per batch

pkg/hooks/hooks.go, pkg/segment/query/segquery.go
- Adds hook for remove usage for a segment
=> Add RemoveUsageForRotatedSegmentForQidHook

pkg/segment/query/processor/searcher.go, pkg/segment/query/processor/searcher_test.go, pkg/segment/sortindex/sortindex.go
Sort index files are created on rotation, so often (e.g., for an unrotated segment) there won't be a sort index file for a particular segment. In that case, we want to do the typical search and sort flow for that segment but use the sort index files for the other segments, and merge the results. This PR does exactly that. Whenever the Searcher has a query that can use a sort index, it makes two subsearchers—one to use sort index files, and the other to do the normal flow. Then `Fetch()`ing from the searcher internally `Fetch()`es from the subsearchers, merges them, and returns the result.
Setup the sort index to use the `address` field, then ran a query to sort on that field. Test with only rotated, only unrotated, and a combination of rotated and unrotated data.
Before marking your pull …
=> Fallback on normal search if missing sort index

pkg/segment/query/processor/sortcommand.go, pkg/segment/utils/segconsts.go, pkg/utils/stringutils.go, pkg/utils/stringutils_test.go
When `strconv.ParseFloat()` errors, it takes some memory on the heap to store the error. We've been calling `ParseFloat()` sometimes just to check if the string can be converted to a float. This leads to a lot of unnecessary allocations.
With this PR, when writing sort index files the memory usage is decreased to about 60% of the original usage, and writing the sort index is about 10% faster.
I have 7.5 million records ingested in one segment, and added a loop on startup to write the sort index for a column with values like `2013-07-03 12:09:10` 5 times, and used pprof to check total allocations. There were about 200k unique values in the column
=> Reduce memory from errors parsing float

pkg/segment/sortindex/sortindex.go
pprof showed that `sort.Slice()` was using a fair amount of memory (a few 100 MBs). After switching to `slices.Sort()`, pprof doesn't show any memory allocations for these lines. This also reduced the time for writing the sort index file by about 8%.
In my test, I was often sorting two-element slices, or a slice of about 10 elements; not sure if that makes any difference.
Same as #2001 
=> Reduce memory from sorting

pkg/segment/query/processor/searcher.go, pkg/segment/sortindex/sortindex.go, pkg/segment/sortindex/sortindex_test.go, pkg/segment/utils/segconsts.go
Previously, using a sort index file would always return the results sorted lowest to highest. Now it can also be used when sorting highest to lowest. To do this, a metadata section is added near the beginning of the sort index file; this metadata specifies the offset within the file for each "line" (see the `type line`).
Note: If the forward sorting of records 1, 2, 3 is 1, 2, 3 and `val(1) < val(2) == val(3)`, then the reverse sort we get from the sort index file will be 2, 3, 1 rather than 3, 2, 1, because both orders are correct but 2, 3, 1 makes reading the sort index file easier.
Unit tests for writing/reading the sort index file both forward and reversed, both with and without a previous checkpoint.
I also manually tested with `* | sort str(EventTime)` and `* | sort -str(EventTime)` …
=> Handle reverse sort using sort index

pkg/segment/reader/metrics/series/seriesreader.go
Each pool element is 150MB, so we can save a lot of RAM when metrics aren't used by starting the pool with no elements. The pool should still create elements as needed.
Started siglens and ingested some data, then ran `go tool pprof -http :8080 localhost:5122/debug/pprof/heap`. Previously, we used 570MB for this pool; now we use 0 when we're not using metrics.
=> Reduce memory by starting pool with no elements

pkg/config/common/common.go, pkg/config/config.go, pkg/config/config_test.go, pkg/segment/writer/segstore.go
Now adding this to server.yaml:
```
memoryLimits:
lowMemoryMode: true
```
will cause siglens to use slightly less memory, but be slightly slower. The only place this config matters right now is when data is flushed to disk, but we may want to make similar changes other places as well.
Ingested some data, waited for it to flush to disk, then ran `go tool pprof -http :8080 localhost:5122/debug/pprof/heap`. Without this change, I saw about 40MB used for `ResizeSlice()` on my 10-CPU machine; with this PR, it went down to 2MB
=> Add low memory mode

pkg/segment/sortindex/sortindex.go, pkg/segment/writer/segstore.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
API endpoint to set sort columns & non-API function to retrieve those columns name.
```
curl -X POST \
http://localhost:5122/api/sort-columns \ 
-H 'Content-Type: application/json' \
-d '["timestamp", "app_name"]'
```
=> API endpoint to set sort columns & non-API function to retrieve columns name

cmd/startup/startup.go
- Logs SigLens version on Bootup
- Tested by running the server and verifying that the version is being logged at the server log and also in the `siglens.log` file.
=> Log SigLens version on bootup

pkg/config/config.go
- Logs whether memory is from `os` or from `cgroups`
- Tested by running the siglens server and ensured that the logs were being displayed
=> Log memory fetch source

pkg/hooks/hooks.go, pkg/segment/writer/segmetarw.go, pkg/segment/writer/segstore.go
- Removes Segment Rotation Hook
=> Cleanup segment rotation hook

pkg/es/writer/esDocIndexingHandler.go, pkg/hooks/hooks.go, pkg/server/ingest/entryHandlers.go, pkg/server/ingest/server.go
This adds support for endpoints like `elastic/<index>/_doc endpoint`, which can be used to add a single row to the index
This fixes an issue when running in kubernetes with the k8sExporter in the [helm chart](https://github.com/siglens/charts/tree/main/charts/siglens). The k8sExporter uses this endpoint, but it was failing since the endpoint wasn't setup. 
1. Setup a k8s on minikube
2. Installed the [helm chart](https://github.com/siglens/charts/tree/main/charts/siglens)
3. Started (`kubectl run test-nginx --image=nginx`) and stopped (`kubectl delete pod test-nginx`) a pod to generate a kubernetes event
4. Waited 10 seconds, then queried siglens and saw the event logs in the `kubernetes-events` index
=> Handle ES endpoint to add single row

pkg/config/version.go, pkg/es/writer/esDocIndexingHandler.go, pkg/hooks/hooks.go, pkg/server/ingest/entryHandlers.go, pkg/server/ingest/server.go
- Adds an elastic search endpoint for ingesting a single row. This fixes an issue with the k8sExporter when using the [siglens helm chart](https://github.com/siglens/charts/tree/main/charts/siglens)
=> Release 1.0.9

pkg/ingest/ingestionStats.go, pkg/instrumentation/metrics.go, pkg/instrumentation/ssgauges.go, pkg/segment/query/segquery.go, pkg/segment/query/summary/querysummary.go, pkg/segment/writer/segwriter.go
Refactors how we create gauges to reduce boilerplate code and make it easier to add a new gauge. I'll add more gauges in the next PR
1. Start siglens
2. Run `curl localhost:2222/metrics` to see our metrics
3. Ingest data
4. Wait 1 minute (`ingestionMetricsLooper()` loops every minute)
5. Run `curl localhost:2222/metrics` again and see the updated values for our ingestion metrics
=> Reduce gauge creation boilerplate

pkg/common/fileutils/fileutils.go, pkg/common/fileutils/fileutils_test.go, pkg/ingest/ingestionStats.go, pkg/instrumentation/ssgauges.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/query/metricsquery.go, pkg/segment/writer/metrics/metricssegment.go, pkg/usageStats/stats.go
This adds a gauge for each of the following; the gauges are updated each minute.
- Export number of metric names
- Export metric for number of time series
- Number of datapoints per minute
- Number of tag keys (across all metric names)
- Number of tag values 
- Number of bytes on disk for metric data
Ingested some data with `go run main.go ingest metrics -d http://localhost:8081/otsdb -t 25_000  -m 5 -p 1` and manually  check the output metrics using `curl localhost:2222/metrics`
=> Export metrics about metric ingestion

static/alert.html, static/css/metrics-explorer.css, static/css/siglens.css, static/js/alert.js, static/js/common.js, static/js/metrics-explorer.js
1. Resolved the issue on the Metrics Explorer screen where opening the function dropdown caused the window to slide when the query was large.
2. Fixed the bug where hovering over a metric name and clicking outside would change the metric name but not update the data.
3. Corrected the issue where the alert name was not displaying in the Alert Details and Edit screens.
Screenshots of the issues - 
=> Metrics Explorer UI Fix

pkg/segment/memory/limit/memorylimit.go
- Resets the segment search bytes value to the initial allocated search bytes during rebalance. 
- While rebalancing the memory assigned to segment search can be lower than the initial assignment and it needs to be reset to the initial value in the next rebalancing.
- Tested by running siglens on a docker container with `2GB` of ram.
- Set the memory threshold to `10%` and ran logs and metrics ingestion.
- Quickly the allocated memory for search became `0` and through logs I have verified it is being reset and may become `0` again depending on the ingestion or writer memory.
=> Fix: Reset segment search memory to Initial Allocated Value during rebalance

pkg/segment/memory/limit/memorylimit.go
- Allocated available memory to `segsearch` and then make available memory to `0`.
=> fix: Allocate remaining memory to SegSearch during rebalance

pkg/segment/memory/limit/memorylimit.go, pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/metrics/metricssegment_test.go
- Included only the current block size for metrics in memory calculation, ignoring the flushed or rotated blocks.
- Tested by running some ingestion and observed the global memory print summary. And the values keep changing.
- When the ingestion is stopped, the metrics in memory size came to `0`.
=> Fix: Calculation of In Memory Metrics size

go.mod, go.sum, pkg/server/certreloader.go, pkg/server/ingest/server.go, pkg/server/query/server.go, pkg/utils/eventutils.go, pkg/utils/eventutils_test.go
Previously, when you wanted to use a new TLS certificate (e.g., it's going to expire soon), you had to copy the new certificate to the correct file and restart siglens. Now you just have to copy the new certificate to the correct file. Siglens automatically reloads it when the certificate or private key changes.
1. Create a certificate that expires soon (see below)
2. Setup TLS config in server.yaml:
```
tls:
enabled: true   # Set to true to enable TLS
certificatePath: "certs/localhost.short.crt"  # Path to the certificate file
privateKeyPath: "certs/localhost.key"   # Path to the private key file
```
3. Start siglens
4. Start continuous ingestion to https
```
go run main.go ingest esbulk -n 1 -g benchmark -d https://localhost:8081/elastic -c
```
6. Wait for the certificate to expire, …
=> Reload TLS cert when it gets updated

pkg/segment/writer/unrotatedquery.go
- This is not being tracked correctly before because when rebalancing, we set the `cmiLoaded` to false, and then from next rebalancing the allocated memory for that segment is not being deleted.
- And even when at the final stage when the segment is being removed, since the `cmiLoaded` is set to `false`, the cmi size won't be included.
- This made the `TotalUnrotatedMetadataSizeBytes` increase in value.
- Tested by keeping the memory usage to 10% and memory size to `2GB`
- Ran the ingestion. And verified that the `TotalUnrotatedMetadataSizeBytes` was being removed properly during rebalance and removal of segment in memory after rotation
=> fix: Global Unrotated Metadata Size Tracker

pkg/diagnostics/diagnosticCollector.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, static/css/siglens.css, static/diagnostics.html, static/js/diagnostics.js, static/js/navbar.js
Added a new backend API (`api/collect-diagnostics`) to facilitate the collection of diagnostic data. Currently, the API gathers basic index details displayed on the Cluster Stats page for each index. We will add more diagnostic data collection to the API later.
The backend API calls the `api/clusterStats` endpoint to retrieve cluster data, organizes it into separate JSON files for each index, compresses the files into a ZIP archive, and makes the archive available for download.
Also, added a new "Diagnostics" tab to the "My Org" page in the UI. Users can download the collected diagnostic data.
Before marking your pull request as ready for review, …
=> Add Diagnostic Data Collection Feature

pkg/segment/writer/segmetarw.go, pkg/segment/writer/segmetarw_test.go
This fixes an issue introduced by #2049 causing a bug when trying to delete all the segmeta entries for a particular index
New unit tests
=> Fix bug in removeSegmetas function

pkg/segment/query/processor/searcher.go
The old code had a bug when `subsearchers[1].segEncToKeyBaseValue` was non-zero when `subsearchers[1]` was initialized, which caused merging results to fail because the same encoding was used for two different segkeys.
=> Fix segkey encoding when lacking sort index file

.github/workflows/publish-prod-images.yml
Our github workflow on releases broke. This is an attempt to fix that. The issue appears to be that when we try to make the release, the tag does not exist. So this PR creates the tag if it doesn't exist already. I'm not sure if this will fully fix our release workflow
Manually tested on my fork, and the tag creation job ran correctly: https://github.com/AndrewHess/siglens/actions/runs/12873074246
=> Create tag on release

pkg/ingest/ingestionStats.go
When there's no metric data, we were getting an error log every minute. Now we don't.
=> Fix calculation for metrics disk space when it's 0

eslint.config.mjs, pkg/diagnostics/diagnosticCollector.go, pkg/server/query/entryHandlers.go, static/js/diagnostics.js
Instead of calling the `clusterStats` API, now calling the `ProcessClusterStatsHandler`.
Also, added a hook for the `clusterHandler`.
=> Diagnostic Collector Fix

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertutils/alertutils.go
Previously when updating an alert, we'd parse the whole alert from the API request and use that as the new version of the alert. However, we only want to update certain fields with this API, so the old way was clearing out some fields that should have been unchanged.
This PR fixes that issue and makes it more clear which fields are expected in the API request.
Manually created an alert, then edited it. The new values were updated, and the other fields remained unchanged.
=> Fix issue updating an alert

benchmark_test.go, cmd/startup/startup.go, pkg/es/reader/resolveIndexHandler_test.go, pkg/es/writer/esBulkHandler_test.go, pkg/hooks/hooks.go, pkg/segment/query/queryrefresh.go, pkg/segment/segexecution_test.go, pkg/segment/writer/unrotatedquery_test.go, pkg/server/ingest/entryHandlers_test.go, pkg/virtualtable/virtualtable.go, pkg/virtualtable/virtualtable_test.go
- Currently there is an issue that the we update the virtual table file with the same table names when the server is started.
- This PR fixes that issue.
- And also uses go routines to update the data all at once as bulk, instead of doing one at a time.
- Refactors and removed some of the other code.
- Tested by starting the server with no data and ingested across multiple indexes.
- Kill the server, verify the local file with proper index names.
- Restart the server and verify that the indexnames are not duplicated.
=> Maintain Virtual table names and avoid duplicate appends to virtual table files.

pkg/integrations/prometheus/ingest/putmetrics.go, pkg/integrations/prometheus/ingest/putmetrics_test.go, pkg/server/ingest/entryHandlers.go
Fixes issue ingesting metrics when the ID is not zero
Tested by running the OpenTelemetry Demo as described in https://github.com/siglens/siglens/pull/2098
=> Ingest metrics using proper ID

pkg/segment/utils/segconsts.go, pkg/segment/writer/packer.go, pkg/segment/writer/segwriter.go, tools/sigclient/functionalQueries/functionalQueries.yml, tools/sigclient/functionalQueries/variable_col_tests/var_9stats_groupby_2col.json, tools/sigclient/functionalQueries/variable_col_tests/var_bin.json
We have two ways to store types: as `VALTYPE_XXX` and as `SS_DT_XXX`. We were incorrectly casting from one type to the other. Now we do the conversion correctly.
**Update:** The original version of this had some failing tests in the functional suite. This happened because `initMicroIndices()` was passed a VALTYPE instead of an SS_DTYPE and the string VALTYPE is the signed integer SS_DTYPE. `initMicroIndices()` is called when a column needs to be backfilled, so when we were supposed to backfill a field as a string column, we'd actually backfill it as a numeric column. The functional suite tests failed because the tests were created on ingested data that had this bug. In particular, some columns like SSN and Zip Code have numeric data that's actually ingested as a string. In our variable …
=> Fix incorrect type conversion

pkg/integrations/prometheus/ingest/putmetrics.go, pkg/otlp/otlp.go, pkg/usageStats/stats.go
- Now Traces Ingest Stats will be logged in the per-minute stats.
- Tested by ingesting some traces
- Verified that I see the traces stats.
=> Log Traces and myid in the per minute stats

pkg/otlp/otlp.go, pkg/otlp/utils.go, pkg/utils/httpserverutils.go
This shouldn't change any behavior. It's intended to make it easier to add OTLP log ingestion in the next PR. Then the package structure will be something like
- utils.go
- traces.go
- logs.go
- (eventually) metrics.go
I was still able to manually ingest traces using the OpenTelemetry Demo with this config
```
exporters:
otlphttp/siglens:
endpoint: "http://host.docker.internal:8081/otlp"
prometheusremotewrite:
endpoint: "http://host.docker.internal:8081/promql/api/v1/write"
processors:
batch:
send_batch_size: 5000
timeout: 10s
service:
pipelines:
traces:
exporters: [spanmetrics, otlphttp/siglens]
metrics:
processors: [batch]
exporters: [prometheusremotewrite]
```
=> Refactor OTLP trace ingestion

pkg/integrations/prometheus/ingest/putmetrics.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/packer.go
=> fix: flooding of error log lines

pkg/ast/pipesearch/searchHandler.go, pkg/segment/tracing/handler/tracehandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go, pkg/utils/httpserverutils.go, pkg/utils/httpserverutils_test.go
- Added new API to get logs related to the traces. 
- The response would be exactly same as http API response. 
- Ingested Logs and Traces through otel-collector-demo
- Executed the api in postman by setting the searchText as `traceId=<id>` and `spanId=<id>` and verified that the results are there.
=> feat: Add API and handler to get logs related to traces

pkg/alerts/alertsHandler/alertsHandler.go
Mostly cosmetic changes. The one change in behavior is that there's a different error returned when making an invalid type of alert
Not tested
=> Tidy alert validation function

static/css/siglens.css, static/css/tracing.css, static/js/common.js, static/js/log-results-grid.js, static/js/search-traces.js, static/js/trace.js
1. Tooltip on bubble chart on the search-trace page displaying trace details with two options:
- View Traces: Navigates to the Gantt chart view.
- Related Logs: Opens the log search screen in a new tab with prefilled search parameters.
2. On the trace/Gantt chart screen: "Logs for this Trace" and "Logs for this Span" buttons now open the log search screen in a new tab with prefilled search parameters.
- Prefilled search parameters for related logs include:
```
Search Text = traceID=""
StartTime = traceStartTime - 15 mins
EndtTime = traceStartTime + 15 mins
Mode = Code
Query Language = Splunk QL
Index = trace-related-logs
```
Before marking your …
=> UI: Correlation b/w Logs and Traces 

pkg/otlp/logs.go
This is because otel traces already use snake case, and we want to be consistent. See traces.go.
Ingested logs with the otel demo, and saw column names used snake case.
=> Use snake case for otel log column names

pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/structs/querystructs.go, pkg/segment/tracing/handler/tracehandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
- Added the changes to identify trace-related-logs index and replaced it as `*`
UPDATE:
- Added this replacement of indexname to `*` at `ParseSearchBody` as this function is being used by both websocket and http handler.
- Tested by running ingestion through otel-collector.
- And verified traces to logs through the UI.
=> Traces to logs through websocket and http handler

pkg/alerts/alertsHandler/alert_test.go, pkg/alerts/alertsHandler/alertsHandler.go, pkg/ast/pipesearch/searchHandler.go, pkg/segment/structs/segstructs.go, pkg/segment/structs/segstructs_test.go
1. Requires queries for log alerts to contain exactly one measure column
2. Fixes a bug: all indexes were being searched for log alerts; now the correct indexes are searched
3. Adds unit tests
Previously, we were able to create an alert that has multiple measure columns, but then the alert would fail when it was evaluated. Now we reject those queries when creating/updating an alert
**Note:** There's still an issue with queries that have something before a `stats` block (e.g., `* | eval latencyMs = latency / 1000 | stats avg(latencyMs) as avgLatencyMs by weekday`). We're able to create these alerts, but then the evaluation fails and so the alert never fires. I didn't find an easy fix for this, so I'll make a ticket for it.
New unit tests, and manually tested creating/updating alerts on the …
=> Require exactly one measure agg for log alerts

API_README.md, pkg/segment/tracing/handler/tracehandler.go, pkg/server/query/entryHandlers.go, pkg/server/query/server.go
endpoint: api/traces/span/ganttChart
method: POST
Example:
request: http://localhost:5122/api/traces/span/ganttChart
body:
{
"startEpoch": "now-1h",
"searchText": "span_id=a98166653c6f7f44"
}
Finds the corresponding trace_id from the span_id and generates a gantt chart according to it. If the span_id does not have a corresponding trace_id, it returns an error of an orphaned span_id state. 
Right now it only logs a comment if there are more than 1 associated traces to a span_id, but later on this case should be handled properly. 
=> Generate Gantt Chart by SpanID

pkg/integrations/prometheus/promql/parser.go
In parsePromQLQuery, we parse an expression using parsePromQLExprNode. However if this fails and returns an error, we weren't returning an error and instead continued the function, resulting in a divide by zero error when using a faulty expression or one that wasn't implemented yet.
This change returns an error and reports a Syntax Error if this function fails. 
=> Returns error if parsing a metric expression in PromQL fails

static/alert.html
Manually added alerts with negative and non-integer thresholds and verified they fired when appropriate.
=> Allow alerting on negative/non-integer thresholds

pkg/alerts/alertsqlite/alerts_sqlite.go, pkg/alerts/alertsqlite/alerts_sqlite_test.go
1. Extract a helper function for replacing the alert message template with the final message
2. Test that function
3. Decode the base64 query text (we store it encoded in the SQL DB) so the final message shows the proper text
New unit tests. Also tested manually by making an alert with a template message
=> Fix bug with query text in alert message

pkg/e2etests/metrics_e2e_test.go, pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/metricresults_test.go
- Fixed issue with regex tag filtering for queries that require fetching of all labels.
- Fixed issue with regex querying on both metric name and tags.
- Added Unit test cases that test cases 
- regex tag filtering with group by
- regex on metric name with regex tag filtering with group by on tags
- regex on metric name with regex tag filtering with group by on tags + metric
- regex on metric name with negative regex tag filtering with group by on tags
- Ran queries like below on UI:
```
count by (job, jvm_thread_state) (jvm_thread_count{job=~"kafka", jvm_thread_state=~".+"})
```
=> Fix metrics regex queries

pkg/config/common/common.go, pkg/config/config.go, pkg/config/config_test.go, pkg/server/ingest/server.go, pkg/server/query/server.go, pkg/server/utils/utils.go, server.yaml
Adds the ability to configure siglens to run with mTLS. If enabled, the clientCA file must also be provided.
Manually tested with dummy certificates. For the normal TLS certificate: 
```
mkcert localhost
```
For the client cert and key I ran this:
```
CAROOT=$(mkcert -CAROOT)
openssl genpkey -algorithm RSA -out client.key
openssl req -new -key client.key \
-subj "/C=US/ST=State/L=City/O=Org/CN=client@example.com" \
-out client.csr
cat > ca.cnf << EOF
[ ca ]
default_ca = CA_default
[ CA_default ]
dir               = .
database          = index.txt
new_certs_dir     = .
certificate       = ${CAROOT}/rootCA.pem
serial            = serial.txt
private_key       = ${CAROOT}/rootCA-key.pem
default_md        = sha256
policy            = policy_anything
x509_extensions   = v3_client
[ …
```
=> Add support for mTLS

static/css/siglens.css, static/js/log-results-grid.js
Added an expand icon next to timestamo in log table, single line and multi-line view.
screen shot for changes:
=> Added expand icon next to timestamp 

.github/workflows/uts.yml, .golangci.yml, Makefile, pkg/e2etests/e2e_utils.go, pkg/e2etests/metrics_e2e_test.go
This sets up a framework for E2E testing and adds a simple test to verify metrics persist after graceful shutdown and restart
The build directive `//go:build e2e_all` was added so that `make test` skips these tests so it's still easy/quick to run just the unit tests. All the tests can be run with `make test_all`.
New test
=> Setup E2E testing framework

pkg/otlp/logs.go
Now if the TraceID/SpanID is not set in the otel log, but the corresponding `attribute` _is_ set, then we'll use that value. The purpose of this is to make it easier for people to associate a log with a trace/span when they're sending otel logs to siglens and the trace/span isn't already set.
Manually tested with the otel demo with this config
```
exporters:
otlphttp/siglens:
endpoint: "http://host.docker.internal:8081/otlp"
prometheusremotewrite:
endpoint: "http://host.docker.internal:8081/promql/api/v1/write"
processors:
batch:
timeout: 10s
attributes:
actions:
- key: "span_id"
value: "123"
action: "insert"
- key: "trace_id"
value: "abc"
action: "insert"
service:
pipelines:
traces:
exporters: [spanmetrics, otlphttp/siglens]
metrics:
processors: [batch]
exporters: [prometheusremotewrite] …
```
=> Get span and trace IDs from otel log attributes

pkg/utils/fileutils.go, pkg/utils/fileutils_test.go
Adds a function to atomically write a file either in append or truncate mode, though the append mode will be inefficient if the file already has a lot of data.
New tests
=> Add util for atomically writing files

pkg/ast/pipesearch/addTimechart_test.go, pkg/ast/pipesearch/multiplexer/queryStateMultiplexer.go, pkg/ast/pipesearch/multiplexer/queryStateMultiplexer_test.go, pkg/ast/pipesearch/searchHandler.go, pkg/ast/pipesearch/searchHandler_test.go, pkg/ast/pipesearch/wsSearchHandler.go, pkg/segment/segexecution.go, pkg/segment/structs/resultStructs.go, pkg/segment/structs/segstructs.go, pkg/segment/tracing/handler/tracehandler.go
When we get a websocket query that returns logs, now when a flag is set for that query, we'll also run a timechart version of that query and forward those results to the websocket, along with the results for the original query.
This PR shouldn't change any functionality on the UI, because the new feature is turned off by default.
Some new unit tests for individual components of this. For integration testing, I made [these changes](https://github.com/user-attachments/files/18876635/diff.patch) to display the timechart results on the frontend and it sort of worked. Those frontend changes aren't quite correct, so it actually replaced the resulting logs with the timechart results, but I was able to see the timechart in the Visualization tab as expected.
Before marking your pull request as …
=> Add backend for automatic timechart query

pkg/memorypool/memorypool.go, pkg/segment/query/processor/inputlookupcommand.go, pkg/segment/reader/segread/agiletreereader.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/utils/aggutils.go, pkg/segment/utils/number.go, pkg/segment/utils/segutils.go, pkg/segment/writer/segstore.go, pkg/segment/writer/segwriter.go, pkg/segment/writer/segwriter_test.go, pkg/segment/writer/startree_test.go, pkg/utils/buffer.go, pkg/utils/mathutils.go, pkg/utils/segutils.go
https://github.com/siglens/siglens/blob/e67725c1f8266d3cf7ed6bdcc6c0cad19f419d2a/pkg/utils/segutils.go#L98-L99
This PR replaces min/max helpers (`MinInt`, `MaxInt`, `MinInt64`, etc.) with built-in `min` and `max` functions. We can use the built-in `min` and `max` functions since Go 1.21.
Reference: https://go.dev/ref/spec#Min_and_max
```
make test
```
=> Replace min/max helpers with built-in min/max

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/utils/dateutils.go
- Fixed the response for promql instant query API
- Tested by verifying the results from Prometheus response and SigLens response
=> fix: promql response format for Instant queries

pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/structs/metricsstructs.go, pkg/segment/structs/metricsstructs_test.go
- Separated the response formats for Range and Instant Queries
- Added a custom Marshaling for Instant Response Query
- Added unit test for custom Marshaling.
- Tested by adding SigLens as a Prometheus data source on Grafana.
- Tested by running queries manually on Prometheus and SigLens
=> Separate response structs for PromQL Range and Instant Queries

pkg/e2etests/metrics_e2e_test.go, pkg/integrations/prometheus/promql/parser.go, pkg/integrations/prometheus/promql/parser_test.go, pkg/segment/query/metricsquery.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/metricresults_test.go, pkg/segment/structs/metricsstructs.go
- Add support for PromQL without aggregation.
- Tested on UI by running the below queries
1. `sum without (instance) (demo_api_http_requests_in_progress)`
2. `sum  without(instance) (avg_over_time(demo_api_http_requests_in_progress[3h:30m]))`
- Added few functional unit tests.
- TODO: Need to add tests for parser and other functional unit tests.
- Added Tests for parser and an e2e test.
=> Add support for PromQL without Aggregation operator

pkg/integrations/prometheus/promql/parser.go
- Ensures that the minimum step value is 1 second.
- Without this for instant queries, the step is getting set to `0.04s` causing the query to execute very slow.
- Tested by running the below query on Grafana by selecting Instant query
```
max without(instance, le) (max_over_time(demo_api_request_duration_seconds_bucket{job="demo"}[1d]))
```
=> Set minimum step value to 1 second

pkg/segment/reader/metrics/tagstree/tagstree_test.go
The test was occasionally failing here: https://github.com/siglens/siglens/blob/develop/pkg/segment/reader/metrics/tagstree/tagstree_test.go#L337-L344, so I 10x the number of iterations. If this is still flaky, we may need a better way to fix the test
=> Make flaky test more rare

install.sh, install_with_docker.sh
This PR updates the installation shell scripts to replace all references to the deprecated `docker-compose` command with the `docker compose` command, in accordance with Docker’s migration guidelines. This change ensures compatibility with Docker Compose V2, which is now the standard.
Fixes #1311
I executed the updated installation script on Fedora Workstation 41.
Verified that Docker is installed by running `docker --version`.
Confirmed that Docker Compose V2 is installed by running `docker compose version` and ensuring the output reflects a V2 version.
Finally, I ran additional commands (such as logs and down) to ensure all Docker Compose operations work as expected.
=> Update docker script for v2 compatibility

static/js/metrics-explorer.js
Previously, the metrics graph end time was always set to "now," custom end time set . 
This fix ensures that the graph respects the custom end time provided.
=> Fix: Use Custom End Time for Metrics Graph

pkg/segment/tracing/handler/tracehandler.go
Fix: Handle missing "startEpoch" and "endEpoch" keys in request body JSON parsing  
- Sanitized the code so that if a key is not present, it logs an error and returns control.  
- Replaced hardcoded error messages with constants for better maintainability.
=> Fix: Handle missing "startEpoch" and "endEpoch" keys 

pkg/segment/writer/metrics/tagstree.go
When adding tags to the tags tree for a certain TSID, sometimes we erroneously skipped adding the tags because we got a false positive from a bloom filter, so we thought the TSID was already added.
This just removes the bloom filter check, as `tth.addTags()` should already correctly handle a call for tags that are already there.
=> Fix issue not adding some tags to tags tree

pkg/segment/reader/metrics/series/seriesreader.go, pkg/segment/utils/segconsts.go, pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/metrics/metricssegment_test.go
The previous TSO file format reserved 2 bytes for the number of TSIDs, which caused an overflow issue when there were too many. Now we reserve 8 bytes.
Existing and new unit tests. I also tested manually that I could still query metrics that were ingested using the old TSO format, and that I could query metrics ingested using the new format.
=> Fix overflow issue in TSO file

pkg/integrations/prometheus/ingest/putmetrics.go, pkg/segment/results/segresults/segresults.go
fix panic in SplunkQL query due to Index out of range
- Ensured applyAggregationsToResult gracefully skips missing attributes.
- Fixed log line that was printing data as bytes by converting it to string before logging.
=> fix panic in SplunkQL query due to Index out of range

static/js/metrics-explorer.js
**Issue:** 
The metrics name dropdown lags significantly when loading and filtering options. This performance issue occurs because we're loading all metrics names (2500+) into the dropdown at once, causing the UI to become unresponsive during initialization and filtering operations.
**Fix:** 
- Implemented a lazy loading approach for the metrics dropdown
- Initially show only the first 20 items when dropdown opens
- Added scroll detection to dynamically load more items as the user scrolls down
Tested with 2500+ metrics names from the sandbox2.siglens.com machine
=> Fix Performance Issues with Metrics Name Dropdown

static/alert.html, static/css/metrics-explorer.css, static/js/metrics-explorer.js
**Issue:**
Previously, all legends were displayed without scrolling, taking up too much space and making the graph hard to view. Also, clicking a legend would only hide that one, while others remained.
**Fix:**
- Scrollable Legends: Legends are now placed inside a scrollable container to avoid taking over the graph space.
- Improved Legend Toggle:
- Clicking on a legend shows only that legend's line on the graph (hides others).
- If only one legend is visible and it's toggled, all legends are shown again.
- Multi-select Support: By pressing Shift and selecting multiple legends, we can view more than one line on the graph at a time.
Before marking …
=> Fix: Scrollable Legends with Improved Selection Behavior for Metrics Graph

tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go
This PR is a temporary fix and should get reverted once a certain bug is fixed. I tried to fix the bug in https://github.com/siglens/siglens/pull/2356, but then tests in the functional test suite started failing.
The bug is: sometimes we return records for a query and those records are correct, but the `allColumns` field contains some fields that none of the records have data for.
This bug causes the longevity test to fail in ~40 seconds. With this "fix", the longevity test has run for 5 minutes.
=> Don't validate allColumns in longevity test

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go
This adds the following queries to the longevity test suite:
```
state_c1=Texas | stats count
app_version_c1=1.2.3 | stats count
```
It's also easy to any other query like `key=value | stats count`
New unit tests 
=> Add stats count queries to the longevity test

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go
1. Handle wildcard queries in the longevity test, and add some to the suite
2. Fix an issue with `key=value` queries where `value` has spaces
New unit tests, and manually ran longevity
=> Add wildcard searches to the longevity test

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go, tools/sigclient/pkg/utils/numbers.go
Now the longevity test can run queries similar to `key=value | sort col1`
A few notes:
1. Only numeric sort columns are handled so far
2. When no sort column is specified, we sort on timestamp
3. The sort is always descending (this makes it easy to fallback to sorting on timestamp)
New unit tests. Also, running the longevity test seems to work, with output like this:
```
INFO[0286] queryManager.runQuery: successfully ran query=city_c1="New *" | head 10, timeSpan=1s (1742250517363-1742250518363), got 10 matches
INFO[0286] queryManager.runQuery: successfully ran query=city_c1="Boston" | head 10, timeSpan=1s (1742250517363-1742250518363), got 3 matches
INFO[0287] queryManager.runQuery: successfully ran query=city_c1="Boston" | head 10, timeSpan=1s (1742250518457-1742250519457), got 6 matches …
```
=> Add sort queries to the longevity test

tools/sigclient/pkg/query/queryvalidator.go
The `filterQueryValidator` previously stored the results in reverse order; this was a small optimization while handling logs, when we were always sorting based on timestamp. With a recent PR making it possible to sort on other columns, that optimization is not applicable, and storing the results in reverse adds unneeded complexity; so this PR stores them in the correct order.
Existing unit tests pass, and the longevity test seems to run the same.
=> Refactor filter query validator for longevity test

cicd/metrics_test.csv, pkg/integrations/prometheus/promql/parser.go, pkg/integrations/prometheus/promql/parser_test.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/results/mresults/seriesresult_test.go, pkg/segment/structs/metricsstructs.go
- Fixes the queries with Tag Filters.
- Before the response for a query in this format: `metric{tk1:tv1, ...tkn:tv1}`, would only return series displaying only the tags given in the query. 
- But with this PR, it will return all the labels and series.
- All unit test cases pass
- Updated metrics cicd queries
=> Fix metric tag filter query

static/css/tracing.css, static/js/search-traces.js
Issues Fixed: 
1. Previously, the scatter chart displayed normal trace bubbles and then another timeline specifically for errors, causing redundancy.
2. When there were too many spans, the bubble size became too large, making the chart unreadable.
Fix: Implemented a logarithmic scaling function to dynamically adjust bubble sizes based on the span count.
=> Fix: Tracing Scatter Chart Timeline

pkg/segment/reader/metrics/tagstree/tagstreereader.go, pkg/segment/writer/metrics/tagstree.go, pkg/utils/errorutils.go
- Checks if the error is due to file not found, if it is continue processing next tags, otherwise return error
- Reduced error log flooding
- Tested by ingesting some metrics data for sometime.
- Ingest different types of metrics. Run the query and make sure new metrics can be queried.
- Kill the server and Ingest metrics again. And query to ensure there are no errors
=> Do not thrown err when tags tree file does not exist

pkg/segment/writer/metrics/metricssegment.go
- Since for an unrotated metric segment, even when there is an issue while reading the Block summary file, we still need to consider the current unrotated block for that segment.
=> Continue searching even when there is an error reading the Metric Block summary file

pkg/segment/query/segquery.go, pkg/segment/search/filtersearch.go, pkg/segment/search/segsearch.go, pkg/segment/search/segsearch_test.go, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/queryvalidator.go
Previously, running this query
```
curl -X POST \
-d '{
"searchText": "app_version_c1=\"1.2.3\" | stats count",
"startEpoch": 1742406660826,
"endEpoch": 1742406669826,
}' http://localhost:5122/api/search | python -m json.tool | less
```
would incorrectly give 8 results while running the corresponding non-stats query:
```
curl -X POST \
-d '{
"searchText": "app_version_c1=\"1.2.3\"",
"startEpoch": 1742406660826,
"endEpoch": 1742406669826,
}' http://localhost:5122/api/search | python -m json.tool | less
```
would correctly give 4 results.
Additionally, both queries incorrectly logged that 8 records matched in the QuerySummary:
```
WARN[2025-03-20 12:39:29] qid=2, pqid 4417048619338014975, …
```
=> Check time range of records in stats query

pkg/segment/search/filtersearch.go, tools/sigclient/cmd/sigclient.go
This fix is similar to https://github.com/siglens/siglens/pull/2393. However, that PR missed an edge case where we're filtering on a dict-encoded column and so we don't check each record. This PR handles that edge case.
Ran the longevity test. Now stats queries on dict-encoded columns also work (e.g., `state=Texas | stats count`)
=> Always check record timestamps when block is split

pkg/segment/search/filtersearch.go, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go
Similar to #2395 and #2393 but for match-all queries
Ran the longevity test with the added queries. Running the longevity test with the new queries but without the bug fix causes the test to fail
=> Check timestamp on match-all queries

pkg/ast/pipesearch/searchQueryParser.go, pkg/segment/segexecution.go
Previously, running the query:
```
curl -X POST \
-d '{
"searchText": "* | stats count",
"startEpoch": "now-30d",
}' http://localhost:5122/api/search
```
would give these logs:
```
INFO[2025-03-21 11:00:59] qid=1, ParseAndExecutePipeRequest: index=[Raw Index: [*] Expanded To 11 Entries. There are: 0 Elastic Indices. Sample: [ind-0 ind-1 ind-2 ind-3].....], searchString=[* | stats count] , startEpoch: 1739984459150, endEpoch: 1742576459150
INFO[2025-03-21 11:00:59] qid=1, parsePipeSearch output:
INFO[2025-03-21 11:00:59] qid=1, ASTNode for Splunk QLquery parser: {"AndFilterCondition":{"FilterCriteria":[{"MatchFilter":{"MatchColumn":"*","MatchWords":["Kg=="],"MatchWordsOriginal":[null,"Kg=="],"MatchOperator":1,"MatchPhrase":"K …
```
=> Reduce unneeded logging on each query

static/dashboard.html, static/js/metrics-explorer.js, static/metrics-explorer.html
- The previous default color palette used in Metrics Explorer did not provide distinction between multiple metrics.
- Updated the default color palette to use a more contrasting and visually distinct set of colors.
=> Fix - Updated Default Color Palette for Metrics Explorer

pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/segquery.go, pkg/segment/query/summary/querysummary.go, pkg/segment/query/summary/querysummary_test.go, pkg/segment/segexecution.go
In some error paths, we were starting a goroutine to watch a ticker (started by `InitQuerySummary()`), but we weren't properly closing that goroutine. This PR fixes that with a `Cleanup()` method that's safe to call multiple times.
1. New unit test
2. Manually forced an error creating a QueryProcessor (that's one of the error paths we didn't handle properly), and ran a query. Previously, we'd get "still executing" logs every 10 seconds; with this PR, we don't.
=> Fix goroutine leak in query summary

pkg/blob/blobStorage.go
- Removed logging of errors from the blob error functions, as they are logged by the caller.
=> Removed log lines from blob functions

pkg/utils/debugutils.go, pkg/utils/segutils.go, pkg/utils/segutils_test.go
1. A function to get the segkey given any filepath belonging to that segment
2. A function for debugging, which returns the callers of the current function. Similar to `debug.Stack()`, but much more concise
=> Add util functions

pkg/e2etests/metrics_e2e_test.go, pkg/integrations/prometheus/promql/metricsSearchHandler.go, pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go, pkg/segment/structs/metricsstructs.go
- Implements the Instant Query for Metrics similar to Prometheus, except the reset of data when the `up` metric for the instance is `0`.
- Tested by ingesting data into  Prometheus and SigLens
- Ran same instant query through Grafana. 
- Verified that the values are same for some queries.
- Added a new unit test case.
=> Promql instant query Support

tools/sigclient/pkg/query/querymanager.go
Previously, if a query in the longevity test required X minutes of data, we'd only run that query once the longevity test had been running for X minutes. With this PR, we'll start that query earlier—if the test's been running for `Y` minutes, we'll start the query and use `min(X, Y)` minutes of lookback.
I ran the longevity test with just one query that should run every 5 seconds with a 5 minute lookback. With this PR, it started querying much sooner:
```
INFO[0065] queryManager.runQuery: successfully ran query=city_c1="Boston" | head 10, timeSpan=5s (1743176939160-1743176944160), got 10 matches
INFO[0070] queryManager.runQuery: successfully ran query=city_c1="Boston" | head 10, timeSpan=10s (1743176939160-1743176949160), got 10 matches
INFO[0075] queryManager.runQuery: successfully ran …
```
=> Add initial queries to longevity test

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go
Now instead of hardcoding all the queries in the longevity test, we have some queries that will look at the data being ingested and choose a random, valid filter—either a `key=value` pair that matches at least one log, or a match-all if there is no such pair.
New unit tests. I also ran the test with just some of the dynamic queries, and got a good variety of `key=value` pairs:
```
INFO[0448] queryManager.runQuery: successfully ran query=hobby_c5="Frisbee" | stats count, timeSpan=1s (1743184958697-1743184959697), got 1 matches
INFO[0449] queryManager.runQuery: successfully ran query=gender_c4="male" | stats count, timeSpan=1s (1743184959708-1743184960708), got 341 matches
INFO[0449] queryManager.runQuery: successfully ran query=image_c3="https://picsum.photos/135/349" | head 10, …
```
=> Add dynamic queries to the longevity suite

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/querymanager.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go
Previously the queries in the longevity suite would only query over the time range that the longevity test was running, so that we'd know exactly what the expected result is. This PR adds some other queries that run over a much longer time range (30 days), but have less validation since we're not sure what the expected result is (e.g., siglens could have preexisting data before the longevity test is started)
=> Add queries with long time range to longevity suite

pkg/segment/reader/segread/timereader.go
In an error path, there's a loop `continue` (line 406) that caused an infinite loop because the loop index wasn't updated. This PR fixes that.
Not tested
=> Fix infinite loop in error path

pkg/ast/pipesearch/multiplexer/queryStateMultiplexer.go, pkg/ast/pipesearch/searchHandler.go, pkg/otlp/logs_test.go, pkg/segment/query/querystatus.go, pkg/segment/query/summary/querysummary.go, pkg/segment/segexecution.go
- Log the Metrics Query Summary every 10 seconds by fetching metrics query state.
- This is so that we know whether the query is actually or waiting in the queue.
- Tested by running multiple metrics query through K8s dashboard UI.
- Observed that the logs were being printed query state (WAITING, RUNNING)
=> Log Metrics Query Summary With Query State

tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/query/querymanager.go
1. Add more monitoring to the longevity test
2. Prevent overwhelming the system by limiting the number of query validators
In a long running longevity test, the server running the test was getting overwhelmed because we were adding queries faster that we were able to remove them (by running the query and verifying the results). This lead to too much RAM usage. This PR should fix that; if it doesn't, at least we'll have additional monitoring to see what's going wrong.
=> Avoid overwhelming the system with query validators

pkg/segment/query/querystatus.go, pkg/segment/structs/segstructs.go
There's at least one path for concurrently storing errors:
```
github.com/siglens/siglens/pkg/segment/structs.StoreError(...)
/siglens/pkg/segment/structs/segstructs.go:1729
github.com/siglens/siglens/pkg/segment/structs.(*NodeResult).StoreGlobalSearchError(...)
/siglens/pkg/segment/structs/segstructs.go:1720
github.com/siglens/siglens/pkg/segment/search.filterRecordsFromSearchQuery(0xc143e0d110, 0xc086e422f0?, 0xc0efdcf940, 0xc0003de700, 0xc0e3c80680, 0x139, 0xc113cc1110, 0x9057, 0xc0d5066f70, 0xc1346ca070, ...)
/siglens/pkg/segment/search/filtersearch.go:297 +0xb9c
github.com/siglens/siglens/pkg/segment/search.filterBlockRequestFromQuery(0xc0003de700, 0xc143e0d110, 0xc086e422f0, 0xc060e80540, 0xc0efdcf940, 0x44c43d?, 0x1, 0x1, 0x9057, 0xc0d5066f70, ...) …
```
=> Fix concurrency bug when storing errors

tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go, tools/sigclient/pkg/utils/strings.go, tools/sigclient/pkg/utils/strings_test.go
We don't yet support searching for non-ASCII values, but the longevity test had some dynamically generated queries that would occasionally choose non-ASCII values to query for. This PR fixes that.
=> Make longevity test only select ASCII values

tools/sigclient/pkg/query/queryvalidator_test.go, tools/sigclient/pkg/utils/numbers_test.go
This fixes the query validators in the longevity test from incorrectly failing with:
```
msg="queryManager.runQuery: incorrect results for query=gender_c2=\"male\" | stats count, timeSpan=32m24s (1743743499409-1743745443409), validation=strict, got 1044750 matches; err=CQV.MatchesResult: invalid count type float64 in measure[0] value map[count(*):1.04475e+06]"
```
The issue was that `1.04475e+06` is large enough that it got formatted in a way that can't directly be parsed as a uint.
New unit tests
=> Fix longevity test validator parsing large numbers

pkg/segment/results/mresults/metricresults.go, pkg/segment/results/mresults/seriesresult.go, pkg/utils/dateutils.go
- Fixes the issue with metrics instant query not showing any data for range vectors.
- Tested with kubernetes dashboard on the UI
- All unit test cases pass
=> fix: Metrics range vector query through Instant Query

pkg/segment/reader/segread/segreader/segreader.go, pkg/segment/reader/segread/timereader.go, pkg/segment/search/segsearch.go, pkg/segment/segexecution_test.go, pkg/segment/writer/segwriter.go, pkg/utils/checksumfile.go, pkg/utils/checksumfile_test.go
Use https://github.com/siglens/siglens/pull/2484 to read/write .csg files with checksum validation. Reading is backward compatible.
New and existing unit tests. I also manually tested by ingesting 2 blocks of data on `develop`, then ingesting 2 more blocks on the tip of this feature branch and running queries, to verify backward compatibility. All the queries worked as expected.
=> Write CSG files in checksummed chunks

pkg/health/clusterStatsHandler.go
Caller is responsible for passing the correct org id. Remove the redundant check.
=> Remove the redundant extraction of org id when processing usage stats

static/js/common.js, static/js/usage-stats.js, static/usage-stats.html
The Usage Stats graph should have a dynamic time axis so that labels adjust based on the selected time range.
=> UI: Usage Stats

pkg/health/clusterStatsHandler.go
* Org Id is passed as a parameter to processing usage stat request. It should not be extracted from the request headers.
=> Removing redundant org extraction

static/css/query-builder.css, static/css/siglens.css, static/js/available-fields.js, static/js/search.js
**Issue**: Previously, long field names in the fields sidebar were truncated with no way for the user to view the full name.
**Fix:**
- Added functionality to resize the fields sidebar.
- User can now drag to adjust the width.
- The selected width is saved in `localStorage` to persist the sidebar state across sessions.
https://github.com/user-attachments/assets/b89c6d69-0f69-4890-9571-2fcf6c899bde
=> UI: Resizable Fields Sidebar

static/component/infrastructure/header-component.js, static/component/time-picker/time-picker.js, static/css/siglens.css, static/js/event-handlers.js, static/js/kubernetes-overview.js, static/js/kubernetes-view.js, static/js/metric-summary.js, static/js/metrics-cardinality.js, static/js/metrics-explorer.js, static/js/service-health-overview.js, static/js/service-health.js, static/js/usage-stats.js
Added validation to prevent users from selecting an end time earlier than the start time in the custom timepicker.
If such a selection is made:
- A warning message is shown.
- Search is not triggered.
- The warning auto-dismisses after a few milliseconds, allowing the user to correct their selection.
=> Fix: Custom Timepicker Validation

Makefile, pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go, shell.nix
This deviates from https://docs.splunk.com/Documentation/Splunk/7.3.1/Knowledge/Aboutregularexpressionswithfieldextractions#Proper_field_name_syntax by allowing field names with `-` and `/` for SPL queries.
It also updates the Makefile so you can run
```
make pkg/ast/spl/spl.go
```
instead of
```
pigeon -o pkg/ast/spl/spl.go pkg/ast/spl/spl.peg
```
New unit tests. Also manually tested with `account-balance>100` and `account/balance>100`—now these give no results (because those fields don't exist in my dataset) but previously they gave a parsing error.
=> Allow slash and dash in SPL field names

static/cluster-stats.html, static/css/query-builder.css, static/index.html, static/js/common.js, static/js/log-search.js, static/js/search.js
- Implemented a default search when the user lands on the Logs screen, now automatically runs: `* | head 10`.
- Improves user experience by immediately showing sample data.
=> UI: Default Search on Logs Screen

pkg/segment/query/metricsevaluator/evaluator.go, pkg/segment/query/metricsquery.go, pkg/segment/query/metricsquery_test.go, pkg/utils/sliceutils.go, pkg/utils/sliceutils_test.go
See title. One interesting thing: Prometheus always returns the series for a range query in a certain order (see [the doc](https://prometheus.io/docs/prometheus/latest/querying/api/#range-vectors)), but while they say "Series are returned sorted by metric" and the [`sort_by_label`](https://prometheus.io/docs/prometheus/latest/querying/functions/#sort_by_label) function uses normal sort, it seems that Prometheus uses lexicographical sort rather than normal sort on the series for a range query.
New unit test. Also ingested some test data and then queried:
```
curl -G 'http://localhost:5122/promql/api/v1/query_range' \
--data-urlencode 'query=testmetric0' \
--data-urlencode 'start=1745347400' \
--data-urlencode 'end=1745347500' \
--data-urlencode 'step=10s' | jq
```
and the results looked …
=> Handle range queries that return multiple series

pkg/segment/reader/record/recordreader.go, pkg/utils/sliceutils.go, pkg/utils/sliceutils_test.go
For logs queries without a `stats` block, at the end of the query we have to read all the columns for all records that matched. We were doing this one column at a time; with this PR it's done in parallel. This improves query response times, but allocates about 50% more memory.
1. Ingest:
```
go -C tools/sigclient run main.go ingest esbulk -n 2 -g benchmark -d http://localhost:8081/elastic -t 1_600_000 --enableVariableNumColumns --maxColumns 200
```
2. Run queries:
```
latency_c1<100000 AND question_c1="*truck*to*"
question_c1="*truck*to*"
*
```
3. Check the response time from the logs like:
```
INFO[2025-04-25 16:27:16] qid=2, Finished execution in 931.176292ms
```
With this PR, the corresponding query response times were: 1080 ms, 109 ms, 61 ms
Without this PR, the response times were: …
=> Increase performance of reading all columns

.circleci/config.yml
The path-filtering orb is not working , it gives a error since it is no longer supported on python 3.8 version.
Temporarily removing the path-filtering orb and letting circle ci run all the time.
=> fix circle ci python 3.8 issue

pkg/regex/regex.go, pkg/regex/regex_test.go, pkg/segment/utils/segconsts.go, pkg/utils/bufutils.go, pkg/utils/bufutils_test.go
Many regex searches are simple wildcard searches. These are not optimized in Go's regexp library; this PR optimizes them, yielding a 10x improvement for some queries.
Ingested 100 million records, then ran these queries:
```
* | regex URL = ".*google.*" | stats count
URL = "*google*" | stats count
```
(for the second query, we translate it to a regex query under the hood).
Previously, the queries took 32.9 and 29.9 seconds respectively. With this PR, they take 3.3 and 5.4 seconds.
There's one known issue: regex like `^.*foo.*$` won't match something like `line1\nline2fooinfo` because there's a line break, but the regex implementation in this PR doesn't consider line breaks at all (it treats them as any other character). This will be fixed in a later PR.
For the first query, CPU profiling …
=> Optimize regex searches

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/iqrreader.go, pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/multicolreader.go, pkg/utils/errorutils.go, pkg/utils/errorutils_test.go
There was a call to `iqr.getColumnsInternal()` that was both expensive (for certain queries) and largely unneeded (we only used the result to check for one specific column). This PR removes that.
Ingested 100 million records and ran
```
CounterID = 62 AND IsRefresh = 0 
| where strptime(EventDate,"%Y-%m-%d") >= strptime("2013-07-01", "%Y-%m-%d") AND strptime(EventDate,"%Y-%m-%d") <= strptime("2013-07-31", "%Y-%m-%d") 
| eval Src=if(SearchEngineID=0 AND AdvEngineID=0, Referer, "") 
| rename URL as Dst 
| stats count as PageViews by TraficSourceID, SearchEngineID, AdvEngineID, Src, Dst 
| sort -PageViews 
| head 1010 
| tail 10 
| tail 10
```
This used to take ~100 seconds; now it takes ~8 seconds.
=> Optimize column reading

pkg/segment/reader/segread/segreader/segreader.go
This small changes saves about `2.2s /13 s` on the below query: 
```
SearchPhrase != "" | regex Title = ".*Google.*" | regex URL != ".*\.google\..*" | stats count as c, min(eval(URL)), min(eval(Title)), dc(UserID) by SearchPhrase | sort -c | head 10
```
=> improve query perf

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/iqr/record.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/searcher.go, pkg/segment/query/processor/sortcommand.go
This slightly improves the speed of `sort` queries. Previously to compare two records, we'd read the values for their sort columns on the fly; now we read all the values for the sort columns up front, and then reference them as needed.
Did CPU profiling on this query:
```
SearchPhrase != "" 
| sort 10 str(EventTime)  
| fields SearchPhrase
```
with a 100 million record dataset. The response time varied some, but on average it was about 20 seconds previously, and 17 seconds with this PR.
=> Optimize sort

static/css/query-builder.css, static/css/siglens.css, static/index.html, static/js/download-logs.js, static/js/query-builder.js, static/js/saved-query.js, static/metrics-explorer.html
Styling Improvements for Popups on Logs and Metrics Screen
1. Create Dashboard Popup - 
2. Create Alert Popup - 
3. Save Query popup-
=> Fix: Styling Improvements for Popups

pkg/segment/reader/segread/segreader/segreader.go
Did CPU profiling on the query `SearchPhrase != "" | sort str(EventTime) | head 10 | fields SearchPhrase`.
Before:
```
Total:       1.95s      2.02s (flat, cum)  8.51%
737            .          .            
738            .          .           	dWord := sfr.deTlv[dwIdx] 
739            .          .           	return dWord, nil 
740            .          .           } 
741            .          .            
742            .          .           func (sfr *SegmentFileReader) AddRecNumsToMr(dwordIdx uint16, bsh *structs.BlockSearchHelper) { 
743            .          .           	// If validRecords is nil, then all records are considered valid; 
744            .          .           	// otherwise, only those in validRecords can be added to the results. 
745            .          . …
```
=> Optimize loop

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/searcher.go, pkg/segment/reader/record/recordreader.go, pkg/utils/sliceutils.go, pkg/utils/sliceutils_test.go
Read blocks in parallel. This reduced the query time for `SearchPhrase != "" | sort str(EventTime) | head 10 | fields SearchPhrase` from about 17 seconds to about 13 seconds.
=> Read blocks in parallel

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go
Reduce memory allocations for moving slices by allocating the right amount the first time. This doesn't seem to have an affect on the query execution time.
Tested on this query: `SearchPhrase != "" | sort str(EventTime) | head 10 | fields SearchPhrase` and used the `allocs` pprof profile
Before
```
(pprof) top
Showing nodes accounting for 9744.24MB, 86.15% of 11311.12MB total
```
After
```
(pprof) top
Showing nodes accounting for 8793.45MB, 87.49% of 10050.94MB total
```
=> Reduce allocations for slice movement

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/iqr/intermediateQueryResult_test.go, pkg/segment/query/processor/sortcommand.go, pkg/utils/heap.go, pkg/utils/heap_test.go
When sorting records and only taking the top few, this PR speeds up the query by using a heap instead of sorting all the records (in the batch).
This query: `SearchPhrase != "" | sort str(EventTime) | head 10 | fields SearchPhrase` takes about 11 seconds both before and after this PR. But changing it to `SearchPhrase != "" | sort 10 str(EventTime) | fields SearchPhrase`, it takes about 10.2 seconds before this PR and 7.8 seconds after the PR.
=> Use a heap to sort faster

pkg/segment/query/processor/statscommand.go, pkg/segment/query/processor/timechartcommand.go, pkg/segment/reader/segread/agiletreereader.go, pkg/segment/results/blockresults/blockresult.go, pkg/segment/results/blockresults/runningstats.go, pkg/segment/results/blockresults/runningstats_test.go, pkg/segment/search/searchaggs.go, pkg/utils/sliceutils.go
Previously when computing aggregations, we'd make a map for each record, mapping the measure columns to their values. These short-lived maps caused a lot of allocations and work for the garbage collector. With this PR, we make just one map per batch of records.
Tested on this query:
```
URL != "" | stats avg(eval(len(URL))) as l, count as c by CounterID | where c > 100000 | sort -l | head 25
```
Before: took 16 seconds and 60 GB
```
(pprof) top
Showing nodes accounting for 59922.54MB, 98.72% of 60699.58MB total
```
After: took 13 seconds and 23.5 GB
```
(pprof) top
Showing nodes accounting for 23.27GB, 99.28% of 23.44GB total
```
=> Reuse map to avoid allocations

pkg/segment/structs/evaluationstructs.go
Before this PR, the below query used to take `105 s` , after this PR it takes `85 s`
query: 
```
Referer != "" | rex field=Referer "^https?://(?:www\.)?(?<k>[^/]+)" | stats avg(eval(len(Referer))) as l, count as c, min(eval(Referer)) by k | where c > 100000 | sort
```
=> avoid string creations during sending errors

pkg/segment/writer/segstore.go
The [panic](https://sigscalr.slack.com/archives/C02999B0A49/p1746267979762769) in addMicroIndicesToUnrotatedInfo occurs when [blockNum](https://github.com/siglens/siglens/blob/f8b214cd84aec683c80b6275d258436ebe99349d/pkg/segment/writer/unrotatedquery.go#L271) reaches 65535. The fix is to rotating segment when about to reach it.
=> Fix for panic when segment blockNum reaches MaxUint16

static/js/query-builder.js
**Issue:** 
Previously, once a filter in the query builder (column name, symbol, and value) was added, users could only **delete and recreate** it if they wanted to make any changes.
**Fix:** 
Clicking on an existing filter now populates the input fields (column, operator, and value) with the current filter’s data, allowing users to **modify and update** it without needing to delete and recreate.
=> UI: Allow Editing Existing Filters in Query Builder

pkg/segment/query/processor/dataprocessor.go, tools/sigclient/cmd/sigclient.go, tools/sigclient/pkg/ingest/ingest.go, tools/sigclient/pkg/query/querymanager.go, tools/sigclient/pkg/query/queryvalidator.go, tools/sigclient/pkg/query/queryvalidator_test.go
When the longevity test suite encounters a failing query, if that query matched a record that siglens may have duplicate records for (because ingestion had to be retried), log that as a a warning instead of an error.
Not tested
=> Log as warning when server may have duplicates

pkg/alerts/alertsHandler/alertsHandler.go, pkg/alerts/alertsHandler/notificationHandler.go, pkg/alerts/alertutils/alertutils.go
* Configures a http client to ignore ssl certificate validation / check
* Use the http client when verifying webhook config (contact point) and when invoking webhook to send alerts
=> Ignore SSL Cert validation in webhook

pkg/segment/query/processor/searcher.go
See this comment:
```
// We chose the blocks using s.cutOffTimestampInMs, so we can only return
// RRCs up to that time; if we returned records past that time, then we
// can't guarantee the records we return are in the correct order
// considering ALL data we have.
```
The issue was that we'd determine a cutoff time, then use that to determine which blocks we needed to search, and then we'd search all of those blocks and return the records from them before getting the next batch of blocks. This lead to some records getting returned out of order.
For example, say we're returning records in the recent-first order, and we have blocks
```
block 1: lowTs=10, highTs=20
block 2: lowTs=15, highTs=25
block 3: lowTs=25, highTs=30
```
and our cutoff time is 23—so we want to return all records with …
=> Fix bug causing records to be read out of order

pkg/segment/query/processor/searcher.go
With [this fix](https://github.com/siglens/siglens/pull/2643) in previous PR, sometimes the Searcher gets a batch of blocks to search, and has some leftover blocks when it gets the next batch of blocks. This revealed a new issue: we were comparing SSRs by pointers instead of doing a deep-equal type of comparison; this caused [this error](https://github.com/siglens/siglens/blob/d3b46e70ce5de6a1f59dab071123f4476481c3dc/pkg/segment/query/processor/searcher.go#L1495) to get triggered on a false positive when blocks from this batch and the previous batch have the same SSR underlying data, but different SSR pointers. This PR fixes that.
I was able to trigger the error by ingesting 1 million records (so there's several blocks) into index 0, then another 1 million split between index 0 and 1 (and …
=> Check for SSR equality

pkg/segment/tracing/utils/buildspantree.go
Previously if you went to the Gantt chart view for a trace and refreshed the page, the spans would be in a different order (and sometimes get assigned different colors, as a result). Now refreshing the page doesn't change anything, and the chart flows from left to right better since we're sorting on start time
=> Make Gantt chart ordering deterministic

pkg/segment/tracing/handler/tracehandler.go
When making the Gantt chart, we query for spans in chunks of 1000. Previously we'd only break out of the loop when a query returned 0 spans, which lead to the last query being unnecessary in most cases. This avoids that last query (unless this trace has a multiple of exactly 1000 spans).
I didn't test this with 1000 spans in one trace. But I did view the Gantt chart for a trace with fewer spans and checked the logs. Before this we made 2 queries; now we make 1 query.
=> Remove unnecessary final query in Gantt chart

pkg/segment/tracing/handler/tracehandler.go, pkg/utils/sliceutils.go
Speed up searching on the /search-traces.html page by running fewer queries.
Previously when doing a search on that page, we'd get a batch of traceIDs and then do two additional queries per trace ID. With this PR, we combine the queries so we do two additional queries total for the batch, instead of two additional per trace.
With 4 million spans and about 840k traces, doing a basic search for the traces used to take about 11 seconds. Now it takes 2.5 seconds.
=> Speedup trace search

pkg/segment/results/blockresults/blockresult.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go
This avoids iterating all the records (and allocating memory for RRCs, which causes significant GC cycles) for timechart queries. This reduces query time by about 25%
Manually verified these queries gave the same results with and without this PR:
```
* | timechart span=1m count
* | timechart span=1m avg(ConnectTiming)
* | timechart span=1m count by ConnectTiming
```
=> Avoid unneeded record iteration in timechart

pkg/segment/query/segquery.go
This should improve query performance when:
1. The number of segments matching the query exceeds half the number of vCPUs, and
2. There's some idle CPUs
=> Double file parallelism

pkg/segment/reader/segread/multicolreader.go, pkg/segment/search/searchaggs.go
If a bad timestamp column is given in the config, timechart queries were very slow because they'd add an error for each record. Now we add just one error, so the query completes much faster.
Ingest data, then in server.yaml change the `timestampKey` to something else, then restart and run a query like `* | timechart span=1m count`. Now the query completes much faster, and we see one of these errors in the logs:
```
ERRO[2025-05-15 15:31:32] qid=1, addRecordToAggregations: Failed to extract timestamp from record, Count: 7182, ExtraInfo: uninitialized time reader
```
=> Reduce repeated errors on invalid timestamp field

pkg/segment/pqmr/pqmatchresults.go, pkg/segment/search/searchstatus.go
For the query `* | timechart span=1m count` this reduced the time from 1.50 seconds to 1.35 seconds.
=> Reduce time to initialize bitset

pkg/segment/results/blockresults/blockresult.go
- minor code change, but this part of the code now takes `410 ms` vs `640 ms` previously for the query `* | timechart span=1m count`
=> do map lookup once

static/css/siglens.css, static/index.html, static/js/download-logs.js, static/js/pagination.js
- Added a new option to select the download scope when exporting logs:
- Current View – Downloads only the data currently loaded in the UI.
- All Records – Downloads up to a maximum of 10,000 records.
- When "All Records" is selected, a warning is shown.
=> Download All Records for Logs Query

pkg/segment/reader/metrics/series/seriesreader.go, pkg/segment/reader/record/recordreader.go, pkg/segment/reader/segread/agiletreereader.go, pkg/segment/reader/segread/dechecker.go, pkg/segment/reader/segread/multicolreader.go, pkg/segment/reader/segread/segreader/segreader.go, pkg/segment/reader/segread/timereader.go, pkg/segment/search/searchaggs.go
If we get errors in the common path, we will likely get a lot of them. This PR uses constant errors for those to avoid needing to allocate heap memory for each error, which could cause GC pressure and slow down the system.
Not tested
=> Use constant errors in fast path to reduce allocs

pkg/segment/aggregations/timechartagg.go, pkg/segment/aggregations/timechartagg_test.go, pkg/segment/query/processor/timechartcommand.go, pkg/segment/search/searchaggs.go, pkg/segment/search/segsearch.go
For `url_c1=http* | timechart span=1m count` we would create a slice of equally-spaced buckets (1 minute apart in this case) for each block. This caused some unnecessary allocations to keep creating this slice. Moreover, we only used the slice to determine which bucket a particular timestamp belongs in. Since the buckets are equally spaced, this PR replaces the slice with a struct, and we can find the correct bucket for a timestamp with simple arithmetic instead of binary search.
Added unit tests to ensure no behavior change.
pprof reported about 50% fewer bytes allocated, and the query ran about 5% faster.
=> Delete unnecessary allocations

static/js/search.js
Problem:
When the backend takes too long to respond with the first query_update, users had no indication of progress.
Fix: 
As soon as a query is initiated, we now immediately show a progress bar and set it to 1%.
=> UI: Improved Progress Bar Feedback

static/js/common.js
Problem: The code was using `toISOString()` on a Date object, which always returns time in UTC, leading to incorrect custom time display for users in different time zones.
Fix: Correctly format and display the custom time based on the user’s local timezone.
=> Fix: Display Correct Custom Time with Timezone

pkg/segment/query/processor/searcher.go
This removes a check that was causing false-positive errors.
The old code stated that all the blocks should have the same PQMR, but that's not quite necessary. They should be PQMRs for the same segment (and if you look up the chain of callers, you'll see that they are) so they should have the same info, but it _is_ valid for them to be different actual PQMR structs. Since different blocks for the same segment can be added in multiple calls to `getBlocks()`, we'll sometimes have blocks for the same segment with different PQMR structs—this was the false-positive error getting triggered.
=> Remove unnecessary PQMR check

pkg/segment/reader/segread/dechecker.go, pkg/segment/search/conditioncheck.go
Some cases in https://github.com/siglens/siglens/blob/5db0233beaaefdba6eacad2283928fbe29b2edca/pkg/segment/search/conditioncheck.go#L190 were misleading because they'd have `found, err := ...` and then return `found`; that return value was used to determine if record-level searching is necessary, and in all queries we'd get `found = false`. This is sort of correct (because we don't want to do record-level searching), but misleading—and the inner function calls had comments saying they return true if a match is found, but instead always returned false.
I think the only change in behavior is a few calls to https://github.com/siglens/siglens/blob/5db0233beaaefdba6eacad2283928fbe29b2edca/pkg/segment/search/conditioncheck.go#L303 will be correct now (since `found` is sometimes `true`; …
=> Cleanup misleading code

pkg/segment/aggregations/timechartagg.go
1. timechart queries without eval work fine.
2. timechart queries with distinct_count  and eval  cause siglens to crash. eg -> `* | timechart span=1m dc(eval('account.balance'>5000)) BY account.created_data.country` crashes but `* | timechart span=1m avg(eval('account.balance'>5000)) BY account.created_data.country` works fine.
3. only happens during merging of time buckets when `useAdditionForMerge=false` [here](https://github.com/vsharma-va/siglens/blob/90715059ce2df2af2f028c085addb2757f59ac55/pkg/segment/aggregations/timechartagg.go#L449).
4. which activates [this](https://github.com/vsharma-va/siglens/blob/90715059ce2df2af2f028c085addb2757f59ac55/pkg/segment/aggregations/timechartagg.go#L379) block in the code. `(hllToMerge = nil)`
=> Fix: prevent panic during hll merging for timechart queries

static/css/siglens.css, static/js/common.js, static/js/event-handlers.js, static/js/log-results-grid.js, static/js/logs-histogram.js, static/js/pagination.js, static/js/search.js
1. Hide JSON Popup on Error/Empty Results
The JSON viewer popup will now automatically hide if - the query returns an error or the result set is empty.
2. Pagination Fixes
Previously, the UI - displayed 100 records per page regardless of the selected page size and on Load more we are showing all the records instead of the selected page size. 
Fixed these two issues in the PR.
=> UI Fix: JSON Popup and Pagination

pkg/segment/aggregations/evalaggs.go, pkg/segment/query/processor/rexcommand.go, pkg/segment/structs/evaluationstructs.go, pkg/segment/utils/segconsts.go
- Use constant errors
- Use fast float parsing, the strconv.ParseFloat constructs a syntaxError struct which is expensive in hot path, avoid it
- minor optimzations in `MatchAndExtractNamedGroups`
This query `Referer != "" | rex field=Referer "^https?://(?:www\.)?(?<k>[^/]+)" | stats avg(eval(len(Referer))) as l, count as c, min(eval(Referer)) by k | where c > 100000 | sort 25 -l`
develop: takes `85 s` 
with this PR: `55 s`
with this PR and #2748 : takes `27 s`
=> use const errors, use fast float parsing

static/css/query-builder.css
Fixed issue where the search textarea would collapse unexpectedly when the user clicked on the last line, especially if the query has a lot of lines.
=> Fix: Search Textarea Auto-Collapse Issue

pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/queryprocessor.go
We call `AggsToDataProcessors()` when setting up a query, and it used to have side-effects for certain queries. This made it difficult to correctly call it multiple times, which we want to do when parallelizing a query.
This PR separates the side-effect part of the code so we can call that just once and then call `AggsToDataProcessors()` multiple times without worrying about additional side-effects. This PR shouldn't cause any behavior changes.
CICD
=> Refactor query setup to separate side-effect

pkg/segment/reader/record/recordreader.go
We were doing:
```
for each item in slice:
for key, value in map:
```
This PR switches it to:
```
for key, value in map:
for each item in slice:
```
Because iterating maps in Go has more overhead than iterating slices, so we want to reduce the amount of map iterations.
Tested on 100 million records:
```
* | eval height=ResolutionHeight / 10 | stats avg(height) as avg, count(height) as count, sum(height) as sum by ResolutionWidth | sort -ResolutionWidth
```
This PR decreased the total real time from 10.8 seconds to 9.7 seconds. The CPU time of `readAllRawRecords()` dropped from 6.7 seconds to 3.3 seconds.
=> Improve performance by swapping nested loops

pkg/segment/structs/evaluationstructs.go, tools/sigclient/functionalQueries/functionalQueries.yml, tools/sigclient/functionalQueries/multi_value.json, tools/sigclient/functionalQueries/mvappend.json, tools/sigclient/functionalQueries/mvdedup.json
Implementation of `mvdedup` & `mvappend`. Docs can be found [here](https://docs.splunk.com/Documentation/Splunk/9.1.1/SearchReference/MultivalueEvalFunctions#mvappend.28.26lt.3Bvalues.26gt.3B.29)
Added individual functional tests + updated `multi_value.json` functional test to include `mvappend`
=> SPL: Implement eval commands mvdedup + mvappend

pkg/segment/query/processor/statscommand.go, pkg/utils/maputils.go
Improve performance by converting a read-only map to a slice before we iterate it several times. Map iteration has more overhead than slice iteration
Saw about 5% faster response time on this query with 100 million records:
```
* | eval height=ResolutionHeight / 10 | stats avg(height) as avg, count(height) as count, sum(height) as sum by ResolutionWidth | sort -ResolutionWidth
```
CPU time of `processGroupByRequest()` dropped from 14.2 seconds to 12.7 seconds.
=> Avoid repeated map iteration

pkg/virtualtable/virtualtable.go
The length of finalResults is already set to be length of the finalResultsMap that the loop is iterating over without any escape path.
=> Remove redundant re-slicing

pkg/segment/query/iqr/intermediateQueryResult.go, pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/queryprocessor.go, pkg/segment/query/processor/queryprocessor_test.go, pkg/segment/query/processor/sortcommand.go
Similar to #2772 but for `sort`
Correctness: CICD
Performance: query time dropped from 5.0 seconds to 1.8 seconds for 100 million records on
```
SearchPhrase != "" | sort 10 str(SearchPhrase) | fields SearchPhrase
```
=> Parallelize the sort command

pkg/segment/query/processor/dataprocessor.go, pkg/segment/query/processor/queryprocessor.go
Similar to #2772 and #2811 but for `timechart`
Tested with 100 million records on
```
ResolutionHeight>1500 | eval height=ResolutionHeight / 10 | timechart span=10m avg(height) as avg, count(height) as count, sum(height) as sum by ResolutionWidth | fields "sum: other"
```
This PR dropped the query time from 10.0 seconds to 3.8 seconds.
=> Parallelize timechart

pkg/utils/heap.go, pkg/utils/heap_test.go
To evaluate queries with a `sort` command where only the top `N` results are kept and `N` is small (< 1000), we use a heap to do the sorting. When the heap is at capacity, we were pushing each item and then popping an item. With this PR, we only push if we're not going to immediately pop the same item.
Decreased this query time by about 15%
```
SearchPhrase != "" | sort 10 str(EventTime) | fields SearchPhrase, EventTime
```
=> Improve sorting performance with small limit

pkg/segment/reader/segread/multicolreader.go
With 100 million records, this query
```
CounterID=62 DontCountHits = 0 IsRefresh = 0 
| eval ptime = strptime(EventDate,"%Y-%m-%d") 
| where ptime >= 1372636800 AND ptime <= 1375228800
| stats count
```
response time dropped from 1.58 to 1.18 seconds
=> Init map with correct size

pkg/ast/spl/tests/splParser_test.go
Pretty self-explanatory; I got the below error while running `make pr`
```
--- FAIL: Test_Aggs (0.07s)
splParser_test.go:10207:
Error Trace:    /siglens/pkg/ast/spl/tests/splParser_test.go:10207
/siglens/pkg/ast/spl/tests/splParser_test.go:10384
Error:          Not equal:
expected: 47.895294267132456
actual  : 47.89529426713246
Test:           Test_Aggs
```
=> Float equality comparison in SPL parser tests

pkg/config/config.go, pkg/config/config_test.go, pkg/segment/memory/limit/memorylimit.go, pkg/segment/metadata/metadata.go, pkg/segment/metadata/metricsmetadata.go, pkg/segment/structs/memorystructs.go, pkg/segment/utils/segutils.go, pkg/segment/writer/metrics/metricssegment.go, pkg/segment/writer/unrotatedquery.go
- Add convenience functions for getting the amount of available RAM
- Consolidate helper functions into one generic one, and clarify MiB instead of MB.
=> Add memory tracking helpers

pkg/utils/gobutils.go, pkg/utils/gobutils_test.go
This registers our custom types that implement the gob encode/decode interfaces so that these custom implementations get called even if these types are passed as `interface{}` values.
From the [documentation](https://pkg.go.dev/encoding/gob#Register)
> Register records a type, identified by a value for that type, under its internal type name. That name will identify the concrete type of a value sent or received as an interface variable. Only types that will be transferred as implementations of interface values need to be registered. Expecting to be used only during initialization, it panics if the mapping between types and names is not a bijection.
=> Register custom Gob types

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg
changed the StrEnc of percentile related functions to enable multiple percentile calculations in a single command.
Eg - ` * | streamstats sum(account.balance) as visitors | stats perc50(visitors) perc95(visitors)`
Earlier `perc95` would overwrite the results of `perc50`
=> Fix: change StrEnc for percentile to enable multiple calculations

pkg/ast/spl/spl.go, pkg/ast/spl/spl.peg, pkg/ast/spl/tests/splParser_test.go
This fixes two issue with floating point numbers in the parser tests:
1. A number (e.g. `0.0005`) may be formatted using scientific notation (`5e-4`) when it is converted to string using `fmt.Sprintf()`. This results in expressions such as `eval(5e-4)`. SigLens does not currently support the use of `e` in floats.
2. [While generating the tests](https://github.com/t-sunk/siglens/blob/9384a28b1c9870e2239df69b61df8f3d2906fa96/pkg/ast/spl/tests/splParser_test.go#L10176), we use [`strconv.FormatFloat()`](https://pkg.go.dev/strconv#FormatFloat), which is meant for use with [`strconv.ParseFloat()`](https://pkg.go.dev/strconv#ParseFloat). However we were using [a different function](https://github.com/siglens/siglens/blob/9ccb4c73a2a383cacf1a49819d59d31817b6c1ff/pkg/ast/spl/spl.peg#L4010) to …
=> Fix float formatting issues
